// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi.common;

/**
 * {@code DXGI_MODE_ROTATION} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code DXGI_MODE_ROTATION} as it is the same as the enumeration name.
 * </p>
 */
public class DXGI_MODE_ROTATION {
    /**
     * Enumeration value {@code DXGI_MODE_ROTATION_UNSPECIFIED}
     */
    public static final int UNSPECIFIED = 0;

    /**
     * Enumeration value {@code DXGI_MODE_ROTATION_IDENTITY}
     */
    public static final int IDENTITY = 1;

    /**
     * Enumeration value {@code DXGI_MODE_ROTATION_ROTATE90}
     */
    public static final int ROTATE90 = 2;

    /**
     * Enumeration value {@code DXGI_MODE_ROTATION_ROTATE180}
     */
    public static final int ROTATE180 = 3;

    /**
     * Enumeration value {@code DXGI_MODE_ROTATION_ROTATE270}
     */
    public static final int ROTATE270 = 4;


    private DXGI_MODE_ROTATION() {}
}
