// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi.common;

/**
 * {@code DXGI_COLOR_SPACE_TYPE} enumeration
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgicommon/ne-dxgicommon-dxgi_color_space_type">DXGI_COLOR_SPACE_TYPE (Microsoft)</a>
 */
public class DXGI_COLOR_SPACE_TYPE {
    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709}
     */
    public static final int DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709 = 0;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_RGB_FULL_G10_NONE_P709}
     */
    public static final int DXGI_COLOR_SPACE_RGB_FULL_G10_NONE_P709 = 1;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_RGB_STUDIO_G22_NONE_P709}
     */
    public static final int DXGI_COLOR_SPACE_RGB_STUDIO_G22_NONE_P709 = 2;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_RGB_STUDIO_G22_NONE_P2020}
     */
    public static final int DXGI_COLOR_SPACE_RGB_STUDIO_G22_NONE_P2020 = 3;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_RESERVED}
     */
    public static final int DXGI_COLOR_SPACE_RESERVED = 4;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_FULL_G22_NONE_P709_X601}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_FULL_G22_NONE_P709_X601 = 5;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_LEFT_P601}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_LEFT_P601 = 6;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_FULL_G22_LEFT_P601}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_FULL_G22_LEFT_P601 = 7;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_LEFT_P709}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_LEFT_P709 = 8;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_FULL_G22_LEFT_P709}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_FULL_G22_LEFT_P709 = 9;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_LEFT_P2020}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_LEFT_P2020 = 10;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_FULL_G22_LEFT_P2020}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_FULL_G22_LEFT_P2020 = 11;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020}
     */
    public static final int DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020 = 12;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_LEFT_P2020}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_LEFT_P2020 = 13;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_RGB_STUDIO_G2084_NONE_P2020}
     */
    public static final int DXGI_COLOR_SPACE_RGB_STUDIO_G2084_NONE_P2020 = 14;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_TOPLEFT_P2020}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_TOPLEFT_P2020 = 15;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_TOPLEFT_P2020}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_TOPLEFT_P2020 = 16;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P2020}
     */
    public static final int DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P2020 = 17;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_STUDIO_GHLG_TOPLEFT_P2020}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_STUDIO_GHLG_TOPLEFT_P2020 = 18;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_FULL_GHLG_TOPLEFT_P2020}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_FULL_GHLG_TOPLEFT_P2020 = 19;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_RGB_STUDIO_G24_NONE_P709}
     */
    public static final int DXGI_COLOR_SPACE_RGB_STUDIO_G24_NONE_P709 = 20;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_RGB_STUDIO_G24_NONE_P2020}
     */
    public static final int DXGI_COLOR_SPACE_RGB_STUDIO_G24_NONE_P2020 = 21;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_STUDIO_G24_LEFT_P709}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_STUDIO_G24_LEFT_P709 = 22;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_STUDIO_G24_LEFT_P2020}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_STUDIO_G24_LEFT_P2020 = 23;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_YCBCR_STUDIO_G24_TOPLEFT_P2020}
     */
    public static final int DXGI_COLOR_SPACE_YCBCR_STUDIO_G24_TOPLEFT_P2020 = 24;

    /**
     * Enumeration value {@code DXGI_COLOR_SPACE_CUSTOM}
     */
    public static final int DXGI_COLOR_SPACE_CUSTOM = -1;


    private DXGI_COLOR_SPACE_TYPE() {}
}
