// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi.common;

import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code DXGI_RATIONAL} structure
 * <p>
 * {@snippet lang=c :
 * struct DXGI_RATIONAL {
 *    DWORD Numerator;
 *    DWORD Denominator;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgicommon/ns-dxgicommon-dxgi_rational">DXGI_RATIONAL (Microsoft)</a>
 */
public class DXGI_RATIONAL {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("Numerator"),
        JAVA_INT.withName("Denominator")
    );

    /**
     * Gets the layout of the struct {@code DXGI_RATIONAL}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DXGI_RATIONAL} (in bytes).
     */
    public static long sizeof() {
        return 8L;
    }

    /**
     * Gets the offset of the field {@code Numerator} (in bytes).
     */
    public static long Numerator$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code Numerator} in {@code segment}.
     */
    public static int Numerator(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code Numerator} in {@code segment} to {@code value}.
     */
    public static void Numerator(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code Denominator} (in bytes).
     */
    public static long Denominator$offset() {
        return 4L;
    }

    /**
     * Gets the value of field {@code Denominator} in {@code segment}.
     */
    public static int Denominator(MemorySegment segment) {
        return segment.get(JAVA_INT, 4L);
    }

    /**
     * Sets the field {@code Denominator} in {@code segment} to {@code value}.
     */
    public static void Denominator(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 4L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code DXGI_RATIONAL}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(8L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DXGI_RATIONAL} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(8L * index, 8L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(8L * elementCount, 4L);
    }

    private DXGI_RATIONAL () {}
}
