// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi.common;

/**
 * {@code DXGI_MODE_SCALING} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code DXGI_MODE_SCALING} as it is the same as the enumeration name.
 * </p>
 */
public class DXGI_MODE_SCALING {
    /**
     * Enumeration value {@code DXGI_MODE_SCALING_UNSPECIFIED}
     */
    public static final int UNSPECIFIED = 0;

    /**
     * Enumeration value {@code DXGI_MODE_SCALING_CENTERED}
     */
    public static final int CENTERED = 1;

    /**
     * Enumeration value {@code DXGI_MODE_SCALING_STRETCHED}
     */
    public static final int STRETCHED = 2;


    private DXGI_MODE_SCALING() {}
}
