modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "hdr_mod"
version = "${version}"
displayName = "HDR Mod"
logoFile = "icon.png"
credits = "XgarhontX, moyongxin, CommandGenius"
authors = "rrtt217"
description = '''
Enable native HDR in Minecraft with Iris shaders.
'''
#logoFile = ""

[[mods.mixin]]
config = "hdr_mod.mixins.json"

[[dependencies.hdr_mod]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.hdr_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hdr_mod]]
modId = "cloth_config"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hdr_mod]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[mods."sodium:options"]
"mixin.features.render.compositing" = false