// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d.fxc;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.*;

/**
 * Functions of namespace {@code Windows.Win32.Graphics.Direct3D.Fxc}
 */
public class Apis {

    

    private static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup("D3DCOMPILER_47.dll", Arena.global());
    private static final Linker LINKER = Linker.nativeLinker();
    private static final AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    private static final AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));
    private static final AddressLayout ADDRESS$STRUCT_16_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(8));

    private static class D3DCompile$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_LONG, ADDRESS$UNKNOWN_SIZE, ADDRESS$STRUCT_16_8, ADDRESS$ADDRESS, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, JAVA_INT, JAVA_INT, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = LINKER.downcallHandle(SYMBOL_LOOKUP.findOrThrow("D3DCompile"), DESC);
    }

    /**
     * Gets the function descriptor for {@code D3DCompile}
     */
    public static FunctionDescriptor D3DCompile$descriptor() {
        return D3DCompile$IMPL.DESC;
    }

    /**
     * Gets the method handle for {@code D3DCompile}
     */
    public static MethodHandle D3DCompile$handle() {
        return D3DCompile$IMPL.HANDLE;
    }

    /**
     * {@code D3DCompile} function
     * <p>
     * {@snippet lang=c :
     * HRESULT D3DCompile(
     *     void* pSrcData,
     *     ULONG_PTR SrcDataSize,
     *     PSTR pSourceName,
     *     D3D_SHADER_MACRO* pDefines,
     *     ID3DInclude pInclude,
     *     PSTR pEntrypoint,
     *     PSTR pTarget,
     *     DWORD Flags1,
     *     DWORD Flags2,
     *     ID3DBlob* ppCode,
     *     ID3DBlob* ppErrorMsgs
     * );
     * }
     * </p>
     *
     * @see <a href="https://learn.microsoft.com/windows/win32/api/d3dcompiler/nf-d3dcompiler-d3dcompile">D3DCompile (Microsoft)</a>
     */
    public static int D3DCompile(MemorySegment pSrcData, long SrcDataSize, MemorySegment pSourceName, MemorySegment pDefines, MemorySegment pInclude, MemorySegment pEntrypoint, MemorySegment pTarget, int Flags1, int Flags2, MemorySegment ppCode, MemorySegment ppErrorMsgs) {
        try {
            return (int) D3DCompile$IMPL.HANDLE.invokeExact(pSrcData, SrcDataSize, pSourceName, pDefines, pInclude, pEntrypoint, pTarget, Flags1, Flags2, ppCode, ppErrorMsgs);
        } catch (Throwable ex) {
            throw new RuntimeException(ex);
        }
    }

}
