/*
Auto-generated by Ixeris. Cannot directly use their version because of inconsistent package names.
*/

package xyz.rrtt217.HDRMod.compat.ixeris;

import it.unimi.dsi.fastutil.longs.Long2ReferenceMap;
import it.unimi.dsi.fastutil.longs.Long2ReferenceArrayMap;
import it.unimi.dsi.fastutil.objects.ReferenceArrayList;
import me.decce.ixeris.core.threading.RenderThreadDispatcher;
import xyz.rrtt217.HDRMod.util.ime.*;
import org.lwjgl.system.Callback;

public class PreeditCandidateCallbackDispatcher {
    private static final Long2ReferenceMap<PreeditCandidateCallbackDispatcher> instance = new Long2ReferenceArrayMap<>(1);

    private final ReferenceArrayList<GLFWPreeditCandidateCallbackI> mainThreadCallbacks = new ReferenceArrayList<>(1);
    private boolean lastCallbackSet;
    public GLFWPreeditCandidateCallbackI lastCallback;
    public long lastCallbackAddress;

    private final long window;
    public volatile boolean suppressChecks;

    private PreeditCandidateCallbackDispatcher(long window) {
        this.window = window;
    }

    public synchronized static PreeditCandidateCallbackDispatcher get(long window) {
        if (!instance.containsKey(window)) {
            instance.put(window, new PreeditCandidateCallbackDispatcher(window));
            instance.get(window).validate();
        }
        return instance.get(window);
    }

    public synchronized void registerMainThreadCallback(GLFWPreeditCandidateCallbackI callback) {
        mainThreadCallbacks.add(callback);
        this.validate();
    }

    public synchronized long update(long newAddress) {
        suppressChecks = true;
        long ret = lastCallbackAddress;
        if (newAddress == 0L && this.mainThreadCallbacks.isEmpty()) {
            GLFWIMEUtils.nglfwSetPreeditCandidateCallback(window, 0L);
        }
        else {
            GLFWIMEUtils.nglfwSetPreeditCandidateCallback(window, CommonCallbacks_334.preeditCandidateCallback.address());
        }
        lastCallbackAddress = newAddress;
        if (!lastCallbackSet) {
            lastCallback = newAddress == 0L ? null : Callback.get(newAddress);
        }
        lastCallbackSet = false;
        suppressChecks = false;
        return ret;
    }

    public synchronized void update(GLFWPreeditCandidateCallbackI callback) {
        lastCallback = callback;
        lastCallbackSet = true;
    }

    public synchronized void validate() {
        suppressChecks = true;
        var current = GLFWIMEUtils.nglfwSetPreeditCandidateCallback(window, CommonCallbacks_334.preeditCandidateCallback.address());
        if (current == 0L) {
            if (this.mainThreadCallbacks.isEmpty()) {
                // Remove callback when not needed
                GLFWIMEUtils.nglfwSetPreeditCandidateCallback(window, 0L);
            }
        }
        else if (current != CommonCallbacks_334.preeditCandidateCallback.address()) {
            // This only happens when mods register callbacks without using LWJGL (e.x. directly in native code)
            lastCallback = Callback.get(current);
            lastCallbackAddress = current;
        }
        suppressChecks = false;
    }

    public void onCallback(long window, int candidates_count, int selected_index, int page_start, int page_size) {
        if (this.window != window) {
            return;
        }
        for (int i = 0; i < mainThreadCallbacks.size(); i++) {
            mainThreadCallbacks.get(i).invoke(window, candidates_count, selected_index, page_start, page_size);
        }
        if (lastCallback != null) {
            var callback = lastCallback; // Keep a reference to the current callback; they are used as FunctionalInterface's so there are no issue even if the callback is already freed when we use it
            RenderThreadDispatcher.runLater((DispatchedRunnable) () -> {
                callback.invoke(window, candidates_count, selected_index, page_start, page_size);
            });
        }
    }

    @FunctionalInterface
    public interface DispatchedRunnable extends Runnable {
    }
}
