
package xyz.rrtt217.HDRMod.core;

import ar.com.hjg.pngj.ImageInfo;
import ar.com.hjg.pngj.ImageLineInt;
import ar.com.hjg.pngj.PngWriter;
import ar.com.hjg.pngj.chunks.PngChunkICCP;
import com.mojang.blaze3d.pipeline.RenderTarget;
import com.mojang.blaze3d.platform.GlStateManager;
import com.mojang.blaze3d.systems.RenderSystem;
import me.shedaniel.autoconfig.AutoConfig;
import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.ClickEvent;
import net.minecraft.network.chat.Component;
import net.minecraft.Util;
import org.jetbrains.annotations.Nullable;
import org.lwjgl.opengl.GL30;
import org.lwjgl.system.MemoryUtil;
import xyz.rrtt217.HDRMod.HDRMod;
import xyz.rrtt217.HDRMod.config.HDRModConfig;
import xyz.rrtt217.HDRMod.util.*;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.file.Files;
import java.util.function.Consumer;

import static xyz.rrtt217.HDRMod.HDRMod.enableHDR;

public class PngjHDRScreenshot {
    public static final String SCREENSHOT_DIR = "screenshots";
    public static void grab(File baseDirectory, RenderTarget renderTarget, Consumer<Component> consumer) {
        grab(baseDirectory, null, renderTarget, consumer);
    }
    public static void grab(File baseDirectory, @Nullable String string, RenderTarget renderTarget, Consumer<Component> consumer) {
        // Mod config.
        HDRModConfig config = AutoConfig.getConfigHolder(HDRModConfig.class).getConfig();
        if(!enableHDR) return;
        // Width and height.
        int width = renderTarget.width;
        int height = renderTarget.height;

        // Pngj things.
        ImageInfo imi = new ImageInfo(width, height, 16, false);
        File screenshotFile = getScreenshotFile(new File(baseDirectory, SCREENSHOT_DIR));
        HDRMod.LOGGER.debug("Screenshot file location: {}", screenshotFile.getAbsolutePath());
        PngWriter png = new PngWriter(screenshotFile, imi);
        png.getMetadata().setDpi(100.0);
        png.getMetadata().setTimeNow(0);
        // Use the fastest compress level.
        png.setCompLevel(1);
        PngChunkICCP chunkICCP = new PngChunkICCP(imi);

        // Extracted iCCP that is supposed to generated by libjxl
        try(InputStream is = LibraryExtractor.class.getClassLoader().getResourceAsStream("iccs/RGB_D65_202_Rel_PeQ.icc")){
            if(is == null) {
                throw new FileNotFoundException("Could not find icc file: " + string);
            }
            chunkICCP.setProfileNameAndContent("RGB_D65_202_Rel_PeQ",is.readAllBytes());
            png.queueChunk(chunkICCP);
        }
        catch (Exception e) {
            HDRMod.LOGGER.error("Error while trying to grab screenshot for {}", string, e);
            return;
        }
        // Get the buffer.
        long pixels = MemoryUtil.nmemAlloc((long) width * height * 4 * 2);
        RenderSystem.bindTexture(renderTarget.getColorTextureId());
        GlStateManager._pixelStore(GL30.GL_UNPACK_ALIGNMENT, 4);
        GlStateManager._getTexImage(3553, 0, GL30.GL_RGBA, GL30.GL_HALF_FLOAT, pixels);
        ByteBuffer buffer = MemoryUtil.memByteBuffer(pixels, width * height * 4 * 2);
        // The actual screenshot part
        float[] datas = new float[4];
        float[] rgb = new float[3];
        short bits;
        // Do remember to flip Y.
        for (int y = height - 1; y >= 0; y--) {
            // Line by line.
            ImageLineInt line = new ImageLineInt(imi);
            int[] scanline = line.getScanline();
            for (int x = 0; x < width; x++) {
                // Interpret data.
                int basePos = ((y * width + x) * 4) * 2;
                // RGBA16F.
                for (int c = 0; c < 4; c++) {
                    bits = buffer.getShort(basePos + c * 2);
                    datas[c] = Float.float16ToFloat(bits);
                }
                // Do transform.
                System.arraycopy(datas, 0, rgb, 0, 3);
                System.arraycopy(ColorTransforms.sRGBDecodeSafe(rgb), 0, datas, 0, 3);
                System.arraycopy(datas, 0, rgb, 0, 3);
                System.arraycopy(ColorTransforms.linearColorspaceTransform(rgb, ColorTransforms.linear709to2020Matrix), 0, datas, 0, 3);
                float EotfEmulate = config.customEotfEmulate < 0 ? GLFWColorManagement.glfwGetWindowSdrWhiteLevel(Minecraft.getInstance().getWindow().getWindow()) : config.customEotfEmulate;
                if(EotfEmulate > 0) {
                    System.arraycopy(datas, 0, rgb, 0, 3);
                    System.arraycopy(ColorTransforms.eotfEmulate(rgb, EotfEmulate), 0, datas, 0, 3);
                }
                System.arraycopy(datas, 0, rgb, 0, 3);
                System.arraycopy(ColorTransforms.PQEncode(rgb, config.uiBrightness < 0 ? GLFWColorManagement.glfwGetWindowSdrWhiteLevel(Minecraft.getInstance().getWindow().getWindow()) : config.uiBrightness), 0, datas, 0, 3);
                // Write to line.
                for (int c = 0; c < png.imgInfo.channels; c++) {
                    scanline[x * png.imgInfo.channels + c] = (int) (datas[c] * 65535);
                }
            }
            // Write to file.
            png.writeRow(line);
        }
        // Close the file.
        png.end();
        // Close the buffer.
        MemoryUtil.memFree(buffer);
        // Send component.
        Component component = Component.literal(screenshotFile.getName()).withStyle(ChatFormatting.UNDERLINE).withStyle((style) -> style.withClickEvent(new ClickEvent(ClickEvent.Action.OPEN_FILE, screenshotFile.getAbsolutePath())));
        consumer.accept(Component.translatable("screenshot.success", new Object[]{component}));
    }
    private static File getScreenshotFile(File baseDirectory) {
        if(!baseDirectory.exists()) {
            try{
                Files.createDirectories(baseDirectory.toPath());
            } catch (IOException e) {
                HDRMod.LOGGER.error("Error while creating screenshot directory {}", baseDirectory, e);
            }
        }
        String string = Util.getFilenameFormattedDateTime();
        int i = 1;
        while(true) {
            File screenshotFile = new File(baseDirectory, string + (i == 1 ? "" : "_" + i) + "_hdr" + ".png");
            if (!screenshotFile.exists()) {
                return screenshotFile;
            }
            ++i;
        }
    }
}
