package xyz.rrtt217.HDRMod.core;

import ar.com.hjg.pngj.ImageInfo;
import ar.com.hjg.pngj.ImageLineInt;
import ar.com.hjg.pngj.PngWriter;
import ar.com.hjg.pngj.chunks.PngChunkICCP;
import com.mojang.blaze3d.buffers.GpuBuffer;
import com.mojang.blaze3d.pipeline.RenderTarget;
import com.mojang.blaze3d.platform.NativeImage;
import com.mojang.blaze3d.systems.CommandEncoder;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.textures.GpuTexture;
import me.shedaniel.autoconfig.AutoConfig;
import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.ClickEvent;
import net.minecraft.network.chat.Component;
import net.minecraft.util.Util;
import org.jspecify.annotations.Nullable;
import org.lwjgl.opengl.GL30;
import xyz.rrtt217.HDRMod.HDRMod;
import xyz.rrtt217.HDRMod.config.HDRModConfig;
import xyz.rrtt217.HDRMod.util.*;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.ShortBuffer;
import java.nio.file.Files;
import java.util.function.Consumer;

import static xyz.rrtt217.HDRMod.HDRMod.*;

public class PngjHDRScreenshot {
    public static final String SCREENSHOT_DIR = "screenshots";
    public static void grab(File baseDirectory, RenderTarget renderTarget, Consumer<Component> consumer) {
        grab(baseDirectory, null, renderTarget, consumer);
    }

    record ImageBuffer(ShortBuffer shortBuffer, int width, int height){}

    public static void grab(File baseDirectory, @Nullable String string, RenderTarget renderTarget, Consumer<Component> consumer){
            if (!enableHDR) return;
            takeScreenshot(renderTarget,(imageBuffer -> {
                int width = imageBuffer.width();
                int height = imageBuffer.height();
                File screenshotFile = getScreenshotFile(new File(baseDirectory, SCREENSHOT_DIR));
                HDRMod.LOGGER.debug("Screenshot file location: {}", screenshotFile.getAbsolutePath());
                Util.ioPool().execute(() -> {
                    // Pngj things.
                    ImageInfo imi = new ImageInfo(width, height, 16, false);
                    PngWriter png = new PngWriter(screenshotFile, imi);
                    png.getMetadata().setDpi(100.0);
                    png.getMetadata().setTimeNow(0);
                    // Use the fastest compress level.
                    //png.setCompLevel(1);
                    PngChunkICCP chunkICCP = new PngChunkICCP(imi);
                    // Extracted iCCP that is supposed to generated by libjxl
                    try (InputStream is = LibraryExtractor.class.getClassLoader().getResourceAsStream("iccs/RGB_D65_202_Rel_PeQ.icc")) {
                        if (is == null) {
                            throw new FileNotFoundException("Could not find icc file: " + string);
                        }
                        chunkICCP.setProfileNameAndContent("RGB_D65_202_Rel_PeQ", is.readAllBytes());
                        png.queueChunk(chunkICCP);
                    } catch (Exception e) {
                        HDRMod.LOGGER.error("Error while trying to grab screenshot for {}", string, e);
                        return;
                    }
                    short bits;
                    for (int y = height - 1; y >= 0; y--) {
                        // Line by line.
                        ImageLineInt line = new ImageLineInt(imi);
                        int[] scanline = line.getScanline();
                        for (int x = 0; x < width; x++) {
                            // Interpret data.
                            int basePos = ((y * width + x) * 4);
                            // RGBA16 UNORM.
                            for (int c = 0; c < png.imgInfo.channels; c++) {
                                bits = imageBuffer.shortBuffer().get(basePos + c);
                                scanline[x * png.imgInfo.channels + c] = bits;
                            }
                        }
                        // Write to file.
                        png.writeRow(line);
                    }
                    // Close the file.
                    png.end();
                });
                Component component = Component.literal(screenshotFile.getName()).withStyle(ChatFormatting.UNDERLINE).withStyle((style) -> style.withClickEvent(new ClickEvent.OpenFile(screenshotFile.getAbsoluteFile())));
                consumer.accept(Component.translatable("screenshot.success", new Object[]{component}));
            }));
    }
    public static void takeScreenshot(RenderTarget renderTarget, Consumer<ImageBuffer> consumer){
        HDRModConfig config = AutoConfig.getConfigHolder(HDRModConfig.class).getConfig();

        // Create ScreenshotColorTransformRenderer if there's not one.
        if(ScreenshotColorTransformRenderer == null){
            ScreenshotColorTransformRenderer = new ColorTransformRenderer(renderTarget, "Screenshot");
        }
        // Update ScreenshotColorTransformRenderer.srcTarget.
        if(ScreenshotColorTransformRenderer.getSrcTarget() != renderTarget){
            ScreenshotColorTransformRenderer.setSrcTarget(renderTarget);
        }
        ScreenshotColorTransformRenderer.updateColorTransformUniforms(
                config.uiBrightness < 0 ? GLFWColorManagementUtils.glfwGetWindowSdrWhiteLevel(Minecraft.getInstance().getWindow().handle()) : config.uiBrightness, // For UI Brightness
                config.customEotfEmulate < 0 ? GLFWColorManagementUtils.glfwGetWindowSdrWhiteLevel(Minecraft.getInstance().getWindow().handle()) : config.customEotfEmulate,
                Enums.Primaries.BT2020.getId(),
                Enums.TransferFunction.ST2084_PQ.getId()
        );
        ScreenshotColorTransformRenderer.render();

        // The actual screenshot part
        GpuTexture gpuTexture = ScreenshotColorTransformRenderer.getDstTexture();
        if (gpuTexture == null) {
            throw new IllegalStateException("color texture is null");
        }
        if (!enableHDR) return;
        // Width and height.
        int width = gpuTexture.getWidth(0);
        int height = gpuTexture.getHeight(0);

        // Get the buffer.
        GpuBuffer gpuBuffer = RenderSystem.getDevice().createBuffer(() -> "HDR Mod Screenshot buffer", 9, (long) width * (long) height * 8L);

        CommandEncoder commandEncoder = RenderSystem.getDevice().createCommandEncoder();
        TextureUpgradeUtils.setTargetReadPixelFormat(GL30.GL_UNSIGNED_SHORT);
        RenderSystem.getDevice().createCommandEncoder().copyTextureToBuffer(gpuTexture, gpuBuffer, 0L, () -> {
            try (GpuBuffer.MappedView mappedView = commandEncoder.mapBuffer(gpuBuffer, true, false)) {
                ShortBuffer shortBuffer = ShortBuffer.allocate( width * height * 4);
                // You should read mappedView.data() in the same way as TextureUpgradeUtils.setTargetReadPixelFormat() specifies. Any other ways (e.g. call bytebuffer.put(mappedView.data()) for GL30.GL_UNSIGNED_SHORT is undefined.
                shortBuffer.put(mappedView.data().asShortBuffer());
                shortBuffer.flip();
                consumer.accept(new ImageBuffer(shortBuffer, width, height));
            } catch (Exception e) {
                HDRMod.LOGGER.error("Error while trying to capture screenshot:" , e);
            }
            // Close the buffer.
            gpuBuffer.close();
        }, 0);
    }
    private static File getScreenshotFile(File baseDirectory) {
        if(!baseDirectory.exists()) {
            try{
                Files.createDirectories(baseDirectory.toPath());
            } catch (IOException e) {
                HDRMod.LOGGER.error("Error while creating screenshot directory {}", baseDirectory, e);
            }
        }
        String string = Util.getFilenameFormattedDateTime();
        int i = 1;
        while(true) {
            File screenshotFile = new File(baseDirectory, string + (i == 1 ? "" : "_" + i) + "_hdr" + ".png");
            if (!screenshotFile.exists()) {
                return screenshotFile;
            }
            ++i;
        }
    }
}

