package xyz.rrtt217.HDRMod.core;

import ar.com.hjg.pngj.ImageInfo;
import ar.com.hjg.pngj.ImageLineInt;
import ar.com.hjg.pngj.PngWriter;
import ar.com.hjg.pngj.chunks.PngChunkICCP;
import com.mojang.blaze3d.pipeline.RenderTarget;
import com.mojang.blaze3d.platform.GlStateManager;
import com.mojang.blaze3d.systems.RenderSystem;
import me.shedaniel.autoconfig.AutoConfig;
import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.ClickEvent;
import net.minecraft.network.chat.Component;
import net.minecraft.Util;
import org.jetbrains.annotations.Nullable;
import org.lwjgl.opengl.GL30;
import org.lwjgl.system.MemoryUtil;
import xyz.rrtt217.HDRMod.HDRMod;
import xyz.rrtt217.HDRMod.config.HDRModConfig;
import xyz.rrtt217.HDRMod.util.*;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.ShortBuffer;
import java.nio.file.Files;
import java.util.function.Consumer;

import static xyz.rrtt217.HDRMod.HDRMod.*;

public class PngjHDRScreenshot {
    public static final String SCREENSHOT_DIR = "screenshots";
    public static void grab(File baseDirectory, RenderTarget renderTarget, Consumer<Component> consumer) {
        grab(baseDirectory, null, renderTarget, consumer);
    }

    record ImageBuffer(ShortBuffer shortBuffer, int width, int height){}

    public static void grab(File baseDirectory, @Nullable String string, RenderTarget renderTarget, Consumer<Component> consumer){
        grab(baseDirectory, string, renderTarget, 2 ,consumer);
    }

    // Implements nearest neighbor sampling. Useful with mods like RenderScale.
    // Unlike vanilla, we accept floating point scale and do not throw an error when image size is not divisible by downscale factor.
    public static void grab(File baseDirectory, @Nullable String string, RenderTarget renderTarget, float i, Consumer<Component> consumer){
            if (!enableHDR) return;
            takeScreenshot(renderTarget,(imageBuffer -> {
                int origWidth = imageBuffer.width();
                int origHeight = imageBuffer.height();
                float iEffective = Math.max(i, 1);
                int newWidth = Math.max((int)(origWidth / iEffective), 1);
                int newHeight = Math.max((int)(origHeight / iEffective), 1);
                float stepX = (float) origWidth / newWidth;
                float stepY = (float) origHeight / newHeight;
                File screenshotFile = getScreenshotFile(new File(baseDirectory, SCREENSHOT_DIR));
                HDRMod.LOGGER.debug("Screenshot file location: {}", screenshotFile.getAbsolutePath());
                Util.ioPool().execute(() -> {
                    // Pngj things.
                    ImageInfo imi = new ImageInfo(newWidth, newHeight, 16, false);
                    PngWriter png = new PngWriter(screenshotFile, imi);
                    png.getMetadata().setDpi(100.0);
                    png.getMetadata().setTimeNow(0);

                    HDRModConfig config = AutoConfig.getConfigHolder(HDRModConfig.class).getConfig();
                    png.setCompLevel(Math.max(Math.min(config.screenshotCompressLevel, 9), -1));
                    PngChunkICCP chunkICCP = new PngChunkICCP(imi);
                    // Extracted iCCP that is supposed to generated by libjxl.
                    try (InputStream is = LibraryExtractor.class.getClassLoader().getResourceAsStream("iccs/RGB_D65_202_Rel_PeQ.icc")) {
                        if (is == null) {
                            throw new FileNotFoundException("Could not find icc file: " + string);
                        }
                        chunkICCP.setProfileNameAndContent("RGB_D65_202_Rel_PeQ", is.readAllBytes());
                        png.queueChunk(chunkICCP);
                    } catch (Exception e) {
                        HDRMod.LOGGER.error("Error while trying to grab screenshot for {}", string, e);
                        return;
                    }

                    short bits;

                    // Read from buffer and write to PNG.
                    for (int y = newHeight - 1; y >= 0; y--) {
                        int srcY = (int) (y * stepY);
                        // Line by line.
                        ImageLineInt line = new ImageLineInt(imi);
                        int[] scanline = line.getScanline();
                        for (int x = 0; x < newWidth; x++) {
                            int srcX = (int) (x * stepX);
                            // Interpret data.
                            int basePos = (srcY * origWidth + srcX) * 4;
                            // RGBA16 UNORM.
                            for (int c = 0; c < png.imgInfo.channels; c++) {
                                bits = imageBuffer.shortBuffer().get(basePos + c);
                                scanline[x * png.imgInfo.channels + c] = bits;
                            }
                        }
                        // Write to file.
                        png.writeRow(line);
                    }
                    // Close the file.
                    png.end();
                });
                Component component = Component.literal(screenshotFile.getName()).withStyle(ChatFormatting.UNDERLINE).withStyle((style) -> style.withClickEvent(new ClickEvent(ClickEvent.Action.OPEN_FILE, screenshotFile.getAbsolutePath())));
                consumer.accept(Component.translatable("screenshot.success", new Object[]{component}));
            }));
    }
    public static void takeScreenshot(RenderTarget renderTarget, Consumer<ImageBuffer> consumer){
        HDRModConfig config = AutoConfig.getConfigHolder(HDRModConfig.class).getConfig();
        if (!enableHDR) return;
        // Create ScreenshotColorTransformRenderer if there's not one.
        if(ScreenshotColorTransformRenderer == null){
            try {
                ScreenshotColorTransformRenderer = new ColorTransformRenderer(renderTarget, "Screenshot");
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
        // Update ScreenshotColorTransformRenderer.srcTarget.
        if(ScreenshotColorTransformRenderer.getSrcTarget() != renderTarget){
            ScreenshotColorTransformRenderer.setSrcTarget(renderTarget);
        }
        ScreenshotColorTransformRenderer.updateColorTransformUniforms(
                config.uiBrightness < 0 ? GLFWColorManagementUtils.glfwGetWindowSdrWhiteLevel(Minecraft.getInstance().getWindow().getWindow()) : config.uiBrightness, // For UI Brightness
                config.customEotfEmulate < 0 ? GLFWColorManagementUtils.glfwGetWindowSdrWhiteLevel(Minecraft.getInstance().getWindow().getWindow()) : config.customEotfEmulate,
                Enums.Primaries.BT2020.getId(),
                Enums.TransferFunction.ST2084_PQ.getId()
        );
        ScreenshotColorTransformRenderer.render();

        // Width and height.
        int width = renderTarget.width;
        int height = renderTarget.height;

        // Get the buffer.
        long pixels = MemoryUtil.nmemAlloc((long) width * height * 4 * 2);
        RenderSystem.bindTexture(ScreenshotColorTransformRenderer.getDstTextureId());
        GlStateManager._pixelStore(GL30.GL_UNPACK_ALIGNMENT, 4);
        GlStateManager._getTexImage(3553, 0, GL30.GL_RGBA, GL30.GL_UNSIGNED_SHORT, pixels);
        ShortBuffer buffer = MemoryUtil.memShortBuffer(pixels, width * height * 4);
        consumer.accept(new ImageBuffer(buffer, width, height));
    }
    private static File getScreenshotFile(File baseDirectory) {
        if(!baseDirectory.exists()) {
            try{
                Files.createDirectories(baseDirectory.toPath());
            } catch (IOException e) {
                HDRMod.LOGGER.error("Error while creating screenshot directory {}", baseDirectory, e);
            }
        }
        String string = Util.getFilenameFormattedDateTime();
        int i = 1;
        while(true) {
            File screenshotFile = new File(baseDirectory, string + (i == 1 ? "" : "_" + i) + "_hdr" + ".png");
            if (!screenshotFile.exists()) {
                return screenshotFile;
            }
            ++i;
        }
    }
}

