// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

import java.lang.foreign.*;

/**
 * Constants of namespace Windows.Win32.Graphics.Direct3D11.
 */
public class Constants {
    /**
     * Numeric constant {@code D3D11_SDK_VERSION} (DWORD).
    */
    public static final int D3D11_SDK_VERSION = 7;

}
