// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

/**
 * {@code D3D11_USAGE} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code D3D11_USAGE} as it is the same as the enumeration name.
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ne-d3d11-d3d11_usage">D3D11_USAGE (Microsoft)</a>
 */
public class D3D11_USAGE {
    /**
     * Enumeration value {@code D3D11_USAGE_DEFAULT}
     */
    public static final int DEFAULT = 0;

    /**
     * Enumeration value {@code D3D11_USAGE_IMMUTABLE}
     */
    public static final int IMMUTABLE = 1;

    /**
     * Enumeration value {@code D3D11_USAGE_DYNAMIC}
     */
    public static final int DYNAMIC = 2;

    /**
     * Enumeration value {@code D3D11_USAGE_STAGING}
     */
    public static final int STAGING = 3;


    private D3D11_USAGE() {}
}
