// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

/**
 * {@code D3D11_BIND_FLAG} enumeration flags
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ne-d3d11-d3d11_bind_flag">D3D11_BIND_FLAG (Microsoft)</a>
 */
public class D3D11_BIND_FLAG {
    /**
     * Enumeration value {@code D3D11_BIND_VERTEX_BUFFER}
     */
    public static final int D3D11_BIND_VERTEX_BUFFER = 1;

    /**
     * Enumeration value {@code D3D11_BIND_INDEX_BUFFER}
     */
    public static final int D3D11_BIND_INDEX_BUFFER = 2;

    /**
     * Enumeration value {@code D3D11_BIND_CONSTANT_BUFFER}
     */
    public static final int D3D11_BIND_CONSTANT_BUFFER = 4;

    /**
     * Enumeration value {@code D3D11_BIND_SHADER_RESOURCE}
     */
    public static final int D3D11_BIND_SHADER_RESOURCE = 8;

    /**
     * Enumeration value {@code D3D11_BIND_STREAM_OUTPUT}
     */
    public static final int D3D11_BIND_STREAM_OUTPUT = 16;

    /**
     * Enumeration value {@code D3D11_BIND_RENDER_TARGET}
     */
    public static final int D3D11_BIND_RENDER_TARGET = 32;

    /**
     * Enumeration value {@code D3D11_BIND_DEPTH_STENCIL}
     */
    public static final int D3D11_BIND_DEPTH_STENCIL = 64;

    /**
     * Enumeration value {@code D3D11_BIND_UNORDERED_ACCESS}
     */
    public static final int D3D11_BIND_UNORDERED_ACCESS = 128;

    /**
     * Enumeration value {@code D3D11_BIND_DECODER}
     */
    public static final int D3D11_BIND_DECODER = 512;

    /**
     * Enumeration value {@code D3D11_BIND_VIDEO_ENCODER}
     */
    public static final int D3D11_BIND_VIDEO_ENCODER = 1024;


    private D3D11_BIND_FLAG() {}
}
