// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

/**
 * {@code D3D11_COUNTER_TYPE} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code D3D11_COUNTER_TYPE} as it is the same as the enumeration name.
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ne-d3d11-d3d11_counter_type">D3D11_COUNTER_TYPE (Microsoft)</a>
 */
public class D3D11_COUNTER_TYPE {
    /**
     * Enumeration value {@code D3D11_COUNTER_TYPE_FLOAT32}
     */
    public static final int FLOAT32 = 0;

    /**
     * Enumeration value {@code D3D11_COUNTER_TYPE_UINT16}
     */
    public static final int UINT16 = 1;

    /**
     * Enumeration value {@code D3D11_COUNTER_TYPE_UINT32}
     */
    public static final int UINT32 = 2;

    /**
     * Enumeration value {@code D3D11_COUNTER_TYPE_UINT64}
     */
    public static final int UINT64 = 3;


    private D3D11_COUNTER_TYPE() {}
}
