// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

/**
 * {@code D3D11_DEPTH_WRITE_MASK} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code D3D11_DEPTH_WRITE_MASK} as it is the same as the enumeration name.
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ne-d3d11-d3d11_depth_write_mask">D3D11_DEPTH_WRITE_MASK (Microsoft)</a>
 */
public class D3D11_DEPTH_WRITE_MASK {
    /**
     * Enumeration value {@code D3D11_DEPTH_WRITE_MASK_ZERO}
     */
    public static final int ZERO = 0;

    /**
     * Enumeration value {@code D3D11_DEPTH_WRITE_MASK_ALL}
     */
    public static final int ALL = 1;


    private D3D11_DEPTH_WRITE_MASK() {}
}
