// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

/**
 * {@code D3D11_FILL_MODE} enumeration
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ne-d3d11-d3d11_fill_mode">D3D11_FILL_MODE (Microsoft)</a>
 */
public class D3D11_FILL_MODE {
    /**
     * Enumeration value {@code D3D11_FILL_WIREFRAME}
     */
    public static final int D3D11_FILL_WIREFRAME = 2;

    /**
     * Enumeration value {@code D3D11_FILL_SOLID}
     */
    public static final int D3D11_FILL_SOLID = 3;


    private D3D11_FILL_MODE() {}
}
