// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

/**
 * {@code D3D11_STENCIL_OP} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code D3D11_STENCIL_OP} as it is the same as the enumeration name.
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ne-d3d11-d3d11_stencil_op">D3D11_STENCIL_OP (Microsoft)</a>
 */
public class D3D11_STENCIL_OP {
    /**
     * Enumeration value {@code D3D11_STENCIL_OP_KEEP}
     */
    public static final int KEEP = 1;

    /**
     * Enumeration value {@code D3D11_STENCIL_OP_ZERO}
     */
    public static final int ZERO = 2;

    /**
     * Enumeration value {@code D3D11_STENCIL_OP_REPLACE}
     */
    public static final int REPLACE = 3;

    /**
     * Enumeration value {@code D3D11_STENCIL_OP_INCR_SAT}
     */
    public static final int INCR_SAT = 4;

    /**
     * Enumeration value {@code D3D11_STENCIL_OP_DECR_SAT}
     */
    public static final int DECR_SAT = 5;

    /**
     * Enumeration value {@code D3D11_STENCIL_OP_INVERT}
     */
    public static final int INVERT = 6;

    /**
     * Enumeration value {@code D3D11_STENCIL_OP_INCR}
     */
    public static final int INCR = 7;

    /**
     * Enumeration value {@code D3D11_STENCIL_OP_DECR}
     */
    public static final int DECR = 8;


    private D3D11_STENCIL_OP() {}
}
