// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code D3D11_MAPPED_SUBRESOURCE} structure
 * <p>
 * {@snippet lang=c :
 * struct D3D11_MAPPED_SUBRESOURCE {
 *    void* pData;
 *    DWORD RowPitch;
 *    DWORD DepthPitch;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ns-d3d11-d3d11_mapped_subresource">D3D11_MAPPED_SUBRESOURCE (Microsoft)</a>
 */
public class D3D11_MAPPED_SUBRESOURCE {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withName("pData"),
        JAVA_INT.withName("RowPitch"),
        JAVA_INT.withName("DepthPitch")
    );

    /**
     * Gets the layout of the struct {@code D3D11_MAPPED_SUBRESOURCE}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code D3D11_MAPPED_SUBRESOURCE} (in bytes).
     */
    public static long sizeof() {
        return 16L;
    }

    /**
     * Gets the offset of the field {@code pData} (in bytes).
     */
    public static long pData$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code pData} in {@code segment}.
     */
    public static MemorySegment pData(MemorySegment segment) {
        return segment.get(ADDRESS, 0L);
    }

    /**
     * Sets the field {@code pData} in {@code segment} to {@code value}.
     */
    public static void pData(MemorySegment segment, MemorySegment value) {
        segment.set(ADDRESS, 0L, value);
    }

    /**
     * Gets the offset of the field {@code RowPitch} (in bytes).
     */
    public static long RowPitch$offset() {
        return 8L;
    }

    /**
     * Gets the value of field {@code RowPitch} in {@code segment}.
     */
    public static int RowPitch(MemorySegment segment) {
        return segment.get(JAVA_INT, 8L);
    }

    /**
     * Sets the field {@code RowPitch} in {@code segment} to {@code value}.
     */
    public static void RowPitch(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 8L, value);
    }

    /**
     * Gets the offset of the field {@code DepthPitch} (in bytes).
     */
    public static long DepthPitch$offset() {
        return 12L;
    }

    /**
     * Gets the value of field {@code DepthPitch} in {@code segment}.
     */
    public static int DepthPitch(MemorySegment segment) {
        return segment.get(JAVA_INT, 12L);
    }

    /**
     * Sets the field {@code DepthPitch} in {@code segment} to {@code value}.
     */
    public static void DepthPitch(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 12L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code D3D11_MAPPED_SUBRESOURCE}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(16L, 8L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code D3D11_MAPPED_SUBRESOURCE} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(16L * index, 16L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(16L * elementCount, 8L);
    }

    private D3D11_MAPPED_SUBRESOURCE () {}
}
