// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

/**
 * {@code D3D11_TEXTURE_ADDRESS_MODE} enumeration
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ne-d3d11-d3d11_texture_address_mode">D3D11_TEXTURE_ADDRESS_MODE (Microsoft)</a>
 */
public class D3D11_TEXTURE_ADDRESS_MODE {
    /**
     * Enumeration value {@code D3D11_TEXTURE_ADDRESS_WRAP}
     */
    public static final int D3D11_TEXTURE_ADDRESS_WRAP = 1;

    /**
     * Enumeration value {@code D3D11_TEXTURE_ADDRESS_MIRROR}
     */
    public static final int D3D11_TEXTURE_ADDRESS_MIRROR = 2;

    /**
     * Enumeration value {@code D3D11_TEXTURE_ADDRESS_CLAMP}
     */
    public static final int D3D11_TEXTURE_ADDRESS_CLAMP = 3;

    /**
     * Enumeration value {@code D3D11_TEXTURE_ADDRESS_BORDER}
     */
    public static final int D3D11_TEXTURE_ADDRESS_BORDER = 4;

    /**
     * Enumeration value {@code D3D11_TEXTURE_ADDRESS_MIRROR_ONCE}
     */
    public static final int D3D11_TEXTURE_ADDRESS_MIRROR_ONCE = 5;


    private D3D11_TEXTURE_ADDRESS_MODE() {}
}
