// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

import static java.lang.foreign.ValueLayout.JAVA_BYTE;
import static java.lang.foreign.ValueLayout.JAVA_INT;

/**
 * {@code D3D11_DEPTH_STENCIL_DESC} structure
 * <p>
 * {@snippet lang=c :
 * struct D3D11_DEPTH_STENCIL_DESC {
 *    BOOL DepthEnable;
 *    D3D11_DEPTH_WRITE_MASK DepthWriteMask;
 *    D3D11_COMPARISON_FUNC DepthFunc;
 *    BOOL StencilEnable;
 *    BYTE StencilReadMask;
 *    BYTE StencilWriteMask;
 *    D3D11_DEPTH_STENCILOP_DESC FrontFace;
 *    D3D11_DEPTH_STENCILOP_DESC BackFace;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ns-d3d11-d3d11_depth_stencil_desc">D3D11_DEPTH_STENCIL_DESC (Microsoft)</a>
 */
public class D3D11_DEPTH_STENCIL_DESC {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("DepthEnable"),
        JAVA_INT.withName("DepthWriteMask"),
        JAVA_INT.withName("DepthFunc"),
        JAVA_INT.withName("StencilEnable"),
        JAVA_BYTE.withName("StencilReadMask"),
        JAVA_BYTE.withName("StencilWriteMask"),
        MemoryLayout.paddingLayout(2),
        D3D11_DEPTH_STENCILOP_DESC.layout().withName("FrontFace"),
        D3D11_DEPTH_STENCILOP_DESC.layout().withName("BackFace")
    );

    /**
     * Gets the layout of the struct {@code D3D11_DEPTH_STENCIL_DESC}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code D3D11_DEPTH_STENCIL_DESC} (in bytes).
     */
    public static long sizeof() {
        return 52L;
    }

    /**
     * Gets the offset of the field {@code DepthEnable} (in bytes).
     */
    public static long DepthEnable$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code DepthEnable} in {@code segment}.
     */
    public static int DepthEnable(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code DepthEnable} in {@code segment} to {@code value}.
     */
    public static void DepthEnable(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code DepthWriteMask} (in bytes).
     */
    public static long DepthWriteMask$offset() {
        return 4L;
    }

    /**
     * Gets the value of field {@code DepthWriteMask} in {@code segment}.
     */
    public static int DepthWriteMask(MemorySegment segment) {
        return segment.get(JAVA_INT, 4L);
    }

    /**
     * Sets the field {@code DepthWriteMask} in {@code segment} to {@code value}.
     */
    public static void DepthWriteMask(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 4L, value);
    }

    /**
     * Gets the offset of the field {@code DepthFunc} (in bytes).
     */
    public static long DepthFunc$offset() {
        return 8L;
    }

    /**
     * Gets the value of field {@code DepthFunc} in {@code segment}.
     */
    public static int DepthFunc(MemorySegment segment) {
        return segment.get(JAVA_INT, 8L);
    }

    /**
     * Sets the field {@code DepthFunc} in {@code segment} to {@code value}.
     */
    public static void DepthFunc(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 8L, value);
    }

    /**
     * Gets the offset of the field {@code StencilEnable} (in bytes).
     */
    public static long StencilEnable$offset() {
        return 12L;
    }

    /**
     * Gets the value of field {@code StencilEnable} in {@code segment}.
     */
    public static int StencilEnable(MemorySegment segment) {
        return segment.get(JAVA_INT, 12L);
    }

    /**
     * Sets the field {@code StencilEnable} in {@code segment} to {@code value}.
     */
    public static void StencilEnable(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 12L, value);
    }

    /**
     * Gets the offset of the field {@code StencilReadMask} (in bytes).
     */
    public static long StencilReadMask$offset() {
        return 16L;
    }

    /**
     * Gets the value of field {@code StencilReadMask} in {@code segment}.
     */
    public static byte StencilReadMask(MemorySegment segment) {
        return segment.get(JAVA_BYTE, 16L);
    }

    /**
     * Sets the field {@code StencilReadMask} in {@code segment} to {@code value}.
     */
    public static void StencilReadMask(MemorySegment segment, byte value) {
        segment.set(JAVA_BYTE, 16L, value);
    }

    /**
     * Gets the offset of the field {@code StencilWriteMask} (in bytes).
     */
    public static long StencilWriteMask$offset() {
        return 17L;
    }

    /**
     * Gets the value of field {@code StencilWriteMask} in {@code segment}.
     */
    public static byte StencilWriteMask(MemorySegment segment) {
        return segment.get(JAVA_BYTE, 17L);
    }

    /**
     * Sets the field {@code StencilWriteMask} in {@code segment} to {@code value}.
     */
    public static void StencilWriteMask(MemorySegment segment, byte value) {
        segment.set(JAVA_BYTE, 17L, value);
    }

    /**
     * Gets the offset of the field {@code FrontFace} (in bytes).
     */
    public static long FrontFace$offset() {
        return 20L;
    }

    /**
     * Gets the field {@code FrontFace} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment FrontFace(MemorySegment segment) {
        return segment.asSlice(20L, 16L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code FrontFace} in {@code segment}.
     */
    public static void FrontFace(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 20L, 16L);
    }

    /**
     * Gets the offset of the field {@code BackFace} (in bytes).
     */
    public static long BackFace$offset() {
        return 36L;
    }

    /**
     * Gets the field {@code BackFace} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment BackFace(MemorySegment segment) {
        return segment.asSlice(36L, 16L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code BackFace} in {@code segment}.
     */
    public static void BackFace(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 36L, 16L);
    }

    /**
     * Allocates a new memory segment for the struct {@code D3D11_DEPTH_STENCIL_DESC}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(52L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code D3D11_DEPTH_STENCIL_DESC} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(52L * index, 52L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(52L * elementCount, 4L);
    }

    private D3D11_DEPTH_STENCIL_DESC () {}
}
