// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code D3D11_SAMPLER_DESC} structure
 * <p>
 * {@snippet lang=c :
 * struct D3D11_SAMPLER_DESC {
 *    D3D11_FILTER Filter;
 *    D3D11_TEXTURE_ADDRESS_MODE AddressU;
 *    D3D11_TEXTURE_ADDRESS_MODE AddressV;
 *    D3D11_TEXTURE_ADDRESS_MODE AddressW;
 *    FLOAT MipLODBias;
 *    DWORD MaxAnisotropy;
 *    D3D11_COMPARISON_FUNC ComparisonFunc;
 *    FLOAT[4] BorderColor;
 *    FLOAT MinLOD;
 *    FLOAT MaxLOD;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ns-d3d11-d3d11_sampler_desc">D3D11_SAMPLER_DESC (Microsoft)</a>
 */
public class D3D11_SAMPLER_DESC {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("Filter"),
        JAVA_INT.withName("AddressU"),
        JAVA_INT.withName("AddressV"),
        JAVA_INT.withName("AddressW"),
        JAVA_FLOAT.withName("MipLODBias"),
        JAVA_INT.withName("MaxAnisotropy"),
        JAVA_INT.withName("ComparisonFunc"),
        MemoryLayout.sequenceLayout(4L, JAVA_FLOAT).withName("BorderColor"),
        JAVA_FLOAT.withName("MinLOD"),
        JAVA_FLOAT.withName("MaxLOD")
    );

    /**
     * Gets the layout of the struct {@code D3D11_SAMPLER_DESC}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code D3D11_SAMPLER_DESC} (in bytes).
     */
    public static long sizeof() {
        return 52L;
    }

    /**
     * Gets the offset of the field {@code Filter} (in bytes).
     */
    public static long Filter$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code Filter} in {@code segment}.
     */
    public static int Filter(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code Filter} in {@code segment} to {@code value}.
     */
    public static void Filter(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code AddressU} (in bytes).
     */
    public static long AddressU$offset() {
        return 4L;
    }

    /**
     * Gets the value of field {@code AddressU} in {@code segment}.
     */
    public static int AddressU(MemorySegment segment) {
        return segment.get(JAVA_INT, 4L);
    }

    /**
     * Sets the field {@code AddressU} in {@code segment} to {@code value}.
     */
    public static void AddressU(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 4L, value);
    }

    /**
     * Gets the offset of the field {@code AddressV} (in bytes).
     */
    public static long AddressV$offset() {
        return 8L;
    }

    /**
     * Gets the value of field {@code AddressV} in {@code segment}.
     */
    public static int AddressV(MemorySegment segment) {
        return segment.get(JAVA_INT, 8L);
    }

    /**
     * Sets the field {@code AddressV} in {@code segment} to {@code value}.
     */
    public static void AddressV(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 8L, value);
    }

    /**
     * Gets the offset of the field {@code AddressW} (in bytes).
     */
    public static long AddressW$offset() {
        return 12L;
    }

    /**
     * Gets the value of field {@code AddressW} in {@code segment}.
     */
    public static int AddressW(MemorySegment segment) {
        return segment.get(JAVA_INT, 12L);
    }

    /**
     * Sets the field {@code AddressW} in {@code segment} to {@code value}.
     */
    public static void AddressW(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 12L, value);
    }

    /**
     * Gets the offset of the field {@code MipLODBias} (in bytes).
     */
    public static long MipLODBias$offset() {
        return 16L;
    }

    /**
     * Gets the value of field {@code MipLODBias} in {@code segment}.
     */
    public static float MipLODBias(MemorySegment segment) {
        return segment.get(JAVA_FLOAT, 16L);
    }

    /**
     * Sets the field {@code MipLODBias} in {@code segment} to {@code value}.
     */
    public static void MipLODBias(MemorySegment segment, float value) {
        segment.set(JAVA_FLOAT, 16L, value);
    }

    /**
     * Gets the offset of the field {@code MaxAnisotropy} (in bytes).
     */
    public static long MaxAnisotropy$offset() {
        return 20L;
    }

    /**
     * Gets the value of field {@code MaxAnisotropy} in {@code segment}.
     */
    public static int MaxAnisotropy(MemorySegment segment) {
        return segment.get(JAVA_INT, 20L);
    }

    /**
     * Sets the field {@code MaxAnisotropy} in {@code segment} to {@code value}.
     */
    public static void MaxAnisotropy(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 20L, value);
    }

    /**
     * Gets the offset of the field {@code ComparisonFunc} (in bytes).
     */
    public static long ComparisonFunc$offset() {
        return 24L;
    }

    /**
     * Gets the value of field {@code ComparisonFunc} in {@code segment}.
     */
    public static int ComparisonFunc(MemorySegment segment) {
        return segment.get(JAVA_INT, 24L);
    }

    /**
     * Sets the field {@code ComparisonFunc} in {@code segment} to {@code value}.
     */
    public static void ComparisonFunc(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 24L, value);
    }

    /**
     * Gets the offset of the field {@code BorderColor} (in bytes).
     */
    public static long BorderColor$offset() {
        return 28L;
    }

    /**
     * Gets the field {@code BorderColor} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment BorderColor(MemorySegment segment) {
        return segment.asSlice(28L, 16L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code BorderColor} in {@code segment}.
     */
    public static void BorderColor(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 28L, 16L);
    }

    /**
     * Gets the offset of the field {@code MinLOD} (in bytes).
     */
    public static long MinLOD$offset() {
        return 44L;
    }

    /**
     * Gets the value of field {@code MinLOD} in {@code segment}.
     */
    public static float MinLOD(MemorySegment segment) {
        return segment.get(JAVA_FLOAT, 44L);
    }

    /**
     * Sets the field {@code MinLOD} in {@code segment} to {@code value}.
     */
    public static void MinLOD(MemorySegment segment, float value) {
        segment.set(JAVA_FLOAT, 44L, value);
    }

    /**
     * Gets the offset of the field {@code MaxLOD} (in bytes).
     */
    public static long MaxLOD$offset() {
        return 48L;
    }

    /**
     * Gets the value of field {@code MaxLOD} in {@code segment}.
     */
    public static float MaxLOD(MemorySegment segment) {
        return segment.get(JAVA_FLOAT, 48L);
    }

    /**
     * Sets the field {@code MaxLOD} in {@code segment} to {@code value}.
     */
    public static void MaxLOD(MemorySegment segment, float value) {
        segment.set(JAVA_FLOAT, 48L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code D3D11_SAMPLER_DESC}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(52L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code D3D11_SAMPLER_DESC} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(52L * index, 52L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(52L * elementCount, 4L);
    }

    private D3D11_SAMPLER_DESC () {}
}
