// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

/**
 * {@code D3D11_BLEND} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code D3D11_BLEND} as it is the same as the enumeration name.
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ne-d3d11-d3d11_blend">D3D11_BLEND (Microsoft)</a>
 */
public class D3D11_BLEND {
    /**
     * Enumeration value {@code D3D11_BLEND_ZERO}
     */
    public static final int ZERO = 1;

    /**
     * Enumeration value {@code D3D11_BLEND_ONE}
     */
    public static final int ONE = 2;

    /**
     * Enumeration value {@code D3D11_BLEND_SRC_COLOR}
     */
    public static final int SRC_COLOR = 3;

    /**
     * Enumeration value {@code D3D11_BLEND_INV_SRC_COLOR}
     */
    public static final int INV_SRC_COLOR = 4;

    /**
     * Enumeration value {@code D3D11_BLEND_SRC_ALPHA}
     */
    public static final int SRC_ALPHA = 5;

    /**
     * Enumeration value {@code D3D11_BLEND_INV_SRC_ALPHA}
     */
    public static final int INV_SRC_ALPHA = 6;

    /**
     * Enumeration value {@code D3D11_BLEND_DEST_ALPHA}
     */
    public static final int DEST_ALPHA = 7;

    /**
     * Enumeration value {@code D3D11_BLEND_INV_DEST_ALPHA}
     */
    public static final int INV_DEST_ALPHA = 8;

    /**
     * Enumeration value {@code D3D11_BLEND_DEST_COLOR}
     */
    public static final int DEST_COLOR = 9;

    /**
     * Enumeration value {@code D3D11_BLEND_INV_DEST_COLOR}
     */
    public static final int INV_DEST_COLOR = 10;

    /**
     * Enumeration value {@code D3D11_BLEND_SRC_ALPHA_SAT}
     */
    public static final int SRC_ALPHA_SAT = 11;

    /**
     * Enumeration value {@code D3D11_BLEND_BLEND_FACTOR}
     */
    public static final int BLEND_FACTOR = 14;

    /**
     * Enumeration value {@code D3D11_BLEND_INV_BLEND_FACTOR}
     */
    public static final int INV_BLEND_FACTOR = 15;

    /**
     * Enumeration value {@code D3D11_BLEND_SRC1_COLOR}
     */
    public static final int SRC1_COLOR = 16;

    /**
     * Enumeration value {@code D3D11_BLEND_INV_SRC1_COLOR}
     */
    public static final int INV_SRC1_COLOR = 17;

    /**
     * Enumeration value {@code D3D11_BLEND_SRC1_ALPHA}
     */
    public static final int SRC1_ALPHA = 18;

    /**
     * Enumeration value {@code D3D11_BLEND_INV_SRC1_ALPHA}
     */
    public static final int INV_SRC1_ALPHA = 19;


    private D3D11_BLEND() {}
}
