// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

import static java.lang.foreign.ValueLayout.JAVA_FLOAT;
import static java.lang.foreign.ValueLayout.JAVA_INT;

/**
 * {@code D3D11_RASTERIZER_DESC} structure
 * <p>
 * {@snippet lang=c :
 * struct D3D11_RASTERIZER_DESC {
 *    D3D11_FILL_MODE FillMode;
 *    D3D11_CULL_MODE CullMode;
 *    BOOL FrontCounterClockwise;
 *    LONG DepthBias;
 *    FLOAT DepthBiasClamp;
 *    FLOAT SlopeScaledDepthBias;
 *    BOOL DepthClipEnable;
 *    BOOL ScissorEnable;
 *    BOOL MultisampleEnable;
 *    BOOL AntialiasedLineEnable;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ns-d3d11-d3d11_rasterizer_desc">D3D11_RASTERIZER_DESC (Microsoft)</a>
 */
public class D3D11_RASTERIZER_DESC {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("FillMode"),
        JAVA_INT.withName("CullMode"),
        JAVA_INT.withName("FrontCounterClockwise"),
        JAVA_INT.withName("DepthBias"),
        JAVA_FLOAT.withName("DepthBiasClamp"),
        JAVA_FLOAT.withName("SlopeScaledDepthBias"),
        JAVA_INT.withName("DepthClipEnable"),
        JAVA_INT.withName("ScissorEnable"),
        JAVA_INT.withName("MultisampleEnable"),
        JAVA_INT.withName("AntialiasedLineEnable")
    );

    /**
     * Gets the layout of the struct {@code D3D11_RASTERIZER_DESC}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code D3D11_RASTERIZER_DESC} (in bytes).
     */
    public static long sizeof() {
        return 40L;
    }

    /**
     * Gets the offset of the field {@code FillMode} (in bytes).
     */
    public static long FillMode$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code FillMode} in {@code segment}.
     */
    public static int FillMode(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code FillMode} in {@code segment} to {@code value}.
     */
    public static void FillMode(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code CullMode} (in bytes).
     */
    public static long CullMode$offset() {
        return 4L;
    }

    /**
     * Gets the value of field {@code CullMode} in {@code segment}.
     */
    public static int CullMode(MemorySegment segment) {
        return segment.get(JAVA_INT, 4L);
    }

    /**
     * Sets the field {@code CullMode} in {@code segment} to {@code value}.
     */
    public static void CullMode(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 4L, value);
    }

    /**
     * Gets the offset of the field {@code FrontCounterClockwise} (in bytes).
     */
    public static long FrontCounterClockwise$offset() {
        return 8L;
    }

    /**
     * Gets the value of field {@code FrontCounterClockwise} in {@code segment}.
     */
    public static int FrontCounterClockwise(MemorySegment segment) {
        return segment.get(JAVA_INT, 8L);
    }

    /**
     * Sets the field {@code FrontCounterClockwise} in {@code segment} to {@code value}.
     */
    public static void FrontCounterClockwise(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 8L, value);
    }

    /**
     * Gets the offset of the field {@code DepthBias} (in bytes).
     */
    public static long DepthBias$offset() {
        return 12L;
    }

    /**
     * Gets the value of field {@code DepthBias} in {@code segment}.
     */
    public static int DepthBias(MemorySegment segment) {
        return segment.get(JAVA_INT, 12L);
    }

    /**
     * Sets the field {@code DepthBias} in {@code segment} to {@code value}.
     */
    public static void DepthBias(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 12L, value);
    }

    /**
     * Gets the offset of the field {@code DepthBiasClamp} (in bytes).
     */
    public static long DepthBiasClamp$offset() {
        return 16L;
    }

    /**
     * Gets the value of field {@code DepthBiasClamp} in {@code segment}.
     */
    public static float DepthBiasClamp(MemorySegment segment) {
        return segment.get(JAVA_FLOAT, 16L);
    }

    /**
     * Sets the field {@code DepthBiasClamp} in {@code segment} to {@code value}.
     */
    public static void DepthBiasClamp(MemorySegment segment, float value) {
        segment.set(JAVA_FLOAT, 16L, value);
    }

    /**
     * Gets the offset of the field {@code SlopeScaledDepthBias} (in bytes).
     */
    public static long SlopeScaledDepthBias$offset() {
        return 20L;
    }

    /**
     * Gets the value of field {@code SlopeScaledDepthBias} in {@code segment}.
     */
    public static float SlopeScaledDepthBias(MemorySegment segment) {
        return segment.get(JAVA_FLOAT, 20L);
    }

    /**
     * Sets the field {@code SlopeScaledDepthBias} in {@code segment} to {@code value}.
     */
    public static void SlopeScaledDepthBias(MemorySegment segment, float value) {
        segment.set(JAVA_FLOAT, 20L, value);
    }

    /**
     * Gets the offset of the field {@code DepthClipEnable} (in bytes).
     */
    public static long DepthClipEnable$offset() {
        return 24L;
    }

    /**
     * Gets the value of field {@code DepthClipEnable} in {@code segment}.
     */
    public static int DepthClipEnable(MemorySegment segment) {
        return segment.get(JAVA_INT, 24L);
    }

    /**
     * Sets the field {@code DepthClipEnable} in {@code segment} to {@code value}.
     */
    public static void DepthClipEnable(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 24L, value);
    }

    /**
     * Gets the offset of the field {@code ScissorEnable} (in bytes).
     */
    public static long ScissorEnable$offset() {
        return 28L;
    }

    /**
     * Gets the value of field {@code ScissorEnable} in {@code segment}.
     */
    public static int ScissorEnable(MemorySegment segment) {
        return segment.get(JAVA_INT, 28L);
    }

    /**
     * Sets the field {@code ScissorEnable} in {@code segment} to {@code value}.
     */
    public static void ScissorEnable(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 28L, value);
    }

    /**
     * Gets the offset of the field {@code MultisampleEnable} (in bytes).
     */
    public static long MultisampleEnable$offset() {
        return 32L;
    }

    /**
     * Gets the value of field {@code MultisampleEnable} in {@code segment}.
     */
    public static int MultisampleEnable(MemorySegment segment) {
        return segment.get(JAVA_INT, 32L);
    }

    /**
     * Sets the field {@code MultisampleEnable} in {@code segment} to {@code value}.
     */
    public static void MultisampleEnable(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 32L, value);
    }

    /**
     * Gets the offset of the field {@code AntialiasedLineEnable} (in bytes).
     */
    public static long AntialiasedLineEnable$offset() {
        return 36L;
    }

    /**
     * Gets the value of field {@code AntialiasedLineEnable} in {@code segment}.
     */
    public static int AntialiasedLineEnable(MemorySegment segment) {
        return segment.get(JAVA_INT, 36L);
    }

    /**
     * Sets the field {@code AntialiasedLineEnable} in {@code segment} to {@code value}.
     */
    public static void AntialiasedLineEnable(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 36L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code D3D11_RASTERIZER_DESC}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(40L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code D3D11_RASTERIZER_DESC} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(40L * index, 40L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(40L * elementCount, 4L);
    }

    private D3D11_RASTERIZER_DESC () {}
}
