// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code D3D11_RENDER_TARGET_BLEND_DESC} structure
 * <p>
 * {@snippet lang=c :
 * struct D3D11_RENDER_TARGET_BLEND_DESC {
 *    BOOL BlendEnable;
 *    D3D11_BLEND SrcBlend;
 *    D3D11_BLEND DestBlend;
 *    D3D11_BLEND_OP BlendOp;
 *    D3D11_BLEND SrcBlendAlpha;
 *    D3D11_BLEND DestBlendAlpha;
 *    D3D11_BLEND_OP BlendOpAlpha;
 *    BYTE RenderTargetWriteMask;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ns-d3d11-d3d11_render_target_blend_desc">D3D11_RENDER_TARGET_BLEND_DESC (Microsoft)</a>
 */
public class D3D11_RENDER_TARGET_BLEND_DESC {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("BlendEnable"),
        JAVA_INT.withName("SrcBlend"),
        JAVA_INT.withName("DestBlend"),
        JAVA_INT.withName("BlendOp"),
        JAVA_INT.withName("SrcBlendAlpha"),
        JAVA_INT.withName("DestBlendAlpha"),
        JAVA_INT.withName("BlendOpAlpha"),
        JAVA_BYTE.withName("RenderTargetWriteMask"),
        MemoryLayout.paddingLayout(3)
    );

    /**
     * Gets the layout of the struct {@code D3D11_RENDER_TARGET_BLEND_DESC}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code D3D11_RENDER_TARGET_BLEND_DESC} (in bytes).
     */
    public static long sizeof() {
        return 32L;
    }

    /**
     * Gets the offset of the field {@code BlendEnable} (in bytes).
     */
    public static long BlendEnable$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code BlendEnable} in {@code segment}.
     */
    public static int BlendEnable(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code BlendEnable} in {@code segment} to {@code value}.
     */
    public static void BlendEnable(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code SrcBlend} (in bytes).
     */
    public static long SrcBlend$offset() {
        return 4L;
    }

    /**
     * Gets the value of field {@code SrcBlend} in {@code segment}.
     */
    public static int SrcBlend(MemorySegment segment) {
        return segment.get(JAVA_INT, 4L);
    }

    /**
     * Sets the field {@code SrcBlend} in {@code segment} to {@code value}.
     */
    public static void SrcBlend(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 4L, value);
    }

    /**
     * Gets the offset of the field {@code DestBlend} (in bytes).
     */
    public static long DestBlend$offset() {
        return 8L;
    }

    /**
     * Gets the value of field {@code DestBlend} in {@code segment}.
     */
    public static int DestBlend(MemorySegment segment) {
        return segment.get(JAVA_INT, 8L);
    }

    /**
     * Sets the field {@code DestBlend} in {@code segment} to {@code value}.
     */
    public static void DestBlend(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 8L, value);
    }

    /**
     * Gets the offset of the field {@code BlendOp} (in bytes).
     */
    public static long BlendOp$offset() {
        return 12L;
    }

    /**
     * Gets the value of field {@code BlendOp} in {@code segment}.
     */
    public static int BlendOp(MemorySegment segment) {
        return segment.get(JAVA_INT, 12L);
    }

    /**
     * Sets the field {@code BlendOp} in {@code segment} to {@code value}.
     */
    public static void BlendOp(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 12L, value);
    }

    /**
     * Gets the offset of the field {@code SrcBlendAlpha} (in bytes).
     */
    public static long SrcBlendAlpha$offset() {
        return 16L;
    }

    /**
     * Gets the value of field {@code SrcBlendAlpha} in {@code segment}.
     */
    public static int SrcBlendAlpha(MemorySegment segment) {
        return segment.get(JAVA_INT, 16L);
    }

    /**
     * Sets the field {@code SrcBlendAlpha} in {@code segment} to {@code value}.
     */
    public static void SrcBlendAlpha(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 16L, value);
    }

    /**
     * Gets the offset of the field {@code DestBlendAlpha} (in bytes).
     */
    public static long DestBlendAlpha$offset() {
        return 20L;
    }

    /**
     * Gets the value of field {@code DestBlendAlpha} in {@code segment}.
     */
    public static int DestBlendAlpha(MemorySegment segment) {
        return segment.get(JAVA_INT, 20L);
    }

    /**
     * Sets the field {@code DestBlendAlpha} in {@code segment} to {@code value}.
     */
    public static void DestBlendAlpha(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 20L, value);
    }

    /**
     * Gets the offset of the field {@code BlendOpAlpha} (in bytes).
     */
    public static long BlendOpAlpha$offset() {
        return 24L;
    }

    /**
     * Gets the value of field {@code BlendOpAlpha} in {@code segment}.
     */
    public static int BlendOpAlpha(MemorySegment segment) {
        return segment.get(JAVA_INT, 24L);
    }

    /**
     * Sets the field {@code BlendOpAlpha} in {@code segment} to {@code value}.
     */
    public static void BlendOpAlpha(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 24L, value);
    }

    /**
     * Gets the offset of the field {@code RenderTargetWriteMask} (in bytes).
     */
    public static long RenderTargetWriteMask$offset() {
        return 28L;
    }

    /**
     * Gets the value of field {@code RenderTargetWriteMask} in {@code segment}.
     */
    public static byte RenderTargetWriteMask(MemorySegment segment) {
        return segment.get(JAVA_BYTE, 28L);
    }

    /**
     * Sets the field {@code RenderTargetWriteMask} in {@code segment} to {@code value}.
     */
    public static void RenderTargetWriteMask(MemorySegment segment, byte value) {
        segment.set(JAVA_BYTE, 28L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code D3D11_RENDER_TARGET_BLEND_DESC}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(32L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code D3D11_RENDER_TARGET_BLEND_DESC} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(32L * index, 32L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(32L * elementCount, 4L);
    }

    private D3D11_RENDER_TARGET_BLEND_DESC () {}
}
