// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

/**
 * {@code D3D11_COMPARISON_FUNC} enumeration
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/ne-d3d11-d3d11_comparison_func">D3D11_COMPARISON_FUNC (Microsoft)</a>
 */
public class D3D11_COMPARISON_FUNC {
    /**
     * Enumeration value {@code D3D11_COMPARISON_NEVER}
     */
    public static final int D3D11_COMPARISON_NEVER = 1;

    /**
     * Enumeration value {@code D3D11_COMPARISON_LESS}
     */
    public static final int D3D11_COMPARISON_LESS = 2;

    /**
     * Enumeration value {@code D3D11_COMPARISON_EQUAL}
     */
    public static final int D3D11_COMPARISON_EQUAL = 3;

    /**
     * Enumeration value {@code D3D11_COMPARISON_LESS_EQUAL}
     */
    public static final int D3D11_COMPARISON_LESS_EQUAL = 4;

    /**
     * Enumeration value {@code D3D11_COMPARISON_GREATER}
     */
    public static final int D3D11_COMPARISON_GREATER = 5;

    /**
     * Enumeration value {@code D3D11_COMPARISON_NOT_EQUAL}
     */
    public static final int D3D11_COMPARISON_NOT_EQUAL = 6;

    /**
     * Enumeration value {@code D3D11_COMPARISON_GREATER_EQUAL}
     */
    public static final int D3D11_COMPARISON_GREATER_EQUAL = 7;

    /**
     * Enumeration value {@code D3D11_COMPARISON_ALWAYS}
     */
    public static final int D3D11_COMPARISON_ALWAYS = 8;


    private D3D11_COMPARISON_FUNC() {}
}
