// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

import java.lang.foreign.*;
import java.lang.invoke.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code ID3D11ClassInstance} COM interface
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/nn-d3d11-id3d11classinstance">ID3D11ClassInstance (Microsoft)</a>
 */
public interface ID3D11ClassInstance extends ID3D11DeviceChild {
    /**
     * {@code GetClassLinkage} COM interface method
     * <p>
     * {@snippet lang=c :
     * void GetClassLinkage(
     *     ID3D11ClassLinkage* ppLinkage
     * );
     * }
     * </p>
     */
    void GetClassLinkage(MemorySegment ppLinkage);

    /**
     * {@code GetDesc} COM interface method
     * <p>
     * {@snippet lang=c :
     * void GetDesc(
     *     D3D11_CLASS_INSTANCE_DESC* pDesc
     * );
     * }
     * </p>
     */
    void GetDesc(MemorySegment pDesc);

    /**
     * {@code GetInstanceName} COM interface method
     * <p>
     * {@snippet lang=c :
     * void GetInstanceName(
     *     PSTR pInstanceName,
     *     ULONG_PTR* pBufferLength
     * );
     * }
     * </p>
     */
    void GetInstanceName(MemorySegment pInstanceName, MemorySegment pBufferLength);

    /**
     * {@code GetTypeName} COM interface method
     * <p>
     * {@snippet lang=c :
     * void GetTypeName(
     *     PSTR pTypeName,
     *     ULONG_PTR* pBufferLength
     * );
     * }
     * </p>
     */
    void GetTypeName(MemorySegment pTypeName, MemorySegment pBufferLength);

    /**
     * Wraps the given COM object in a Java object with methods to call the COM interface functions.
     */
    static ID3D11ClassInstance wrap(MemorySegment comObject) {
        return new $DOWNCALL(comObject.reinterpret(8L));
    }

    /**
     * Gets the address layout for pointers to {@code ID3D11ClassInstance} COM interfaces.
     */
    static AddressLayout addressLayout() {
        return ID3D11ClassInstance$ADDRESS_LAYOUT;
    }

    /**
     * Interface identifier (IID) for {@code ID3D11ClassInstance} ({@code {a6cd7faa-b0b7-4a2f-9436-8662a65797cb}}).
     */
    static MemorySegment iid() {
        return $IID$ID3D11ClassInstance.IID$SEG;
    }

    /**
     * Creates a COM object instance for the given Java object implementing {@code ID3D11ClassInstance}.
     */
    static MemorySegment create(ID3D11ClassInstance obj, Arena arena) {
        var unwrapper = new $UPCALL(obj);
        var vtable = arena.allocate(ADDRESS, 11);
        var linker = Linker.nativeLinker();
        for (int i = 0; i < 11; i++)
            vtable.set(ADDRESS, 8 * i, linker.upcallStub($UPCALL_IMPL.HANDLES[i].bindTo(unwrapper), $UPCALL_IMPL.DESCRIPTORS[i], arena));
        var objSegment = arena.allocate(ADDRESS);
        objSegment.set(ADDRESS, 0, vtable);
        return objSegment;
    }

    StructLayout ID3D11ClassInstance$COM_OBJECT_LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(11, ADDRESS)).withName("vtable")
    );

    AddressLayout ID3D11ClassInstance$ADDRESS_LAYOUT = ADDRESS.withTargetLayout(ID3D11ClassInstance$COM_OBJECT_LAYOUT);

    AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));
    AddressLayout ADDRESS$STRUCT_16_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_32_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(32, JAVA_BYTE).withByteAlignment(4));

    class $IID$ID3D11ClassInstance {
        private static final Arena ARENA = Arena.ofAuto();

        private static MemorySegment createGuid(long v1, long v2) {
            var seg = ARENA.allocate(16, 8);
            seg.set(ValueLayout.JAVA_LONG, 0, v1);
            seg.set(ValueLayout.JAVA_LONG, 8, v2);
            return seg;
        }

        private static final MemorySegment IID$SEG = createGuid(5345685585536057258L, -3776453390397720940L);

    }

    class $DOWNCALL extends ID3D11DeviceChild.$DOWNCALL implements ID3D11ClassInstance {
        private static final VarHandle VTABLE_FUNC_VARHANDLE = ID3D11ClassInstance$COM_OBJECT_LAYOUT.varHandle(
                PathElement.groupElement("vtable"),
                PathElement.dereferenceElement(),
                PathElement.sequenceElement()
        );

        private static MemorySegment vtableFunc(MemorySegment comObject, long index) {
            return (MemorySegment) VTABLE_FUNC_VARHANDLE.get(comObject, 0L, index);
        }

        protected $DOWNCALL(MemorySegment comObject) {
            super(comObject);
        }

        public void GetClassLinkage(MemorySegment ppLinkage) {
            try {
                VFUNC7$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 7), comObject, ppLinkage);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public void GetDesc(MemorySegment pDesc) {
            try {
                VFUNC8$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 8), comObject, pDesc);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public void GetInstanceName(MemorySegment pInstanceName, MemorySegment pBufferLength) {
            try {
                VFUNC9$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 9), comObject, pInstanceName, pBufferLength);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public void GetTypeName(MemorySegment pTypeName, MemorySegment pBufferLength) {
            try {
                VFUNC10$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 10), comObject, pTypeName, pBufferLength);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

    }

    class VFUNC7$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(ID3D11ClassInstance$ADDRESS_LAYOUT, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC8$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(ID3D11ClassInstance$ADDRESS_LAYOUT, ADDRESS$STRUCT_32_4);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC9$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(ID3D11ClassInstance$ADDRESS_LAYOUT, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC10$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(ID3D11ClassInstance$ADDRESS_LAYOUT, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class $UPCALL {
        private final ID3D11ClassInstance javaObject;

        private $UPCALL(ID3D11ClassInstance javaObject) {
            this.javaObject = javaObject;
        }

        int QueryInterface(MemorySegment thisObject, MemorySegment riid, MemorySegment ppvObject) {
            return javaObject.QueryInterface(riid, ppvObject);
        }
        int AddRef(MemorySegment thisObject) {
            return javaObject.AddRef();
        }
        int Release(MemorySegment thisObject) {
            return javaObject.Release();
        }
        void GetDevice(MemorySegment thisObject, MemorySegment ppDevice) {
            javaObject.GetDevice(ppDevice);
        }
        int GetPrivateData(MemorySegment thisObject, MemorySegment guid, MemorySegment pDataSize, MemorySegment pData) {
            return javaObject.GetPrivateData(guid, pDataSize, pData);
        }
        int SetPrivateData(MemorySegment thisObject, MemorySegment guid, int DataSize, MemorySegment pData) {
            return javaObject.SetPrivateData(guid, DataSize, pData);
        }
        int SetPrivateDataInterface(MemorySegment thisObject, MemorySegment guid, MemorySegment pData) {
            return javaObject.SetPrivateDataInterface(guid, pData);
        }
        void GetClassLinkage(MemorySegment thisObject, MemorySegment ppLinkage) {
            javaObject.GetClassLinkage(ppLinkage);
        }
        void GetDesc(MemorySegment thisObject, MemorySegment pDesc) {
            javaObject.GetDesc(pDesc);
        }
        void GetInstanceName(MemorySegment thisObject, MemorySegment pInstanceName, MemorySegment pBufferLength) {
            javaObject.GetInstanceName(pInstanceName, pBufferLength);
        }
        void GetTypeName(MemorySegment thisObject, MemorySegment pTypeName, MemorySegment pBufferLength) {
            javaObject.GetTypeName(pTypeName, pBufferLength);
        }
    }

    class $UPCALL_IMPL {
        private static final FunctionDescriptor[] DESCRIPTORS = createDescriptors();
        private static final MethodHandle[] HANDLES = createHandles();

        private static FunctionDescriptor[] createDescriptors() {
            var descriptors = new FunctionDescriptor[11];
            descriptors[0] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[1] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[2] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[3] = FunctionDescriptor.ofVoid(ADDRESS, ADDRESS$ADDRESS);
            descriptors[4] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
            descriptors[5] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
            descriptors[6] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[7] = FunctionDescriptor.ofVoid(ADDRESS, ADDRESS$ADDRESS);
            descriptors[8] = FunctionDescriptor.ofVoid(ADDRESS, ADDRESS$STRUCT_32_4);
            descriptors[9] = FunctionDescriptor.ofVoid(ADDRESS, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE);
            descriptors[10] = FunctionDescriptor.ofVoid(ADDRESS, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE);
            return descriptors;
        }

        private static MethodHandle[] createHandles() {
            try {
                var lookup = MethodHandles.lookup();
                var handles = new MethodHandle[11];
                handles[0] = lookup.findVirtual($UPCALL.class, "QueryInterface", DESCRIPTORS[0].toMethodType());
                handles[1] = lookup.findVirtual($UPCALL.class, "AddRef", DESCRIPTORS[1].toMethodType());
                handles[2] = lookup.findVirtual($UPCALL.class, "Release", DESCRIPTORS[2].toMethodType());
                handles[3] = lookup.findVirtual($UPCALL.class, "GetDevice", DESCRIPTORS[3].toMethodType());
                handles[4] = lookup.findVirtual($UPCALL.class, "GetPrivateData", DESCRIPTORS[4].toMethodType());
                handles[5] = lookup.findVirtual($UPCALL.class, "SetPrivateData", DESCRIPTORS[5].toMethodType());
                handles[6] = lookup.findVirtual($UPCALL.class, "SetPrivateDataInterface", DESCRIPTORS[6].toMethodType());
                handles[7] = lookup.findVirtual($UPCALL.class, "GetClassLinkage", DESCRIPTORS[7].toMethodType());
                handles[8] = lookup.findVirtual($UPCALL.class, "GetDesc", DESCRIPTORS[8].toMethodType());
                handles[9] = lookup.findVirtual($UPCALL.class, "GetInstanceName", DESCRIPTORS[9].toMethodType());
                handles[10] = lookup.findVirtual($UPCALL.class, "GetTypeName", DESCRIPTORS[10].toMethodType());
               return handles;
           } catch (ReflectiveOperationException e) {
               throw new RuntimeException(e);
           }
       }
   }
}
