// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

import java.lang.foreign.*;
import java.lang.invoke.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code ID3D11DeviceChild} COM interface
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/nn-d3d11-id3d11devicechild">ID3D11DeviceChild (Microsoft)</a>
 */
public interface ID3D11DeviceChild extends windows.win32.system.com.IUnknown {
    /**
     * {@code GetDevice} COM interface method
     * <p>
     * {@snippet lang=c :
     * void GetDevice(
     *     ID3D11Device* ppDevice
     * );
     * }
     * </p>
     */
    void GetDevice(MemorySegment ppDevice);

    /**
     * {@code GetPrivateData} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetPrivateData(
     *     GUID* guid,
     *     DWORD* pDataSize,
     *     void* pData
     * );
     * }
     * </p>
     */
    int GetPrivateData(MemorySegment guid, MemorySegment pDataSize, MemorySegment pData);

    /**
     * {@code SetPrivateData} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT SetPrivateData(
     *     GUID* guid,
     *     DWORD DataSize,
     *     void* pData
     * );
     * }
     * </p>
     */
    int SetPrivateData(MemorySegment guid, int DataSize, MemorySegment pData);

    /**
     * {@code SetPrivateDataInterface} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT SetPrivateDataInterface(
     *     GUID* guid,
     *     IUnknown pData
     * );
     * }
     * </p>
     */
    int SetPrivateDataInterface(MemorySegment guid, MemorySegment pData);

    /**
     * Wraps the given COM object in a Java object with methods to call the COM interface functions.
     */
    static ID3D11DeviceChild wrap(MemorySegment comObject) {
        return new $DOWNCALL(comObject.reinterpret(8L));
    }

    /**
     * Gets the address layout for pointers to {@code ID3D11DeviceChild} COM interfaces.
     */
    static AddressLayout addressLayout() {
        return ID3D11DeviceChild$ADDRESS_LAYOUT;
    }

    /**
     * Interface identifier (IID) for {@code ID3D11DeviceChild} ({@code {1841e5c8-16b0-489b-bcc8-44cfb0d5deae}}).
     */
    static MemorySegment iid() {
        return $IID$ID3D11DeviceChild.IID$SEG;
    }

    /**
     * Creates a COM object instance for the given Java object implementing {@code ID3D11DeviceChild}.
     */
    static MemorySegment create(ID3D11DeviceChild obj, Arena arena) {
        var unwrapper = new $UPCALL(obj);
        var vtable = arena.allocate(ADDRESS, 7);
        var linker = Linker.nativeLinker();
        for (int i = 0; i < 7; i++)
            vtable.set(ADDRESS, 8 * i, linker.upcallStub($UPCALL_IMPL.HANDLES[i].bindTo(unwrapper), $UPCALL_IMPL.DESCRIPTORS[i], arena));
        var objSegment = arena.allocate(ADDRESS);
        objSegment.set(ADDRESS, 0, vtable);
        return objSegment;
    }

    StructLayout ID3D11DeviceChild$COM_OBJECT_LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(7, ADDRESS)).withName("vtable")
    );

    AddressLayout ID3D11DeviceChild$ADDRESS_LAYOUT = ADDRESS.withTargetLayout(ID3D11DeviceChild$COM_OBJECT_LAYOUT);

    AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));
    AddressLayout ADDRESS$STRUCT_16_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(4));

    class $IID$ID3D11DeviceChild {
        private static final Arena ARENA = Arena.ofAuto();

        private static MemorySegment createGuid(long v1, long v2) {
            var seg = ARENA.allocate(16, 8);
            seg.set(ValueLayout.JAVA_LONG, 0, v1);
            seg.set(ValueLayout.JAVA_LONG, 8, v2);
            return seg;
        }

        private static final MemorySegment IID$SEG = createGuid(5231800337697990088L, -5846000310911973188L);

    }

    class $DOWNCALL extends windows.win32.system.com.IUnknown.$DOWNCALL implements ID3D11DeviceChild {
        private static final VarHandle VTABLE_FUNC_VARHANDLE = ID3D11DeviceChild$COM_OBJECT_LAYOUT.varHandle(
                PathElement.groupElement("vtable"),
                PathElement.dereferenceElement(),
                PathElement.sequenceElement()
        );

        private static MemorySegment vtableFunc(MemorySegment comObject, long index) {
            return (MemorySegment) VTABLE_FUNC_VARHANDLE.get(comObject, 0L, index);
        }

        protected $DOWNCALL(MemorySegment comObject) {
            super(comObject);
        }

        public void GetDevice(MemorySegment ppDevice) {
            try {
                VFUNC3$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 3), comObject, ppDevice);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetPrivateData(MemorySegment guid, MemorySegment pDataSize, MemorySegment pData) {
            try {
                return (int) VFUNC4$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 4), comObject, guid, pDataSize, pData);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int SetPrivateData(MemorySegment guid, int DataSize, MemorySegment pData) {
            try {
                return (int) VFUNC5$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 5), comObject, guid, DataSize, pData);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int SetPrivateDataInterface(MemorySegment guid, MemorySegment pData) {
            try {
                return (int) VFUNC6$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 6), comObject, guid, pData);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

    }

    class VFUNC3$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(ID3D11DeviceChild$ADDRESS_LAYOUT, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC4$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11DeviceChild$ADDRESS_LAYOUT, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC5$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11DeviceChild$ADDRESS_LAYOUT, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC6$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11DeviceChild$ADDRESS_LAYOUT, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class $UPCALL {
        private final ID3D11DeviceChild javaObject;

        private $UPCALL(ID3D11DeviceChild javaObject) {
            this.javaObject = javaObject;
        }

        int QueryInterface(MemorySegment thisObject, MemorySegment riid, MemorySegment ppvObject) {
            return javaObject.QueryInterface(riid, ppvObject);
        }
        int AddRef(MemorySegment thisObject) {
            return javaObject.AddRef();
        }
        int Release(MemorySegment thisObject) {
            return javaObject.Release();
        }
        void GetDevice(MemorySegment thisObject, MemorySegment ppDevice) {
            javaObject.GetDevice(ppDevice);
        }
        int GetPrivateData(MemorySegment thisObject, MemorySegment guid, MemorySegment pDataSize, MemorySegment pData) {
            return javaObject.GetPrivateData(guid, pDataSize, pData);
        }
        int SetPrivateData(MemorySegment thisObject, MemorySegment guid, int DataSize, MemorySegment pData) {
            return javaObject.SetPrivateData(guid, DataSize, pData);
        }
        int SetPrivateDataInterface(MemorySegment thisObject, MemorySegment guid, MemorySegment pData) {
            return javaObject.SetPrivateDataInterface(guid, pData);
        }
    }

    class $UPCALL_IMPL {
        private static final FunctionDescriptor[] DESCRIPTORS = createDescriptors();
        private static final MethodHandle[] HANDLES = createHandles();

        private static FunctionDescriptor[] createDescriptors() {
            var descriptors = new FunctionDescriptor[7];
            descriptors[0] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[1] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[2] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[3] = FunctionDescriptor.ofVoid(ADDRESS, ADDRESS$ADDRESS);
            descriptors[4] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
            descriptors[5] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
            descriptors[6] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            return descriptors;
        }

        private static MethodHandle[] createHandles() {
            try {
                var lookup = MethodHandles.lookup();
                var handles = new MethodHandle[7];
                handles[0] = lookup.findVirtual($UPCALL.class, "QueryInterface", DESCRIPTORS[0].toMethodType());
                handles[1] = lookup.findVirtual($UPCALL.class, "AddRef", DESCRIPTORS[1].toMethodType());
                handles[2] = lookup.findVirtual($UPCALL.class, "Release", DESCRIPTORS[2].toMethodType());
                handles[3] = lookup.findVirtual($UPCALL.class, "GetDevice", DESCRIPTORS[3].toMethodType());
                handles[4] = lookup.findVirtual($UPCALL.class, "GetPrivateData", DESCRIPTORS[4].toMethodType());
                handles[5] = lookup.findVirtual($UPCALL.class, "SetPrivateData", DESCRIPTORS[5].toMethodType());
                handles[6] = lookup.findVirtual($UPCALL.class, "SetPrivateDataInterface", DESCRIPTORS[6].toMethodType());
               return handles;
           } catch (ReflectiveOperationException e) {
               throw new RuntimeException(e);
           }
       }
   }
}
