// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;

/**
 * {@code ID3D11Device} COM interface
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/nn-d3d11-id3d11device">ID3D11Device (Microsoft)</a>
 */
public interface ID3D11Device extends windows.win32.system.com.IUnknown {
    /**
     * {@code CreateBuffer} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateBuffer(
     *     D3D11_BUFFER_DESC* pDesc,
     *     D3D11_SUBRESOURCE_DATA* pInitialData,
     *     ID3D11Buffer* ppBuffer
     * );
     * }
     * </p>
     */
    int CreateBuffer(MemorySegment pDesc, MemorySegment pInitialData, MemorySegment ppBuffer);

    /**
     * {@code CreateTexture1D} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateTexture1D(
     *     D3D11_TEXTURE1D_DESC* pDesc,
     *     D3D11_SUBRESOURCE_DATA* pInitialData,
     *     ID3D11Texture1D* ppTexture1D
     * );
     * }
     * </p>
     */
    int CreateTexture1D(MemorySegment pDesc, MemorySegment pInitialData, MemorySegment ppTexture1D);

    /**
     * {@code CreateTexture2D} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateTexture2D(
     *     D3D11_TEXTURE2D_DESC* pDesc,
     *     D3D11_SUBRESOURCE_DATA* pInitialData,
     *     ID3D11Texture2D* ppTexture2D
     * );
     * }
     * </p>
     */
    int CreateTexture2D(MemorySegment pDesc, MemorySegment pInitialData, MemorySegment ppTexture2D);

    /**
     * {@code CreateTexture3D} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateTexture3D(
     *     D3D11_TEXTURE3D_DESC* pDesc,
     *     D3D11_SUBRESOURCE_DATA* pInitialData,
     *     ID3D11Texture3D* ppTexture3D
     * );
     * }
     * </p>
     */
    int CreateTexture3D(MemorySegment pDesc, MemorySegment pInitialData, MemorySegment ppTexture3D);

    /**
     * {@code CreateShaderResourceView} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateShaderResourceView(
     *     ID3D11Resource pResource,
     *     D3D11_SHADER_RESOURCE_VIEW_DESC* pDesc,
     *     ID3D11ShaderResourceView* ppSRView
     * );
     * }
     * </p>
     */
    int CreateShaderResourceView(MemorySegment pResource, MemorySegment pDesc, MemorySegment ppSRView);

    /**
     * {@code CreateUnorderedAccessView} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateUnorderedAccessView(
     *     ID3D11Resource pResource,
     *     D3D11_UNORDERED_ACCESS_VIEW_DESC* pDesc,
     *     ID3D11UnorderedAccessView* ppUAView
     * );
     * }
     * </p>
     */
    int CreateUnorderedAccessView(MemorySegment pResource, MemorySegment pDesc, MemorySegment ppUAView);

    /**
     * {@code CreateRenderTargetView} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateRenderTargetView(
     *     ID3D11Resource pResource,
     *     D3D11_RENDER_TARGET_VIEW_DESC* pDesc,
     *     ID3D11RenderTargetView* ppRTView
     * );
     * }
     * </p>
     */
    int CreateRenderTargetView(MemorySegment pResource, MemorySegment pDesc, MemorySegment ppRTView);

    /**
     * {@code CreateDepthStencilView} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateDepthStencilView(
     *     ID3D11Resource pResource,
     *     D3D11_DEPTH_STENCIL_VIEW_DESC* pDesc,
     *     ID3D11DepthStencilView* ppDepthStencilView
     * );
     * }
     * </p>
     */
    int CreateDepthStencilView(MemorySegment pResource, MemorySegment pDesc, MemorySegment ppDepthStencilView);

    /**
     * {@code CreateInputLayout} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateInputLayout(
     *     D3D11_INPUT_ELEMENT_DESC* pInputElementDescs,
     *     DWORD NumElements,
     *     void* pShaderBytecodeWithInputSignature,
     *     ULONG_PTR BytecodeLength,
     *     ID3D11InputLayout* ppInputLayout
     * );
     * }
     * </p>
     */
    int CreateInputLayout(MemorySegment pInputElementDescs, int NumElements, MemorySegment pShaderBytecodeWithInputSignature, long BytecodeLength, MemorySegment ppInputLayout);

    /**
     * {@code CreateVertexShader} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateVertexShader(
     *     void* pShaderBytecode,
     *     ULONG_PTR BytecodeLength,
     *     ID3D11ClassLinkage pClassLinkage,
     *     ID3D11VertexShader* ppVertexShader
     * );
     * }
     * </p>
     */
    int CreateVertexShader(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppVertexShader);

    /**
     * {@code CreateGeometryShader} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateGeometryShader(
     *     void* pShaderBytecode,
     *     ULONG_PTR BytecodeLength,
     *     ID3D11ClassLinkage pClassLinkage,
     *     ID3D11GeometryShader* ppGeometryShader
     * );
     * }
     * </p>
     */
    int CreateGeometryShader(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppGeometryShader);

    /**
     * {@code CreateGeometryShaderWithStreamOutput} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateGeometryShaderWithStreamOutput(
     *     void* pShaderBytecode,
     *     ULONG_PTR BytecodeLength,
     *     D3D11_SO_DECLARATION_ENTRY* pSODeclaration,
     *     DWORD NumEntries,
     *     DWORD* pBufferStrides,
     *     DWORD NumStrides,
     *     DWORD RasterizedStream,
     *     ID3D11ClassLinkage pClassLinkage,
     *     ID3D11GeometryShader* ppGeometryShader
     * );
     * }
     * </p>
     */
    int CreateGeometryShaderWithStreamOutput(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pSODeclaration, int NumEntries, MemorySegment pBufferStrides, int NumStrides, int RasterizedStream, MemorySegment pClassLinkage, MemorySegment ppGeometryShader);

    /**
     * {@code CreatePixelShader} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreatePixelShader(
     *     void* pShaderBytecode,
     *     ULONG_PTR BytecodeLength,
     *     ID3D11ClassLinkage pClassLinkage,
     *     ID3D11PixelShader* ppPixelShader
     * );
     * }
     * </p>
     */
    int CreatePixelShader(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppPixelShader);

    /**
     * {@code CreateHullShader} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateHullShader(
     *     void* pShaderBytecode,
     *     ULONG_PTR BytecodeLength,
     *     ID3D11ClassLinkage pClassLinkage,
     *     ID3D11HullShader* ppHullShader
     * );
     * }
     * </p>
     */
    int CreateHullShader(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppHullShader);

    /**
     * {@code CreateDomainShader} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateDomainShader(
     *     void* pShaderBytecode,
     *     ULONG_PTR BytecodeLength,
     *     ID3D11ClassLinkage pClassLinkage,
     *     ID3D11DomainShader* ppDomainShader
     * );
     * }
     * </p>
     */
    int CreateDomainShader(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppDomainShader);

    /**
     * {@code CreateComputeShader} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateComputeShader(
     *     void* pShaderBytecode,
     *     ULONG_PTR BytecodeLength,
     *     ID3D11ClassLinkage pClassLinkage,
     *     ID3D11ComputeShader* ppComputeShader
     * );
     * }
     * </p>
     */
    int CreateComputeShader(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppComputeShader);

    /**
     * {@code CreateClassLinkage} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateClassLinkage(
     *     ID3D11ClassLinkage* ppLinkage
     * );
     * }
     * </p>
     */
    int CreateClassLinkage(MemorySegment ppLinkage);

    /**
     * {@code CreateBlendState} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateBlendState(
     *     D3D11_BLEND_DESC* pBlendStateDesc,
     *     ID3D11BlendState* ppBlendState
     * );
     * }
     * </p>
     */
    int CreateBlendState(MemorySegment pBlendStateDesc, MemorySegment ppBlendState);

    /**
     * {@code CreateDepthStencilState} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateDepthStencilState(
     *     D3D11_DEPTH_STENCIL_DESC* pDepthStencilDesc,
     *     ID3D11DepthStencilState* ppDepthStencilState
     * );
     * }
     * </p>
     */
    int CreateDepthStencilState(MemorySegment pDepthStencilDesc, MemorySegment ppDepthStencilState);

    /**
     * {@code CreateRasterizerState} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateRasterizerState(
     *     D3D11_RASTERIZER_DESC* pRasterizerDesc,
     *     ID3D11RasterizerState* ppRasterizerState
     * );
     * }
     * </p>
     */
    int CreateRasterizerState(MemorySegment pRasterizerDesc, MemorySegment ppRasterizerState);

    /**
     * {@code CreateSamplerState} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateSamplerState(
     *     D3D11_SAMPLER_DESC* pSamplerDesc,
     *     ID3D11SamplerState* ppSamplerState
     * );
     * }
     * </p>
     */
    int CreateSamplerState(MemorySegment pSamplerDesc, MemorySegment ppSamplerState);

    /**
     * {@code CreateQuery} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateQuery(
     *     D3D11_QUERY_DESC* pQueryDesc,
     *     ID3D11Query* ppQuery
     * );
     * }
     * </p>
     */
    int CreateQuery(MemorySegment pQueryDesc, MemorySegment ppQuery);

    /**
     * {@code CreatePredicate} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreatePredicate(
     *     D3D11_QUERY_DESC* pPredicateDesc,
     *     ID3D11Predicate* ppPredicate
     * );
     * }
     * </p>
     */
    int CreatePredicate(MemorySegment pPredicateDesc, MemorySegment ppPredicate);

    /**
     * {@code CreateCounter} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateCounter(
     *     D3D11_COUNTER_DESC* pCounterDesc,
     *     ID3D11Counter* ppCounter
     * );
     * }
     * </p>
     */
    int CreateCounter(MemorySegment pCounterDesc, MemorySegment ppCounter);

    /**
     * {@code CreateDeferredContext} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateDeferredContext(
     *     DWORD ContextFlags,
     *     ID3D11DeviceContext* ppDeferredContext
     * );
     * }
     * </p>
     */
    int CreateDeferredContext(int ContextFlags, MemorySegment ppDeferredContext);

    /**
     * {@code OpenSharedResource} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT OpenSharedResource(
     *     HANDLE hResource,
     *     GUID* ReturnedInterface,
     *     void** ppResource
     * );
     * }
     * </p>
     */
    int OpenSharedResource(MemorySegment hResource, MemorySegment ReturnedInterface, MemorySegment ppResource);

    /**
     * {@code CheckFormatSupport} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CheckFormatSupport(
     *     DXGI_FORMAT Format,
     *     DWORD* pFormatSupport
     * );
     * }
     * </p>
     */
    int CheckFormatSupport(int Format, MemorySegment pFormatSupport);

    /**
     * {@code CheckMultisampleQualityLevels} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CheckMultisampleQualityLevels(
     *     DXGI_FORMAT Format,
     *     DWORD SampleCount,
     *     DWORD* pNumQualityLevels
     * );
     * }
     * </p>
     */
    int CheckMultisampleQualityLevels(int Format, int SampleCount, MemorySegment pNumQualityLevels);

    /**
     * {@code CheckCounterInfo} COM interface method
     * <p>
     * {@snippet lang=c :
     * void CheckCounterInfo(
     *     D3D11_COUNTER_INFO* pCounterInfo
     * );
     * }
     * </p>
     */
    void CheckCounterInfo(MemorySegment pCounterInfo);

    /**
     * {@code CheckCounter} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CheckCounter(
     *     D3D11_COUNTER_DESC* pDesc,
     *     D3D11_COUNTER_TYPE* pType,
     *     DWORD* pActiveCounters,
     *     PSTR szName,
     *     DWORD* pNameLength,
     *     PSTR szUnits,
     *     DWORD* pUnitsLength,
     *     PSTR szDescription,
     *     DWORD* pDescriptionLength
     * );
     * }
     * </p>
     */
    int CheckCounter(MemorySegment pDesc, MemorySegment pType, MemorySegment pActiveCounters, MemorySegment szName, MemorySegment pNameLength, MemorySegment szUnits, MemorySegment pUnitsLength, MemorySegment szDescription, MemorySegment pDescriptionLength);

    /**
     * {@code CheckFeatureSupport} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CheckFeatureSupport(
     *     D3D11_FEATURE Feature,
     *     void* pFeatureSupportData,
     *     DWORD FeatureSupportDataSize
     * );
     * }
     * </p>
     */
    int CheckFeatureSupport(int Feature, MemorySegment pFeatureSupportData, int FeatureSupportDataSize);

    /**
     * {@code GetPrivateData} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetPrivateData(
     *     GUID* guid,
     *     DWORD* pDataSize,
     *     void* pData
     * );
     * }
     * </p>
     */
    int GetPrivateData(MemorySegment guid, MemorySegment pDataSize, MemorySegment pData);

    /**
     * {@code SetPrivateData} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT SetPrivateData(
     *     GUID* guid,
     *     DWORD DataSize,
     *     void* pData
     * );
     * }
     * </p>
     */
    int SetPrivateData(MemorySegment guid, int DataSize, MemorySegment pData);

    /**
     * {@code SetPrivateDataInterface} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT SetPrivateDataInterface(
     *     GUID* guid,
     *     IUnknown pData
     * );
     * }
     * </p>
     */
    int SetPrivateDataInterface(MemorySegment guid, MemorySegment pData);

    /**
     * {@code GetFeatureLevel} COM interface method
     * <p>
     * {@snippet lang=c :
     * D3D_FEATURE_LEVEL GetFeatureLevel(
     * );
     * }
     * </p>
     */
    int GetFeatureLevel();

    /**
     * {@code GetCreationFlags} COM interface method
     * <p>
     * {@snippet lang=c :
     * DWORD GetCreationFlags(
     * );
     * }
     * </p>
     */
    int GetCreationFlags();

    /**
     * {@code GetDeviceRemovedReason} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetDeviceRemovedReason(
     * );
     * }
     * </p>
     */
    int GetDeviceRemovedReason();

    /**
     * {@code GetImmediateContext} COM interface method
     * <p>
     * {@snippet lang=c :
     * void GetImmediateContext(
     *     ID3D11DeviceContext* ppImmediateContext
     * );
     * }
     * </p>
     */
    void GetImmediateContext(MemorySegment ppImmediateContext);

    /**
     * {@code SetExceptionMode} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT SetExceptionMode(
     *     DWORD RaiseFlags
     * );
     * }
     * </p>
     */
    int SetExceptionMode(int RaiseFlags);

    /**
     * {@code GetExceptionMode} COM interface method
     * <p>
     * {@snippet lang=c :
     * DWORD GetExceptionMode(
     * );
     * }
     * </p>
     */
    int GetExceptionMode();

    /**
     * Wraps the given COM object in a Java object with methods to call the COM interface functions.
     */
    static ID3D11Device wrap(MemorySegment comObject) {
        return new $DOWNCALL(comObject.reinterpret(8L));
    }

    /**
     * Gets the address layout for pointers to {@code ID3D11Device} COM interfaces.
     */
    static AddressLayout addressLayout() {
        return ID3D11Device$ADDRESS_LAYOUT;
    }

    /**
     * Interface identifier (IID) for {@code ID3D11Device} ({@code {db6f6ddb-ac77-4e88-8253-819df9bbf140}}).
     */
    static MemorySegment iid() {
        return $IID$ID3D11Device.IID$SEG;
    }

    /**
     * Creates a COM object instance for the given Java object implementing {@code ID3D11Device}.
     */
    static MemorySegment create(ID3D11Device obj, Arena arena) {
        var unwrapper = new $UPCALL(obj);
        var vtable = arena.allocate(ADDRESS, 43);
        var linker = Linker.nativeLinker();
        for (int i = 0; i < 43; i++)
            vtable.set(ADDRESS, 8 * i, linker.upcallStub($UPCALL_IMPL.HANDLES[i].bindTo(unwrapper), $UPCALL_IMPL.DESCRIPTORS[i], arena));
        var objSegment = arena.allocate(ADDRESS);
        objSegment.set(ADDRESS, 0, vtable);
        return objSegment;
    }

    StructLayout ID3D11Device$COM_OBJECT_LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(43, ADDRESS)).withName("vtable")
    );

    AddressLayout ID3D11Device$ADDRESS_LAYOUT = ADDRESS.withTargetLayout(ID3D11Device$COM_OBJECT_LAYOUT);

    AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));
    AddressLayout ADDRESS$STRUCT_8_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(8, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_12_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(12, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_16_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_16_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(8));
    AddressLayout ADDRESS$STRUCT_20_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(20, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_24_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(24, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_24_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(24, JAVA_BYTE).withByteAlignment(8));
    AddressLayout ADDRESS$STRUCT_32_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(32, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_32_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(32, JAVA_BYTE).withByteAlignment(8));
    AddressLayout ADDRESS$STRUCT_36_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(36, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_40_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(40, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_44_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(44, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_52_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(52, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_264_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(264, JAVA_BYTE).withByteAlignment(4));

    class $IID$ID3D11Device {
        private static final Arena ARENA = Arena.ofAuto();

        private static MemorySegment createGuid(long v1, long v2) {
            var seg = ARENA.allocate(16, 8);
            seg.set(ValueLayout.JAVA_LONG, 0, v1);
            seg.set(ValueLayout.JAVA_LONG, 8, v2);
            return seg;
        }

        private static final MemorySegment IID$SEG = createGuid(5658962562573626843L, 4679728168578405250L);

    }

    class $DOWNCALL extends windows.win32.system.com.IUnknown.$DOWNCALL implements ID3D11Device {
        private static final VarHandle VTABLE_FUNC_VARHANDLE = ID3D11Device$COM_OBJECT_LAYOUT.varHandle(
                PathElement.groupElement("vtable"),
                PathElement.dereferenceElement(),
                PathElement.sequenceElement()
        );

        private static MemorySegment vtableFunc(MemorySegment comObject, long index) {
            return (MemorySegment) VTABLE_FUNC_VARHANDLE.get(comObject, 0L, index);
        }

        protected $DOWNCALL(MemorySegment comObject) {
            super(comObject);
        }

        public int CreateBuffer(MemorySegment pDesc, MemorySegment pInitialData, MemorySegment ppBuffer) {
            try {
                return (int) VFUNC3$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 3), comObject, pDesc, pInitialData, ppBuffer);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateTexture1D(MemorySegment pDesc, MemorySegment pInitialData, MemorySegment ppTexture1D) {
            try {
                return (int) VFUNC4$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 4), comObject, pDesc, pInitialData, ppTexture1D);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateTexture2D(MemorySegment pDesc, MemorySegment pInitialData, MemorySegment ppTexture2D) {
            try {
                return (int) VFUNC5$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 5), comObject, pDesc, pInitialData, ppTexture2D);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateTexture3D(MemorySegment pDesc, MemorySegment pInitialData, MemorySegment ppTexture3D) {
            try {
                return (int) VFUNC6$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 6), comObject, pDesc, pInitialData, ppTexture3D);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateShaderResourceView(MemorySegment pResource, MemorySegment pDesc, MemorySegment ppSRView) {
            try {
                return (int) VFUNC7$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 7), comObject, pResource, pDesc, ppSRView);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateUnorderedAccessView(MemorySegment pResource, MemorySegment pDesc, MemorySegment ppUAView) {
            try {
                return (int) VFUNC8$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 8), comObject, pResource, pDesc, ppUAView);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateRenderTargetView(MemorySegment pResource, MemorySegment pDesc, MemorySegment ppRTView) {
            try {
                return (int) VFUNC9$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 9), comObject, pResource, pDesc, ppRTView);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateDepthStencilView(MemorySegment pResource, MemorySegment pDesc, MemorySegment ppDepthStencilView) {
            try {
                return (int) VFUNC10$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 10), comObject, pResource, pDesc, ppDepthStencilView);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateInputLayout(MemorySegment pInputElementDescs, int NumElements, MemorySegment pShaderBytecodeWithInputSignature, long BytecodeLength, MemorySegment ppInputLayout) {
            try {
                return (int) VFUNC11$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 11), comObject, pInputElementDescs, NumElements, pShaderBytecodeWithInputSignature, BytecodeLength, ppInputLayout);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateVertexShader(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppVertexShader) {
            try {
                return (int) VFUNC12$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 12), comObject, pShaderBytecode, BytecodeLength, pClassLinkage, ppVertexShader);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateGeometryShader(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppGeometryShader) {
            try {
                return (int) VFUNC13$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 13), comObject, pShaderBytecode, BytecodeLength, pClassLinkage, ppGeometryShader);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateGeometryShaderWithStreamOutput(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pSODeclaration, int NumEntries, MemorySegment pBufferStrides, int NumStrides, int RasterizedStream, MemorySegment pClassLinkage, MemorySegment ppGeometryShader) {
            try {
                return (int) VFUNC14$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 14), comObject, pShaderBytecode, BytecodeLength, pSODeclaration, NumEntries, pBufferStrides, NumStrides, RasterizedStream, pClassLinkage, ppGeometryShader);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreatePixelShader(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppPixelShader) {
            try {
                return (int) VFUNC15$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 15), comObject, pShaderBytecode, BytecodeLength, pClassLinkage, ppPixelShader);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateHullShader(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppHullShader) {
            try {
                return (int) VFUNC16$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 16), comObject, pShaderBytecode, BytecodeLength, pClassLinkage, ppHullShader);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateDomainShader(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppDomainShader) {
            try {
                return (int) VFUNC17$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 17), comObject, pShaderBytecode, BytecodeLength, pClassLinkage, ppDomainShader);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateComputeShader(MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppComputeShader) {
            try {
                return (int) VFUNC18$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 18), comObject, pShaderBytecode, BytecodeLength, pClassLinkage, ppComputeShader);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateClassLinkage(MemorySegment ppLinkage) {
            try {
                return (int) VFUNC19$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 19), comObject, ppLinkage);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateBlendState(MemorySegment pBlendStateDesc, MemorySegment ppBlendState) {
            try {
                return (int) VFUNC20$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 20), comObject, pBlendStateDesc, ppBlendState);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateDepthStencilState(MemorySegment pDepthStencilDesc, MemorySegment ppDepthStencilState) {
            try {
                return (int) VFUNC21$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 21), comObject, pDepthStencilDesc, ppDepthStencilState);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateRasterizerState(MemorySegment pRasterizerDesc, MemorySegment ppRasterizerState) {
            try {
                return (int) VFUNC22$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 22), comObject, pRasterizerDesc, ppRasterizerState);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateSamplerState(MemorySegment pSamplerDesc, MemorySegment ppSamplerState) {
            try {
                return (int) VFUNC23$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 23), comObject, pSamplerDesc, ppSamplerState);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateQuery(MemorySegment pQueryDesc, MemorySegment ppQuery) {
            try {
                return (int) VFUNC24$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 24), comObject, pQueryDesc, ppQuery);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreatePredicate(MemorySegment pPredicateDesc, MemorySegment ppPredicate) {
            try {
                return (int) VFUNC25$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 25), comObject, pPredicateDesc, ppPredicate);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateCounter(MemorySegment pCounterDesc, MemorySegment ppCounter) {
            try {
                return (int) VFUNC26$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 26), comObject, pCounterDesc, ppCounter);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateDeferredContext(int ContextFlags, MemorySegment ppDeferredContext) {
            try {
                return (int) VFUNC27$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 27), comObject, ContextFlags, ppDeferredContext);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int OpenSharedResource(MemorySegment hResource, MemorySegment ReturnedInterface, MemorySegment ppResource) {
            try {
                return (int) VFUNC28$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 28), comObject, hResource, ReturnedInterface, ppResource);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CheckFormatSupport(int Format, MemorySegment pFormatSupport) {
            try {
                return (int) VFUNC29$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 29), comObject, Format, pFormatSupport);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CheckMultisampleQualityLevels(int Format, int SampleCount, MemorySegment pNumQualityLevels) {
            try {
                return (int) VFUNC30$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 30), comObject, Format, SampleCount, pNumQualityLevels);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public void CheckCounterInfo(MemorySegment pCounterInfo) {
            try {
                VFUNC31$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 31), comObject, pCounterInfo);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CheckCounter(MemorySegment pDesc, MemorySegment pType, MemorySegment pActiveCounters, MemorySegment szName, MemorySegment pNameLength, MemorySegment szUnits, MemorySegment pUnitsLength, MemorySegment szDescription, MemorySegment pDescriptionLength) {
            try {
                return (int) VFUNC32$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 32), comObject, pDesc, pType, pActiveCounters, szName, pNameLength, szUnits, pUnitsLength, szDescription, pDescriptionLength);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CheckFeatureSupport(int Feature, MemorySegment pFeatureSupportData, int FeatureSupportDataSize) {
            try {
                return (int) VFUNC33$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 33), comObject, Feature, pFeatureSupportData, FeatureSupportDataSize);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetPrivateData(MemorySegment guid, MemorySegment pDataSize, MemorySegment pData) {
            try {
                return (int) VFUNC34$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 34), comObject, guid, pDataSize, pData);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int SetPrivateData(MemorySegment guid, int DataSize, MemorySegment pData) {
            try {
                return (int) VFUNC35$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 35), comObject, guid, DataSize, pData);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int SetPrivateDataInterface(MemorySegment guid, MemorySegment pData) {
            try {
                return (int) VFUNC36$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 36), comObject, guid, pData);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetFeatureLevel() {
            try {
                return (int) VFUNC37$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 37), comObject);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetCreationFlags() {
            try {
                return (int) VFUNC38$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 38), comObject);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetDeviceRemovedReason() {
            try {
                return (int) VFUNC39$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 39), comObject);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public void GetImmediateContext(MemorySegment ppImmediateContext) {
            try {
                VFUNC40$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 40), comObject, ppImmediateContext);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int SetExceptionMode(int RaiseFlags) {
            try {
                return (int) VFUNC41$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 41), comObject, RaiseFlags);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetExceptionMode() {
            try {
                return (int) VFUNC42$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 42), comObject);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

    }

    class VFUNC3$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_24_4, ADDRESS$STRUCT_16_8, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC4$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_32_4, ADDRESS$STRUCT_16_8, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC5$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_44_4, ADDRESS$STRUCT_16_8, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC6$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_36_4, ADDRESS$STRUCT_16_8, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC7$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$ADDRESS, ADDRESS$STRUCT_24_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC8$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$ADDRESS, ADDRESS$STRUCT_20_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC9$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$ADDRESS, ADDRESS$STRUCT_20_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC10$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$ADDRESS, ADDRESS$STRUCT_24_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC11$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_32_8, JAVA_INT, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC12$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC13$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC14$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS, JAVA_LONG, ADDRESS$STRUCT_24_8, JAVA_INT, ADDRESS$UNKNOWN_SIZE, JAVA_INT, JAVA_INT, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC15$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC16$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC17$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC18$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC19$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC20$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_264_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC21$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_52_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC22$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_40_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC23$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_52_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC24$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_8_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC25$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_8_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC26$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_8_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC27$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, JAVA_INT, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC28$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC29$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, JAVA_INT, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC30$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, JAVA_INT, JAVA_INT, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC31$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_12_4);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC32$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_8_4, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC33$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, JAVA_INT, ADDRESS, JAVA_INT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC34$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC35$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC36$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC37$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC38$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC39$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC40$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(ID3D11Device$ADDRESS_LAYOUT, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC41$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT, JAVA_INT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC42$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ID3D11Device$ADDRESS_LAYOUT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class $UPCALL {
        private final ID3D11Device javaObject;

        private $UPCALL(ID3D11Device javaObject) {
            this.javaObject = javaObject;
        }

        int QueryInterface(MemorySegment thisObject, MemorySegment riid, MemorySegment ppvObject) {
            return javaObject.QueryInterface(riid, ppvObject);
        }
        int AddRef(MemorySegment thisObject) {
            return javaObject.AddRef();
        }
        int Release(MemorySegment thisObject) {
            return javaObject.Release();
        }
        int CreateBuffer(MemorySegment thisObject, MemorySegment pDesc, MemorySegment pInitialData, MemorySegment ppBuffer) {
            return javaObject.CreateBuffer(pDesc, pInitialData, ppBuffer);
        }
        int CreateTexture1D(MemorySegment thisObject, MemorySegment pDesc, MemorySegment pInitialData, MemorySegment ppTexture1D) {
            return javaObject.CreateTexture1D(pDesc, pInitialData, ppTexture1D);
        }
        int CreateTexture2D(MemorySegment thisObject, MemorySegment pDesc, MemorySegment pInitialData, MemorySegment ppTexture2D) {
            return javaObject.CreateTexture2D(pDesc, pInitialData, ppTexture2D);
        }
        int CreateTexture3D(MemorySegment thisObject, MemorySegment pDesc, MemorySegment pInitialData, MemorySegment ppTexture3D) {
            return javaObject.CreateTexture3D(pDesc, pInitialData, ppTexture3D);
        }
        int CreateShaderResourceView(MemorySegment thisObject, MemorySegment pResource, MemorySegment pDesc, MemorySegment ppSRView) {
            return javaObject.CreateShaderResourceView(pResource, pDesc, ppSRView);
        }
        int CreateUnorderedAccessView(MemorySegment thisObject, MemorySegment pResource, MemorySegment pDesc, MemorySegment ppUAView) {
            return javaObject.CreateUnorderedAccessView(pResource, pDesc, ppUAView);
        }
        int CreateRenderTargetView(MemorySegment thisObject, MemorySegment pResource, MemorySegment pDesc, MemorySegment ppRTView) {
            return javaObject.CreateRenderTargetView(pResource, pDesc, ppRTView);
        }
        int CreateDepthStencilView(MemorySegment thisObject, MemorySegment pResource, MemorySegment pDesc, MemorySegment ppDepthStencilView) {
            return javaObject.CreateDepthStencilView(pResource, pDesc, ppDepthStencilView);
        }
        int CreateInputLayout(MemorySegment thisObject, MemorySegment pInputElementDescs, int NumElements, MemorySegment pShaderBytecodeWithInputSignature, long BytecodeLength, MemorySegment ppInputLayout) {
            return javaObject.CreateInputLayout(pInputElementDescs, NumElements, pShaderBytecodeWithInputSignature, BytecodeLength, ppInputLayout);
        }
        int CreateVertexShader(MemorySegment thisObject, MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppVertexShader) {
            return javaObject.CreateVertexShader(pShaderBytecode, BytecodeLength, pClassLinkage, ppVertexShader);
        }
        int CreateGeometryShader(MemorySegment thisObject, MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppGeometryShader) {
            return javaObject.CreateGeometryShader(pShaderBytecode, BytecodeLength, pClassLinkage, ppGeometryShader);
        }
        int CreateGeometryShaderWithStreamOutput(MemorySegment thisObject, MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pSODeclaration, int NumEntries, MemorySegment pBufferStrides, int NumStrides, int RasterizedStream, MemorySegment pClassLinkage, MemorySegment ppGeometryShader) {
            return javaObject.CreateGeometryShaderWithStreamOutput(pShaderBytecode, BytecodeLength, pSODeclaration, NumEntries, pBufferStrides, NumStrides, RasterizedStream, pClassLinkage, ppGeometryShader);
        }
        int CreatePixelShader(MemorySegment thisObject, MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppPixelShader) {
            return javaObject.CreatePixelShader(pShaderBytecode, BytecodeLength, pClassLinkage, ppPixelShader);
        }
        int CreateHullShader(MemorySegment thisObject, MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppHullShader) {
            return javaObject.CreateHullShader(pShaderBytecode, BytecodeLength, pClassLinkage, ppHullShader);
        }
        int CreateDomainShader(MemorySegment thisObject, MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppDomainShader) {
            return javaObject.CreateDomainShader(pShaderBytecode, BytecodeLength, pClassLinkage, ppDomainShader);
        }
        int CreateComputeShader(MemorySegment thisObject, MemorySegment pShaderBytecode, long BytecodeLength, MemorySegment pClassLinkage, MemorySegment ppComputeShader) {
            return javaObject.CreateComputeShader(pShaderBytecode, BytecodeLength, pClassLinkage, ppComputeShader);
        }
        int CreateClassLinkage(MemorySegment thisObject, MemorySegment ppLinkage) {
            return javaObject.CreateClassLinkage(ppLinkage);
        }
        int CreateBlendState(MemorySegment thisObject, MemorySegment pBlendStateDesc, MemorySegment ppBlendState) {
            return javaObject.CreateBlendState(pBlendStateDesc, ppBlendState);
        }
        int CreateDepthStencilState(MemorySegment thisObject, MemorySegment pDepthStencilDesc, MemorySegment ppDepthStencilState) {
            return javaObject.CreateDepthStencilState(pDepthStencilDesc, ppDepthStencilState);
        }
        int CreateRasterizerState(MemorySegment thisObject, MemorySegment pRasterizerDesc, MemorySegment ppRasterizerState) {
            return javaObject.CreateRasterizerState(pRasterizerDesc, ppRasterizerState);
        }
        int CreateSamplerState(MemorySegment thisObject, MemorySegment pSamplerDesc, MemorySegment ppSamplerState) {
            return javaObject.CreateSamplerState(pSamplerDesc, ppSamplerState);
        }
        int CreateQuery(MemorySegment thisObject, MemorySegment pQueryDesc, MemorySegment ppQuery) {
            return javaObject.CreateQuery(pQueryDesc, ppQuery);
        }
        int CreatePredicate(MemorySegment thisObject, MemorySegment pPredicateDesc, MemorySegment ppPredicate) {
            return javaObject.CreatePredicate(pPredicateDesc, ppPredicate);
        }
        int CreateCounter(MemorySegment thisObject, MemorySegment pCounterDesc, MemorySegment ppCounter) {
            return javaObject.CreateCounter(pCounterDesc, ppCounter);
        }
        int CreateDeferredContext(MemorySegment thisObject, int ContextFlags, MemorySegment ppDeferredContext) {
            return javaObject.CreateDeferredContext(ContextFlags, ppDeferredContext);
        }
        int OpenSharedResource(MemorySegment thisObject, MemorySegment hResource, MemorySegment ReturnedInterface, MemorySegment ppResource) {
            return javaObject.OpenSharedResource(hResource, ReturnedInterface, ppResource);
        }
        int CheckFormatSupport(MemorySegment thisObject, int Format, MemorySegment pFormatSupport) {
            return javaObject.CheckFormatSupport(Format, pFormatSupport);
        }
        int CheckMultisampleQualityLevels(MemorySegment thisObject, int Format, int SampleCount, MemorySegment pNumQualityLevels) {
            return javaObject.CheckMultisampleQualityLevels(Format, SampleCount, pNumQualityLevels);
        }
        void CheckCounterInfo(MemorySegment thisObject, MemorySegment pCounterInfo) {
            javaObject.CheckCounterInfo(pCounterInfo);
        }
        int CheckCounter(MemorySegment thisObject, MemorySegment pDesc, MemorySegment pType, MemorySegment pActiveCounters, MemorySegment szName, MemorySegment pNameLength, MemorySegment szUnits, MemorySegment pUnitsLength, MemorySegment szDescription, MemorySegment pDescriptionLength) {
            return javaObject.CheckCounter(pDesc, pType, pActiveCounters, szName, pNameLength, szUnits, pUnitsLength, szDescription, pDescriptionLength);
        }
        int CheckFeatureSupport(MemorySegment thisObject, int Feature, MemorySegment pFeatureSupportData, int FeatureSupportDataSize) {
            return javaObject.CheckFeatureSupport(Feature, pFeatureSupportData, FeatureSupportDataSize);
        }
        int GetPrivateData(MemorySegment thisObject, MemorySegment guid, MemorySegment pDataSize, MemorySegment pData) {
            return javaObject.GetPrivateData(guid, pDataSize, pData);
        }
        int SetPrivateData(MemorySegment thisObject, MemorySegment guid, int DataSize, MemorySegment pData) {
            return javaObject.SetPrivateData(guid, DataSize, pData);
        }
        int SetPrivateDataInterface(MemorySegment thisObject, MemorySegment guid, MemorySegment pData) {
            return javaObject.SetPrivateDataInterface(guid, pData);
        }
        int GetFeatureLevel(MemorySegment thisObject) {
            return javaObject.GetFeatureLevel();
        }
        int GetCreationFlags(MemorySegment thisObject) {
            return javaObject.GetCreationFlags();
        }
        int GetDeviceRemovedReason(MemorySegment thisObject) {
            return javaObject.GetDeviceRemovedReason();
        }
        void GetImmediateContext(MemorySegment thisObject, MemorySegment ppImmediateContext) {
            javaObject.GetImmediateContext(ppImmediateContext);
        }
        int SetExceptionMode(MemorySegment thisObject, int RaiseFlags) {
            return javaObject.SetExceptionMode(RaiseFlags);
        }
        int GetExceptionMode(MemorySegment thisObject) {
            return javaObject.GetExceptionMode();
        }
    }

    class $UPCALL_IMPL {
        private static final FunctionDescriptor[] DESCRIPTORS = createDescriptors();
        private static final MethodHandle[] HANDLES = createHandles();

        private static FunctionDescriptor[] createDescriptors() {
            var descriptors = new FunctionDescriptor[43];
            descriptors[0] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[1] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[2] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[3] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_24_4, ADDRESS$STRUCT_16_8, ADDRESS$ADDRESS);
            descriptors[4] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_32_4, ADDRESS$STRUCT_16_8, ADDRESS$ADDRESS);
            descriptors[5] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_44_4, ADDRESS$STRUCT_16_8, ADDRESS$ADDRESS);
            descriptors[6] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_36_4, ADDRESS$STRUCT_16_8, ADDRESS$ADDRESS);
            descriptors[7] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS, ADDRESS$STRUCT_24_4, ADDRESS$ADDRESS);
            descriptors[8] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS, ADDRESS$STRUCT_20_4, ADDRESS$ADDRESS);
            descriptors[9] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS, ADDRESS$STRUCT_20_4, ADDRESS$ADDRESS);
            descriptors[10] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS, ADDRESS$STRUCT_24_4, ADDRESS$ADDRESS);
            descriptors[11] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_32_8, JAVA_INT, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS);
            descriptors[12] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
            descriptors[13] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
            descriptors[14] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_LONG, ADDRESS$STRUCT_24_8, JAVA_INT, ADDRESS$UNKNOWN_SIZE, JAVA_INT, JAVA_INT, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
            descriptors[15] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
            descriptors[16] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
            descriptors[17] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
            descriptors[18] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_LONG, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
            descriptors[19] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS);
            descriptors[20] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_264_4, ADDRESS$ADDRESS);
            descriptors[21] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_52_4, ADDRESS$ADDRESS);
            descriptors[22] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_40_4, ADDRESS$ADDRESS);
            descriptors[23] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_52_4, ADDRESS$ADDRESS);
            descriptors[24] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_8_4, ADDRESS$ADDRESS);
            descriptors[25] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_8_4, ADDRESS$ADDRESS);
            descriptors[26] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_8_4, ADDRESS$ADDRESS);
            descriptors[27] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$ADDRESS);
            descriptors[28] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[29] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$UNKNOWN_SIZE);
            descriptors[30] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT, ADDRESS$UNKNOWN_SIZE);
            descriptors[31] = FunctionDescriptor.ofVoid(ADDRESS, ADDRESS$STRUCT_12_4);
            descriptors[32] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_8_4, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE);
            descriptors[33] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT);
            descriptors[34] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
            descriptors[35] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
            descriptors[36] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[37] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[38] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[39] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[40] = FunctionDescriptor.ofVoid(ADDRESS, ADDRESS$ADDRESS);
            descriptors[41] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT);
            descriptors[42] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            return descriptors;
        }

        private static MethodHandle[] createHandles() {
            try {
                var lookup = MethodHandles.lookup();
                var handles = new MethodHandle[43];
                handles[0] = lookup.findVirtual($UPCALL.class, "QueryInterface", DESCRIPTORS[0].toMethodType());
                handles[1] = lookup.findVirtual($UPCALL.class, "AddRef", DESCRIPTORS[1].toMethodType());
                handles[2] = lookup.findVirtual($UPCALL.class, "Release", DESCRIPTORS[2].toMethodType());
                handles[3] = lookup.findVirtual($UPCALL.class, "CreateBuffer", DESCRIPTORS[3].toMethodType());
                handles[4] = lookup.findVirtual($UPCALL.class, "CreateTexture1D", DESCRIPTORS[4].toMethodType());
                handles[5] = lookup.findVirtual($UPCALL.class, "CreateTexture2D", DESCRIPTORS[5].toMethodType());
                handles[6] = lookup.findVirtual($UPCALL.class, "CreateTexture3D", DESCRIPTORS[6].toMethodType());
                handles[7] = lookup.findVirtual($UPCALL.class, "CreateShaderResourceView", DESCRIPTORS[7].toMethodType());
                handles[8] = lookup.findVirtual($UPCALL.class, "CreateUnorderedAccessView", DESCRIPTORS[8].toMethodType());
                handles[9] = lookup.findVirtual($UPCALL.class, "CreateRenderTargetView", DESCRIPTORS[9].toMethodType());
                handles[10] = lookup.findVirtual($UPCALL.class, "CreateDepthStencilView", DESCRIPTORS[10].toMethodType());
                handles[11] = lookup.findVirtual($UPCALL.class, "CreateInputLayout", DESCRIPTORS[11].toMethodType());
                handles[12] = lookup.findVirtual($UPCALL.class, "CreateVertexShader", DESCRIPTORS[12].toMethodType());
                handles[13] = lookup.findVirtual($UPCALL.class, "CreateGeometryShader", DESCRIPTORS[13].toMethodType());
                handles[14] = lookup.findVirtual($UPCALL.class, "CreateGeometryShaderWithStreamOutput", DESCRIPTORS[14].toMethodType());
                handles[15] = lookup.findVirtual($UPCALL.class, "CreatePixelShader", DESCRIPTORS[15].toMethodType());
                handles[16] = lookup.findVirtual($UPCALL.class, "CreateHullShader", DESCRIPTORS[16].toMethodType());
                handles[17] = lookup.findVirtual($UPCALL.class, "CreateDomainShader", DESCRIPTORS[17].toMethodType());
                handles[18] = lookup.findVirtual($UPCALL.class, "CreateComputeShader", DESCRIPTORS[18].toMethodType());
                handles[19] = lookup.findVirtual($UPCALL.class, "CreateClassLinkage", DESCRIPTORS[19].toMethodType());
                handles[20] = lookup.findVirtual($UPCALL.class, "CreateBlendState", DESCRIPTORS[20].toMethodType());
                handles[21] = lookup.findVirtual($UPCALL.class, "CreateDepthStencilState", DESCRIPTORS[21].toMethodType());
                handles[22] = lookup.findVirtual($UPCALL.class, "CreateRasterizerState", DESCRIPTORS[22].toMethodType());
                handles[23] = lookup.findVirtual($UPCALL.class, "CreateSamplerState", DESCRIPTORS[23].toMethodType());
                handles[24] = lookup.findVirtual($UPCALL.class, "CreateQuery", DESCRIPTORS[24].toMethodType());
                handles[25] = lookup.findVirtual($UPCALL.class, "CreatePredicate", DESCRIPTORS[25].toMethodType());
                handles[26] = lookup.findVirtual($UPCALL.class, "CreateCounter", DESCRIPTORS[26].toMethodType());
                handles[27] = lookup.findVirtual($UPCALL.class, "CreateDeferredContext", DESCRIPTORS[27].toMethodType());
                handles[28] = lookup.findVirtual($UPCALL.class, "OpenSharedResource", DESCRIPTORS[28].toMethodType());
                handles[29] = lookup.findVirtual($UPCALL.class, "CheckFormatSupport", DESCRIPTORS[29].toMethodType());
                handles[30] = lookup.findVirtual($UPCALL.class, "CheckMultisampleQualityLevels", DESCRIPTORS[30].toMethodType());
                handles[31] = lookup.findVirtual($UPCALL.class, "CheckCounterInfo", DESCRIPTORS[31].toMethodType());
                handles[32] = lookup.findVirtual($UPCALL.class, "CheckCounter", DESCRIPTORS[32].toMethodType());
                handles[33] = lookup.findVirtual($UPCALL.class, "CheckFeatureSupport", DESCRIPTORS[33].toMethodType());
                handles[34] = lookup.findVirtual($UPCALL.class, "GetPrivateData", DESCRIPTORS[34].toMethodType());
                handles[35] = lookup.findVirtual($UPCALL.class, "SetPrivateData", DESCRIPTORS[35].toMethodType());
                handles[36] = lookup.findVirtual($UPCALL.class, "SetPrivateDataInterface", DESCRIPTORS[36].toMethodType());
                handles[37] = lookup.findVirtual($UPCALL.class, "GetFeatureLevel", DESCRIPTORS[37].toMethodType());
                handles[38] = lookup.findVirtual($UPCALL.class, "GetCreationFlags", DESCRIPTORS[38].toMethodType());
                handles[39] = lookup.findVirtual($UPCALL.class, "GetDeviceRemovedReason", DESCRIPTORS[39].toMethodType());
                handles[40] = lookup.findVirtual($UPCALL.class, "GetImmediateContext", DESCRIPTORS[40].toMethodType());
                handles[41] = lookup.findVirtual($UPCALL.class, "SetExceptionMode", DESCRIPTORS[41].toMethodType());
                handles[42] = lookup.findVirtual($UPCALL.class, "GetExceptionMode", DESCRIPTORS[42].toMethodType());
               return handles;
           } catch (ReflectiveOperationException e) {
               throw new RuntimeException(e);
           }
       }
   }
}
