// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d11;

import java.lang.foreign.*;
import java.lang.invoke.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code ID3D11VertexShader} COM interface
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3d11/nn-d3d11-id3d11vertexshader">ID3D11VertexShader (Microsoft)</a>
 */
public interface ID3D11VertexShader extends ID3D11DeviceChild {
    /**
     * Wraps the given COM object in a Java object with methods to call the COM interface functions.
     */
    static ID3D11VertexShader wrap(MemorySegment comObject) {
        return new $DOWNCALL(comObject.reinterpret(8L));
    }

    /**
     * Gets the address layout for pointers to {@code ID3D11VertexShader} COM interfaces.
     */
    static AddressLayout addressLayout() {
        return ID3D11VertexShader$ADDRESS_LAYOUT;
    }

    /**
     * Interface identifier (IID) for {@code ID3D11VertexShader} ({@code {3b301d64-d678-4289-8897-22f8928b72f3}}).
     */
    static MemorySegment iid() {
        return $IID$ID3D11VertexShader.IID$SEG;
    }

    /**
     * Creates a COM object instance for the given Java object implementing {@code ID3D11VertexShader}.
     */
    static MemorySegment create(ID3D11VertexShader obj, Arena arena) {
        var unwrapper = new $UPCALL(obj);
        var vtable = arena.allocate(ADDRESS, 7);
        var linker = Linker.nativeLinker();
        for (int i = 0; i < 7; i++)
            vtable.set(ADDRESS, 8 * i, linker.upcallStub($UPCALL_IMPL.HANDLES[i].bindTo(unwrapper), $UPCALL_IMPL.DESCRIPTORS[i], arena));
        var objSegment = arena.allocate(ADDRESS);
        objSegment.set(ADDRESS, 0, vtable);
        return objSegment;
    }

    StructLayout ID3D11VertexShader$COM_OBJECT_LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(7, ADDRESS)).withName("vtable")
    );

    AddressLayout ID3D11VertexShader$ADDRESS_LAYOUT = ADDRESS.withTargetLayout(ID3D11VertexShader$COM_OBJECT_LAYOUT);

    AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));
    AddressLayout ADDRESS$STRUCT_16_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(4));

    class $IID$ID3D11VertexShader {
        private static final Arena ARENA = Arena.ofAuto();

        private static MemorySegment createGuid(long v1, long v2) {
            var seg = ARENA.allocate(16, 8);
            seg.set(ValueLayout.JAVA_LONG, 0, v1);
            seg.set(ValueLayout.JAVA_LONG, 8, v2);
            return seg;
        }

        private static final MemorySegment IID$SEG = createGuid(4794599090190032228L, -904507111803545720L);

    }

    class $DOWNCALL extends ID3D11DeviceChild.$DOWNCALL implements ID3D11VertexShader {
        private static final VarHandle VTABLE_FUNC_VARHANDLE = ID3D11VertexShader$COM_OBJECT_LAYOUT.varHandle(
                PathElement.groupElement("vtable"),
                PathElement.dereferenceElement(),
                PathElement.sequenceElement()
        );

        private static MemorySegment vtableFunc(MemorySegment comObject, long index) {
            return (MemorySegment) VTABLE_FUNC_VARHANDLE.get(comObject, 0L, index);
        }

        protected $DOWNCALL(MemorySegment comObject) {
            super(comObject);
        }

    }

    class $UPCALL {
        private final ID3D11VertexShader javaObject;

        private $UPCALL(ID3D11VertexShader javaObject) {
            this.javaObject = javaObject;
        }

        int QueryInterface(MemorySegment thisObject, MemorySegment riid, MemorySegment ppvObject) {
            return javaObject.QueryInterface(riid, ppvObject);
        }
        int AddRef(MemorySegment thisObject) {
            return javaObject.AddRef();
        }
        int Release(MemorySegment thisObject) {
            return javaObject.Release();
        }
        void GetDevice(MemorySegment thisObject, MemorySegment ppDevice) {
            javaObject.GetDevice(ppDevice);
        }
        int GetPrivateData(MemorySegment thisObject, MemorySegment guid, MemorySegment pDataSize, MemorySegment pData) {
            return javaObject.GetPrivateData(guid, pDataSize, pData);
        }
        int SetPrivateData(MemorySegment thisObject, MemorySegment guid, int DataSize, MemorySegment pData) {
            return javaObject.SetPrivateData(guid, DataSize, pData);
        }
        int SetPrivateDataInterface(MemorySegment thisObject, MemorySegment guid, MemorySegment pData) {
            return javaObject.SetPrivateDataInterface(guid, pData);
        }
    }

    class $UPCALL_IMPL {
        private static final FunctionDescriptor[] DESCRIPTORS = createDescriptors();
        private static final MethodHandle[] HANDLES = createHandles();

        private static FunctionDescriptor[] createDescriptors() {
            var descriptors = new FunctionDescriptor[7];
            descriptors[0] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[1] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[2] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[3] = FunctionDescriptor.ofVoid(ADDRESS, ADDRESS$ADDRESS);
            descriptors[4] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
            descriptors[5] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
            descriptors[6] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            return descriptors;
        }

        private static MethodHandle[] createHandles() {
            try {
                var lookup = MethodHandles.lookup();
                var handles = new MethodHandle[7];
                handles[0] = lookup.findVirtual($UPCALL.class, "QueryInterface", DESCRIPTORS[0].toMethodType());
                handles[1] = lookup.findVirtual($UPCALL.class, "AddRef", DESCRIPTORS[1].toMethodType());
                handles[2] = lookup.findVirtual($UPCALL.class, "Release", DESCRIPTORS[2].toMethodType());
                handles[3] = lookup.findVirtual($UPCALL.class, "GetDevice", DESCRIPTORS[3].toMethodType());
                handles[4] = lookup.findVirtual($UPCALL.class, "GetPrivateData", DESCRIPTORS[4].toMethodType());
                handles[5] = lookup.findVirtual($UPCALL.class, "SetPrivateData", DESCRIPTORS[5].toMethodType());
                handles[6] = lookup.findVirtual($UPCALL.class, "SetPrivateDataInterface", DESCRIPTORS[6].toMethodType());
               return handles;
           } catch (ReflectiveOperationException e) {
               throw new RuntimeException(e);
           }
       }
   }
}
