// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.gdi;

/**
 * {@code DISPLAYCONFIG_COLOR_ENCODING} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code DISPLAYCONFIG_COLOR_ENCODING} as it is the same as the enumeration name.
 * </p>
 */
public class DISPLAYCONFIG_COLOR_ENCODING {
    /**
     * Enumeration value {@code DISPLAYCONFIG_COLOR_ENCODING_RGB}
     */
    public static final int RGB = 0;

    /**
     * Enumeration value {@code DISPLAYCONFIG_COLOR_ENCODING_YCBCR444}
     */
    public static final int YCBCR444 = 1;

    /**
     * Enumeration value {@code DISPLAYCONFIG_COLOR_ENCODING_YCBCR422}
     */
    public static final int YCBCR422 = 2;

    /**
     * Enumeration value {@code DISPLAYCONFIG_COLOR_ENCODING_YCBCR420}
     */
    public static final int YCBCR420 = 3;

    /**
     * Enumeration value {@code DISPLAYCONFIG_COLOR_ENCODING_INTENSITY}
     */
    public static final int INTENSITY = 4;


    private DISPLAYCONFIG_COLOR_ENCODING() {}
}
