// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.gdi;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

import static java.lang.foreign.ValueLayout.JAVA_INT;

/**
 * {@code MONITORINFO} structure
 * <p>
 * {@snippet lang=c :
 * struct MONITORINFO {
 *    DWORD cbSize;
 *    RECT rcMonitor;
 *    RECT rcWork;
 *    DWORD dwFlags;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-monitorinfo">MONITORINFO (Microsoft)</a>
 */
public class MONITORINFO {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("cbSize"),
        windows.win32.foundation.RECT.layout().withName("rcMonitor"),
        windows.win32.foundation.RECT.layout().withName("rcWork"),
        JAVA_INT.withName("dwFlags")
    );

    /**
     * Gets the layout of the struct {@code MONITORINFO}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code MONITORINFO} (in bytes).
     */
    public static long sizeof() {
        return 40L;
    }

    /**
     * Gets the offset of the field {@code cbSize} (in bytes).
     */
    public static long cbSize$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code cbSize} in {@code segment}.
     */
    public static int cbSize(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code cbSize} in {@code segment} to {@code value}.
     */
    public static void cbSize(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code rcMonitor} (in bytes).
     */
    public static long rcMonitor$offset() {
        return 4L;
    }

    /**
     * Gets the field {@code rcMonitor} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment rcMonitor(MemorySegment segment) {
        return segment.asSlice(4L, 16L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code rcMonitor} in {@code segment}.
     */
    public static void rcMonitor(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 4L, 16L);
    }

    /**
     * Gets the offset of the field {@code rcWork} (in bytes).
     */
    public static long rcWork$offset() {
        return 20L;
    }

    /**
     * Gets the field {@code rcWork} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment rcWork(MemorySegment segment) {
        return segment.asSlice(20L, 16L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code rcWork} in {@code segment}.
     */
    public static void rcWork(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 20L, 16L);
    }

    /**
     * Gets the offset of the field {@code dwFlags} (in bytes).
     */
    public static long dwFlags$offset() {
        return 36L;
    }

    /**
     * Gets the value of field {@code dwFlags} in {@code segment}.
     */
    public static int dwFlags(MemorySegment segment) {
        return segment.get(JAVA_INT, 36L);
    }

    /**
     * Sets the field {@code dwFlags} in {@code segment} to {@code value}.
     */
    public static void dwFlags(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 36L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code MONITORINFO}.
     * <p>
     * The field {@code cbSize} is set to the size of the allocated struct.
     * </p>
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        var segment = allocator.allocate(40L, 4L);
        cbSize(segment, 40);
        return segment;
    }

    /**
     * Gets the element with index {@code index} of the specified {@code MONITORINFO} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(40L * index, 40L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(40L * elementCount, 4L);
    }

    private MONITORINFO () {}
}
