// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d;

/**
 * {@code D3D_SRV_DIMENSION} enumeration
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_srv_dimension">D3D_SRV_DIMENSION (Microsoft)</a>
 */
public class D3D_SRV_DIMENSION {
    /**
     * Enumeration value {@code D3D_SRV_DIMENSION_UNKNOWN}
     */
    public static final int D3D_SRV_DIMENSION_UNKNOWN = 0;

    /**
     * Enumeration value {@code D3D_SRV_DIMENSION_BUFFER}
     */
    public static final int D3D_SRV_DIMENSION_BUFFER = 1;

    /**
     * Enumeration value {@code D3D_SRV_DIMENSION_TEXTURE1D}
     */
    public static final int D3D_SRV_DIMENSION_TEXTURE1D = 2;

    /**
     * Enumeration value {@code D3D_SRV_DIMENSION_TEXTURE1DARRAY}
     */
    public static final int D3D_SRV_DIMENSION_TEXTURE1DARRAY = 3;

    /**
     * Enumeration value {@code D3D_SRV_DIMENSION_TEXTURE2D}
     */
    public static final int D3D_SRV_DIMENSION_TEXTURE2D = 4;

    /**
     * Enumeration value {@code D3D_SRV_DIMENSION_TEXTURE2DARRAY}
     */
    public static final int D3D_SRV_DIMENSION_TEXTURE2DARRAY = 5;

    /**
     * Enumeration value {@code D3D_SRV_DIMENSION_TEXTURE2DMS}
     */
    public static final int D3D_SRV_DIMENSION_TEXTURE2DMS = 6;

    /**
     * Enumeration value {@code D3D_SRV_DIMENSION_TEXTURE2DMSARRAY}
     */
    public static final int D3D_SRV_DIMENSION_TEXTURE2DMSARRAY = 7;

    /**
     * Enumeration value {@code D3D_SRV_DIMENSION_TEXTURE3D}
     */
    public static final int D3D_SRV_DIMENSION_TEXTURE3D = 8;

    /**
     * Enumeration value {@code D3D_SRV_DIMENSION_TEXTURECUBE}
     */
    public static final int D3D_SRV_DIMENSION_TEXTURECUBE = 9;

    /**
     * Enumeration value {@code D3D_SRV_DIMENSION_TEXTURECUBEARRAY}
     */
    public static final int D3D_SRV_DIMENSION_TEXTURECUBEARRAY = 10;

    /**
     * Enumeration value {@code D3D_SRV_DIMENSION_BUFFEREX}
     */
    public static final int D3D_SRV_DIMENSION_BUFFEREX = 11;

    /**
     * Enumeration value {@code D3D10_SRV_DIMENSION_UNKNOWN}
     */
    public static final int D3D10_SRV_DIMENSION_UNKNOWN = 0;

    /**
     * Enumeration value {@code D3D10_SRV_DIMENSION_BUFFER}
     */
    public static final int D3D10_SRV_DIMENSION_BUFFER = 1;

    /**
     * Enumeration value {@code D3D10_SRV_DIMENSION_TEXTURE1D}
     */
    public static final int D3D10_SRV_DIMENSION_TEXTURE1D = 2;

    /**
     * Enumeration value {@code D3D10_SRV_DIMENSION_TEXTURE1DARRAY}
     */
    public static final int D3D10_SRV_DIMENSION_TEXTURE1DARRAY = 3;

    /**
     * Enumeration value {@code D3D10_SRV_DIMENSION_TEXTURE2D}
     */
    public static final int D3D10_SRV_DIMENSION_TEXTURE2D = 4;

    /**
     * Enumeration value {@code D3D10_SRV_DIMENSION_TEXTURE2DARRAY}
     */
    public static final int D3D10_SRV_DIMENSION_TEXTURE2DARRAY = 5;

    /**
     * Enumeration value {@code D3D10_SRV_DIMENSION_TEXTURE2DMS}
     */
    public static final int D3D10_SRV_DIMENSION_TEXTURE2DMS = 6;

    /**
     * Enumeration value {@code D3D10_SRV_DIMENSION_TEXTURE2DMSARRAY}
     */
    public static final int D3D10_SRV_DIMENSION_TEXTURE2DMSARRAY = 7;

    /**
     * Enumeration value {@code D3D10_SRV_DIMENSION_TEXTURE3D}
     */
    public static final int D3D10_SRV_DIMENSION_TEXTURE3D = 8;

    /**
     * Enumeration value {@code D3D10_SRV_DIMENSION_TEXTURECUBE}
     */
    public static final int D3D10_SRV_DIMENSION_TEXTURECUBE = 9;

    /**
     * Enumeration value {@code D3D10_1_SRV_DIMENSION_UNKNOWN}
     */
    public static final int D3D10_1_SRV_DIMENSION_UNKNOWN = 0;

    /**
     * Enumeration value {@code D3D10_1_SRV_DIMENSION_BUFFER}
     */
    public static final int D3D10_1_SRV_DIMENSION_BUFFER = 1;

    /**
     * Enumeration value {@code D3D10_1_SRV_DIMENSION_TEXTURE1D}
     */
    public static final int D3D10_1_SRV_DIMENSION_TEXTURE1D = 2;

    /**
     * Enumeration value {@code D3D10_1_SRV_DIMENSION_TEXTURE1DARRAY}
     */
    public static final int D3D10_1_SRV_DIMENSION_TEXTURE1DARRAY = 3;

    /**
     * Enumeration value {@code D3D10_1_SRV_DIMENSION_TEXTURE2D}
     */
    public static final int D3D10_1_SRV_DIMENSION_TEXTURE2D = 4;

    /**
     * Enumeration value {@code D3D10_1_SRV_DIMENSION_TEXTURE2DARRAY}
     */
    public static final int D3D10_1_SRV_DIMENSION_TEXTURE2DARRAY = 5;

    /**
     * Enumeration value {@code D3D10_1_SRV_DIMENSION_TEXTURE2DMS}
     */
    public static final int D3D10_1_SRV_DIMENSION_TEXTURE2DMS = 6;

    /**
     * Enumeration value {@code D3D10_1_SRV_DIMENSION_TEXTURE2DMSARRAY}
     */
    public static final int D3D10_1_SRV_DIMENSION_TEXTURE2DMSARRAY = 7;

    /**
     * Enumeration value {@code D3D10_1_SRV_DIMENSION_TEXTURE3D}
     */
    public static final int D3D10_1_SRV_DIMENSION_TEXTURE3D = 8;

    /**
     * Enumeration value {@code D3D10_1_SRV_DIMENSION_TEXTURECUBE}
     */
    public static final int D3D10_1_SRV_DIMENSION_TEXTURECUBE = 9;

    /**
     * Enumeration value {@code D3D10_1_SRV_DIMENSION_TEXTURECUBEARRAY}
     */
    public static final int D3D10_1_SRV_DIMENSION_TEXTURECUBEARRAY = 10;

    /**
     * Enumeration value {@code D3D11_SRV_DIMENSION_UNKNOWN}
     */
    public static final int D3D11_SRV_DIMENSION_UNKNOWN = 0;

    /**
     * Enumeration value {@code D3D11_SRV_DIMENSION_BUFFER}
     */
    public static final int D3D11_SRV_DIMENSION_BUFFER = 1;

    /**
     * Enumeration value {@code D3D11_SRV_DIMENSION_TEXTURE1D}
     */
    public static final int D3D11_SRV_DIMENSION_TEXTURE1D = 2;

    /**
     * Enumeration value {@code D3D11_SRV_DIMENSION_TEXTURE1DARRAY}
     */
    public static final int D3D11_SRV_DIMENSION_TEXTURE1DARRAY = 3;

    /**
     * Enumeration value {@code D3D11_SRV_DIMENSION_TEXTURE2D}
     */
    public static final int D3D11_SRV_DIMENSION_TEXTURE2D = 4;

    /**
     * Enumeration value {@code D3D11_SRV_DIMENSION_TEXTURE2DARRAY}
     */
    public static final int D3D11_SRV_DIMENSION_TEXTURE2DARRAY = 5;

    /**
     * Enumeration value {@code D3D11_SRV_DIMENSION_TEXTURE2DMS}
     */
    public static final int D3D11_SRV_DIMENSION_TEXTURE2DMS = 6;

    /**
     * Enumeration value {@code D3D11_SRV_DIMENSION_TEXTURE2DMSARRAY}
     */
    public static final int D3D11_SRV_DIMENSION_TEXTURE2DMSARRAY = 7;

    /**
     * Enumeration value {@code D3D11_SRV_DIMENSION_TEXTURE3D}
     */
    public static final int D3D11_SRV_DIMENSION_TEXTURE3D = 8;

    /**
     * Enumeration value {@code D3D11_SRV_DIMENSION_TEXTURECUBE}
     */
    public static final int D3D11_SRV_DIMENSION_TEXTURECUBE = 9;

    /**
     * Enumeration value {@code D3D11_SRV_DIMENSION_TEXTURECUBEARRAY}
     */
    public static final int D3D11_SRV_DIMENSION_TEXTURECUBEARRAY = 10;

    /**
     * Enumeration value {@code D3D11_SRV_DIMENSION_BUFFEREX}
     */
    public static final int D3D11_SRV_DIMENSION_BUFFEREX = 11;


    private D3D_SRV_DIMENSION() {}
}
