// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d;

/**
 * {@code D3D_DRIVER_TYPE} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code D3D_DRIVER_TYPE} as it is the same as the enumeration name.
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_driver_type">D3D_DRIVER_TYPE (Microsoft)</a>
 */
public class D3D_DRIVER_TYPE {
    /**
     * Enumeration value {@code D3D_DRIVER_TYPE_UNKNOWN}
     */
    public static final int UNKNOWN = 0;

    /**
     * Enumeration value {@code D3D_DRIVER_TYPE_HARDWARE}
     */
    public static final int HARDWARE = 1;

    /**
     * Enumeration value {@code D3D_DRIVER_TYPE_REFERENCE}
     */
    public static final int REFERENCE = 2;

    /**
     * Enumeration value {@code D3D_DRIVER_TYPE_NULL}
     */
    public static final int NULL = 3;

    /**
     * Enumeration value {@code D3D_DRIVER_TYPE_SOFTWARE}
     */
    public static final int SOFTWARE = 4;

    /**
     * Enumeration value {@code D3D_DRIVER_TYPE_WARP}
     */
    public static final int WARP = 5;


    private D3D_DRIVER_TYPE() {}
}
