// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d;

/**
 * {@code D3D_FEATURE_LEVEL} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code D3D_FEATURE_LEVEL} as it is the same as the enumeration name.
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_feature_level">D3D_FEATURE_LEVEL (Microsoft)</a>
 */
public class D3D_FEATURE_LEVEL {
    /**
     * Enumeration value {@code D3D_FEATURE_LEVEL_1_0_GENERIC}
     */
    public static final int _1_0_GENERIC = 256;

    /**
     * Enumeration value {@code D3D_FEATURE_LEVEL_1_0_CORE}
     */
    public static final int _1_0_CORE = 4096;

    /**
     * Enumeration value {@code D3D_FEATURE_LEVEL_9_1}
     */
    public static final int _9_1 = 37120;

    /**
     * Enumeration value {@code D3D_FEATURE_LEVEL_9_2}
     */
    public static final int _9_2 = 37376;

    /**
     * Enumeration value {@code D3D_FEATURE_LEVEL_9_3}
     */
    public static final int _9_3 = 37632;

    /**
     * Enumeration value {@code D3D_FEATURE_LEVEL_10_0}
     */
    public static final int _10_0 = 40960;

    /**
     * Enumeration value {@code D3D_FEATURE_LEVEL_10_1}
     */
    public static final int _10_1 = 41216;

    /**
     * Enumeration value {@code D3D_FEATURE_LEVEL_11_0}
     */
    public static final int _11_0 = 45056;

    /**
     * Enumeration value {@code D3D_FEATURE_LEVEL_11_1}
     */
    public static final int _11_1 = 45312;

    /**
     * Enumeration value {@code D3D_FEATURE_LEVEL_12_0}
     */
    public static final int _12_0 = 49152;

    /**
     * Enumeration value {@code D3D_FEATURE_LEVEL_12_1}
     */
    public static final int _12_1 = 49408;

    /**
     * Enumeration value {@code D3D_FEATURE_LEVEL_12_2}
     */
    public static final int _12_2 = 49664;


    private D3D_FEATURE_LEVEL() {}
}
