// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.direct3d;

import java.lang.foreign.*;
import java.lang.invoke.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code ID3DBlob} COM interface
 */
public interface ID3DBlob extends windows.win32.system.com.IUnknown {
    /**
     * {@code GetBufferPointer} COM interface method
     * <p>
     * {@snippet lang=c :
     * void* GetBufferPointer(
     * );
     * }
     * </p>
     */
    MemorySegment GetBufferPointer();

    /**
     * {@code GetBufferSize} COM interface method
     * <p>
     * {@snippet lang=c :
     * ULONG_PTR GetBufferSize(
     * );
     * }
     * </p>
     */
    long GetBufferSize();

    /**
     * Wraps the given COM object in a Java object with methods to call the COM interface functions.
     */
    static ID3DBlob wrap(MemorySegment comObject) {
        return new $DOWNCALL(comObject.reinterpret(8L));
    }

    /**
     * Gets the address layout for pointers to {@code ID3DBlob} COM interfaces.
     */
    static AddressLayout addressLayout() {
        return ID3DBlob$ADDRESS_LAYOUT;
    }

    /**
     * Interface identifier (IID) for {@code ID3DBlob} ({@code {8ba5fb08-5195-40e2-ac58-0d989c3a0102}}).
     */
    static MemorySegment iid() {
        return $IID$ID3DBlob.IID$SEG;
    }

    /**
     * Creates a COM object instance for the given Java object implementing {@code ID3DBlob}.
     */
    static MemorySegment create(ID3DBlob obj, Arena arena) {
        var unwrapper = new $UPCALL(obj);
        var vtable = arena.allocate(ADDRESS, 5);
        var linker = Linker.nativeLinker();
        for (int i = 0; i < 5; i++)
            vtable.set(ADDRESS, 8 * i, linker.upcallStub($UPCALL_IMPL.HANDLES[i].bindTo(unwrapper), $UPCALL_IMPL.DESCRIPTORS[i], arena));
        var objSegment = arena.allocate(ADDRESS);
        objSegment.set(ADDRESS, 0, vtable);
        return objSegment;
    }

    StructLayout ID3DBlob$COM_OBJECT_LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(5, ADDRESS)).withName("vtable")
    );

    AddressLayout ID3DBlob$ADDRESS_LAYOUT = ADDRESS.withTargetLayout(ID3DBlob$COM_OBJECT_LAYOUT);

    AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    AddressLayout ADDRESS$STRUCT_16_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(4));

    class $IID$ID3DBlob {
        private static final Arena ARENA = Arena.ofAuto();

        private static MemorySegment createGuid(long v1, long v2) {
            var seg = ARENA.allocate(16, 8);
            seg.set(ValueLayout.JAVA_LONG, 0, v1);
            seg.set(ValueLayout.JAVA_LONG, 8, v2);
            return seg;
        }

        private static final MemorySegment IID$SEG = createGuid(4675389065898883848L, 144461107292887212L);

    }

    class $DOWNCALL extends windows.win32.system.com.IUnknown.$DOWNCALL implements ID3DBlob {
        private static final VarHandle VTABLE_FUNC_VARHANDLE = ID3DBlob$COM_OBJECT_LAYOUT.varHandle(
                PathElement.groupElement("vtable"),
                PathElement.dereferenceElement(),
                PathElement.sequenceElement()
        );

        private static MemorySegment vtableFunc(MemorySegment comObject, long index) {
            return (MemorySegment) VTABLE_FUNC_VARHANDLE.get(comObject, 0L, index);
        }

        protected $DOWNCALL(MemorySegment comObject) {
            super(comObject);
        }

        public MemorySegment GetBufferPointer() {
            try {
                return (MemorySegment) VFUNC3$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 3), comObject);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public long GetBufferSize() {
            try {
                return (long) VFUNC4$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 4), comObject);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

    }

    class VFUNC3$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(ADDRESS, ID3DBlob$ADDRESS_LAYOUT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC4$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_LONG, ID3DBlob$ADDRESS_LAYOUT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class $UPCALL {
        private final ID3DBlob javaObject;

        private $UPCALL(ID3DBlob javaObject) {
            this.javaObject = javaObject;
        }

        int QueryInterface(MemorySegment thisObject, MemorySegment riid, MemorySegment ppvObject) {
            return javaObject.QueryInterface(riid, ppvObject);
        }
        int AddRef(MemorySegment thisObject) {
            return javaObject.AddRef();
        }
        int Release(MemorySegment thisObject) {
            return javaObject.Release();
        }
        MemorySegment GetBufferPointer(MemorySegment thisObject) {
            return javaObject.GetBufferPointer();
        }
        long GetBufferSize(MemorySegment thisObject) {
            return javaObject.GetBufferSize();
        }
    }

    class $UPCALL_IMPL {
        private static final FunctionDescriptor[] DESCRIPTORS = createDescriptors();
        private static final MethodHandle[] HANDLES = createHandles();

        private static FunctionDescriptor[] createDescriptors() {
            var descriptors = new FunctionDescriptor[5];
            descriptors[0] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[1] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[2] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[3] = FunctionDescriptor.of(ADDRESS, ADDRESS);
            descriptors[4] = FunctionDescriptor.of(JAVA_LONG, ADDRESS);
            return descriptors;
        }

        private static MethodHandle[] createHandles() {
            try {
                var lookup = MethodHandles.lookup();
                var handles = new MethodHandle[5];
                handles[0] = lookup.findVirtual($UPCALL.class, "QueryInterface", DESCRIPTORS[0].toMethodType());
                handles[1] = lookup.findVirtual($UPCALL.class, "AddRef", DESCRIPTORS[1].toMethodType());
                handles[2] = lookup.findVirtual($UPCALL.class, "Release", DESCRIPTORS[2].toMethodType());
                handles[3] = lookup.findVirtual($UPCALL.class, "GetBufferPointer", DESCRIPTORS[3].toMethodType());
                handles[4] = lookup.findVirtual($UPCALL.class, "GetBufferSize", DESCRIPTORS[4].toMethodType());
               return handles;
           } catch (ReflectiveOperationException e) {
               throw new RuntimeException(e);
           }
       }
   }
}
