// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.foundation;

import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code LUID} structure
 * <p>
 * {@snippet lang=c :
 * struct LUID {
 *    DWORD LowPart;
 *    LONG HighPart;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/ntdef/ns-ntdef-luid">LUID (Microsoft)</a>
 */
public class LUID {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("LowPart"),
        JAVA_INT.withName("HighPart")
    );

    /**
     * Gets the layout of the struct {@code LUID}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code LUID} (in bytes).
     */
    public static long sizeof() {
        return 8L;
    }

    /**
     * Gets the offset of the field {@code LowPart} (in bytes).
     */
    public static long LowPart$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code LowPart} in {@code segment}.
     */
    public static int LowPart(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code LowPart} in {@code segment} to {@code value}.
     */
    public static void LowPart(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code HighPart} (in bytes).
     */
    public static long HighPart$offset() {
        return 4L;
    }

    /**
     * Gets the value of field {@code HighPart} in {@code segment}.
     */
    public static int HighPart(MemorySegment segment) {
        return segment.get(JAVA_INT, 4L);
    }

    /**
     * Sets the field {@code HighPart} in {@code segment} to {@code value}.
     */
    public static void HighPart(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 4L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code LUID}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(8L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code LUID} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(8L * index, 8L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(8L * elementCount, 4L);
    }

    private LUID () {}
}
