// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.foundation;

/**
 * {@code WAIT_EVENT} enumeration
 */
public class WAIT_EVENT {
    /**
     * Enumeration value {@code WAIT_OBJECT_0}
     */
    public static final int WAIT_OBJECT_0 = 0;

    /**
     * Enumeration value {@code WAIT_ABANDONED}
     */
    public static final int WAIT_ABANDONED = 128;

    /**
     * Enumeration value {@code WAIT_ABANDONED_0}
     */
    public static final int WAIT_ABANDONED_0 = 128;

    /**
     * Enumeration value {@code WAIT_IO_COMPLETION}
     */
    public static final int WAIT_IO_COMPLETION = 192;

    /**
     * Enumeration value {@code WAIT_TIMEOUT}
     */
    public static final int WAIT_TIMEOUT = 258;

    /**
     * Enumeration value {@code WAIT_FAILED}
     */
    public static final int WAIT_FAILED = -1;


    private WAIT_EVENT() {}
}
