// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

import static java.lang.foreign.ValueLayout.JAVA_INT;

/**
 * {@code DISPLAYCONFIG_SOURCE_MODE} structure
 * <p>
 * {@snippet lang=c :
 * struct DISPLAYCONFIG_SOURCE_MODE {
 *    DWORD width;
 *    DWORD height;
 *    DISPLAYCONFIG_PIXELFORMAT pixelFormat;
 *    POINTL position;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_source_mode">DISPLAYCONFIG_SOURCE_MODE (Microsoft)</a>
 */
public class DISPLAYCONFIG_SOURCE_MODE {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("width"),
        JAVA_INT.withName("height"),
        JAVA_INT.withName("pixelFormat"),
        windows.win32.foundation.POINTL.layout().withName("position")
    );

    /**
     * Gets the layout of the struct {@code DISPLAYCONFIG_SOURCE_MODE}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DISPLAYCONFIG_SOURCE_MODE} (in bytes).
     */
    public static long sizeof() {
        return 20L;
    }

    /**
     * Gets the offset of the field {@code width} (in bytes).
     */
    public static long width$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code width} in {@code segment}.
     */
    public static int width(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code width} in {@code segment} to {@code value}.
     */
    public static void width(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code height} (in bytes).
     */
    public static long height$offset() {
        return 4L;
    }

    /**
     * Gets the value of field {@code height} in {@code segment}.
     */
    public static int height(MemorySegment segment) {
        return segment.get(JAVA_INT, 4L);
    }

    /**
     * Sets the field {@code height} in {@code segment} to {@code value}.
     */
    public static void height(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 4L, value);
    }

    /**
     * Gets the offset of the field {@code pixelFormat} (in bytes).
     */
    public static long pixelFormat$offset() {
        return 8L;
    }

    /**
     * Gets the value of field {@code pixelFormat} in {@code segment}.
     */
    public static int pixelFormat(MemorySegment segment) {
        return segment.get(JAVA_INT, 8L);
    }

    /**
     * Sets the field {@code pixelFormat} in {@code segment} to {@code value}.
     */
    public static void pixelFormat(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 8L, value);
    }

    /**
     * Gets the offset of the field {@code position} (in bytes).
     */
    public static long position$offset() {
        return 12L;
    }

    /**
     * Gets the field {@code position} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment position(MemorySegment segment) {
        return segment.asSlice(12L, 8L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code position} in {@code segment}.
     */
    public static void position(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 12L, 8L);
    }

    /**
     * Allocates a new memory segment for the struct {@code DISPLAYCONFIG_SOURCE_MODE}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(20L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DISPLAYCONFIG_SOURCE_MODE} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(20L * index, 20L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(20L * elementCount, 4L);
    }

    private DISPLAYCONFIG_SOURCE_MODE () {}
}
