// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

import static java.lang.foreign.ValueLayout.JAVA_INT;

/**
 * {@code DISPLAYCONFIG_MODE_INFO} structure
 * <p>
 * {@snippet lang=c :
 * struct DISPLAYCONFIG_MODE_INFO {
 *    DISPLAYCONFIG_MODE_INFO_TYPE infoType;
 *    DWORD id;
 *    LUID adapterId;
 *    union {
 *        DISPLAYCONFIG_TARGET_MODE targetMode;
 *        DISPLAYCONFIG_SOURCE_MODE sourceMode;
 *        DISPLAYCONFIG_DESKTOP_IMAGE_INFO desktopImageInfo;
 *    } Anonymous;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_mode_info">DISPLAYCONFIG_MODE_INFO (Microsoft)</a>
 */
public class DISPLAYCONFIG_MODE_INFO {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("infoType"),
        JAVA_INT.withName("id"),
        windows.win32.foundation.LUID.layout().withName("adapterId"),
        MemoryLayout.unionLayout(
            DISPLAYCONFIG_TARGET_MODE.layout().withName("targetMode"),
            DISPLAYCONFIG_SOURCE_MODE.layout().withName("sourceMode"),
            DISPLAYCONFIG_DESKTOP_IMAGE_INFO.layout().withName("desktopImageInfo")
        )
    );

    /**
     * Gets the layout of the struct {@code DISPLAYCONFIG_MODE_INFO}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DISPLAYCONFIG_MODE_INFO} (in bytes).
     */
    public static long sizeof() {
        return 64L;
    }

    /**
     * Gets the offset of the field {@code infoType} (in bytes).
     */
    public static long infoType$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code infoType} in {@code segment}.
     */
    public static int infoType(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code infoType} in {@code segment} to {@code value}.
     */
    public static void infoType(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code id} (in bytes).
     */
    public static long id$offset() {
        return 4L;
    }

    /**
     * Gets the value of field {@code id} in {@code segment}.
     */
    public static int id(MemorySegment segment) {
        return segment.get(JAVA_INT, 4L);
    }

    /**
     * Sets the field {@code id} in {@code segment} to {@code value}.
     */
    public static void id(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 4L, value);
    }

    /**
     * Gets the offset of the field {@code adapterId} (in bytes).
     */
    public static long adapterId$offset() {
        return 8L;
    }

    /**
     * Gets the field {@code adapterId} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment adapterId(MemorySegment segment) {
        return segment.asSlice(8L, 8L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code adapterId} in {@code segment}.
     */
    public static void adapterId(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 8L, 8L);
    }

    /**
     * Gets the offset of the field {@code targetMode} (in bytes).
     */
    public static long targetMode$offset() {
        return 16L;
    }

    /**
     * Gets the field {@code targetMode} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment targetMode(MemorySegment segment) {
        return segment.asSlice(16L, 48L, 8L);
    }

    /**
     * Copies {@code value} into the field {@code targetMode} in {@code segment}.
     */
    public static void targetMode(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 16L, 48L);
    }

    /**
     * Gets the offset of the field {@code sourceMode} (in bytes).
     */
    public static long sourceMode$offset() {
        return 16L;
    }

    /**
     * Gets the field {@code sourceMode} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment sourceMode(MemorySegment segment) {
        return segment.asSlice(16L, 20L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code sourceMode} in {@code segment}.
     */
    public static void sourceMode(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 16L, 20L);
    }

    /**
     * Gets the offset of the field {@code desktopImageInfo} (in bytes).
     */
    public static long desktopImageInfo$offset() {
        return 16L;
    }

    /**
     * Gets the field {@code desktopImageInfo} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment desktopImageInfo(MemorySegment segment) {
        return segment.asSlice(16L, 40L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code desktopImageInfo} in {@code segment}.
     */
    public static void desktopImageInfo(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 16L, 40L);
    }

    /**
     * Allocates a new memory segment for the struct {@code DISPLAYCONFIG_MODE_INFO}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(64L, 8L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DISPLAYCONFIG_MODE_INFO} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(64L * index, 64L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(64L * elementCount, 8L);
    }

    private DISPLAYCONFIG_MODE_INFO () {}
}
