// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

/**
 * {@code DISPLAYCONFIG_MODE_INFO_TYPE} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code DISPLAYCONFIG_MODE_INFO_TYPE} as it is the same as the enumeration name.
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/wingdi/ne-wingdi-displayconfig_mode_info_type">DISPLAYCONFIG_MODE_INFO_TYPE (Microsoft)</a>
 */
public class DISPLAYCONFIG_MODE_INFO_TYPE {
    /**
     * Enumeration value {@code DISPLAYCONFIG_MODE_INFO_TYPE_SOURCE}
     */
    public static final int SOURCE = 1;

    /**
     * Enumeration value {@code DISPLAYCONFIG_MODE_INFO_TYPE_TARGET}
     */
    public static final int TARGET = 2;

    /**
     * Enumeration value {@code DISPLAYCONFIG_MODE_INFO_TYPE_DESKTOP_IMAGE}
     */
    public static final int DESKTOP_IMAGE = 3;


    private DISPLAYCONFIG_MODE_INFO_TYPE() {}
}
