// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

/**
 * {@code DISPLAYCONFIG_PIXELFORMAT} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code DISPLAYCONFIG_PIXELFORMAT} as it is the same as the enumeration name.
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/wingdi/ne-wingdi-displayconfig_pixelformat">DISPLAYCONFIG_PIXELFORMAT (Microsoft)</a>
 */
public class DISPLAYCONFIG_PIXELFORMAT {
    /**
     * Enumeration value {@code DISPLAYCONFIG_PIXELFORMAT_8BPP}
     */
    public static final int _8BPP = 1;

    /**
     * Enumeration value {@code DISPLAYCONFIG_PIXELFORMAT_16BPP}
     */
    public static final int _16BPP = 2;

    /**
     * Enumeration value {@code DISPLAYCONFIG_PIXELFORMAT_24BPP}
     */
    public static final int _24BPP = 3;

    /**
     * Enumeration value {@code DISPLAYCONFIG_PIXELFORMAT_32BPP}
     */
    public static final int _32BPP = 4;

    /**
     * Enumeration value {@code DISPLAYCONFIG_PIXELFORMAT_NONGDI}
     */
    public static final int NONGDI = 5;


    private DISPLAYCONFIG_PIXELFORMAT() {}
}
