// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

/**
 * {@code DISPLAYCONFIG_DESKTOP_IMAGE_INFO} structure
 * <p>
 * {@snippet lang=c :
 * struct DISPLAYCONFIG_DESKTOP_IMAGE_INFO {
 *    POINTL PathSourceSize;
 *    RECTL DesktopImageRegion;
 *    RECTL DesktopImageClip;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_desktop_image_info">DISPLAYCONFIG_DESKTOP_IMAGE_INFO (Microsoft)</a>
 */
public class DISPLAYCONFIG_DESKTOP_IMAGE_INFO {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        windows.win32.foundation.POINTL.layout().withName("PathSourceSize"),
        windows.win32.foundation.RECTL.layout().withName("DesktopImageRegion"),
        windows.win32.foundation.RECTL.layout().withName("DesktopImageClip")
    );

    /**
     * Gets the layout of the struct {@code DISPLAYCONFIG_DESKTOP_IMAGE_INFO}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DISPLAYCONFIG_DESKTOP_IMAGE_INFO} (in bytes).
     */
    public static long sizeof() {
        return 40L;
    }

    /**
     * Gets the offset of the field {@code PathSourceSize} (in bytes).
     */
    public static long PathSourceSize$offset() {
        return 0L;
    }

    /**
     * Gets the field {@code PathSourceSize} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment PathSourceSize(MemorySegment segment) {
        return segment.asSlice(0L, 8L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code PathSourceSize} in {@code segment}.
     */
    public static void PathSourceSize(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 0L, 8L);
    }

    /**
     * Gets the offset of the field {@code DesktopImageRegion} (in bytes).
     */
    public static long DesktopImageRegion$offset() {
        return 8L;
    }

    /**
     * Gets the field {@code DesktopImageRegion} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment DesktopImageRegion(MemorySegment segment) {
        return segment.asSlice(8L, 16L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code DesktopImageRegion} in {@code segment}.
     */
    public static void DesktopImageRegion(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 8L, 16L);
    }

    /**
     * Gets the offset of the field {@code DesktopImageClip} (in bytes).
     */
    public static long DesktopImageClip$offset() {
        return 24L;
    }

    /**
     * Gets the field {@code DesktopImageClip} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment DesktopImageClip(MemorySegment segment) {
        return segment.asSlice(24L, 16L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code DesktopImageClip} in {@code segment}.
     */
    public static void DesktopImageClip(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 24L, 16L);
    }

    /**
     * Allocates a new memory segment for the struct {@code DISPLAYCONFIG_DESKTOP_IMAGE_INFO}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(40L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DISPLAYCONFIG_DESKTOP_IMAGE_INFO} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(40L * index, 40L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(40L * elementCount, 4L);
    }

    private DISPLAYCONFIG_DESKTOP_IMAGE_INFO () {}
}
