// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

import static java.lang.foreign.ValueLayout.JAVA_INT;

/**
 * {@code DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO} structure
 * <p>
 * {@snippet lang=c :
 * struct DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO {
 *    DISPLAYCONFIG_DEVICE_INFO_HEADER header;
 *    union {
 *        struct {
 *            DWORD _bitfield;
 *        } Anonymous;
 *        DWORD value;
 *    } Anonymous;
 *    DISPLAYCONFIG_COLOR_ENCODING colorEncoding;
 *    DWORD bitsPerColorChannel;
 * }
 * }
 * </p>
 */
public class DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        DISPLAYCONFIG_DEVICE_INFO_HEADER.layout().withName("header"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                JAVA_INT.withName("_bitfield")
            ),
            JAVA_INT.withName("value")
        ),
        JAVA_INT.withName("colorEncoding"),
        JAVA_INT.withName("bitsPerColorChannel")
    );

    /**
     * Gets the layout of the struct {@code DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO} (in bytes).
     */
    public static long sizeof() {
        return 32L;
    }

    /**
     * Gets the offset of the field {@code header} (in bytes).
     */
    public static long header$offset() {
        return 0L;
    }

    /**
     * Gets the field {@code header} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment header(MemorySegment segment) {
        return segment.asSlice(0L, 20L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code header} in {@code segment}.
     */
    public static void header(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 0L, 20L);
    }

    /**
     * Gets the offset of the field {@code _bitfield} (in bytes).
     */
    public static long _bitfield1$offset() {
        return 20L;
    }

    /**
     * Gets the value of field {@code _bitfield} in {@code segment}.
     */
    public static int _bitfield1(MemorySegment segment) {
        return segment.get(JAVA_INT, 20L);
    }

    /**
     * Sets the field {@code _bitfield} in {@code segment} to {@code value}.
     */
    public static void _bitfield1(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 20L, value);
    }

    /**
     * Gets the offset of the field {@code value} (in bytes).
     */
    public static long value$offset() {
        return 20L;
    }

    /**
     * Gets the value of field {@code value} in {@code segment}.
     */
    public static int value(MemorySegment segment) {
        return segment.get(JAVA_INT, 20L);
    }

    /**
     * Sets the field {@code value} in {@code segment} to {@code value}.
     */
    public static void value(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 20L, value);
    }

    /**
     * Gets the offset of the field {@code colorEncoding} (in bytes).
     */
    public static long colorEncoding$offset() {
        return 24L;
    }

    /**
     * Gets the value of field {@code colorEncoding} in {@code segment}.
     */
    public static int colorEncoding(MemorySegment segment) {
        return segment.get(JAVA_INT, 24L);
    }

    /**
     * Sets the field {@code colorEncoding} in {@code segment} to {@code value}.
     */
    public static void colorEncoding(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 24L, value);
    }

    /**
     * Gets the offset of the field {@code bitsPerColorChannel} (in bytes).
     */
    public static long bitsPerColorChannel$offset() {
        return 28L;
    }

    /**
     * Gets the value of field {@code bitsPerColorChannel} in {@code segment}.
     */
    public static int bitsPerColorChannel(MemorySegment segment) {
        return segment.get(JAVA_INT, 28L);
    }

    /**
     * Sets the field {@code bitsPerColorChannel} in {@code segment} to {@code value}.
     */
    public static void bitsPerColorChannel(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 28L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(32L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(32L * index, 32L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(32L * elementCount, 4L);
    }

    private DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO () {}
}
