// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

import static java.lang.foreign.ValueLayout.JAVA_INT;

/**
 * {@code DISPLAYCONFIG_SDR_WHITE_LEVEL} structure
 * <p>
 * {@snippet lang=c :
 * struct DISPLAYCONFIG_SDR_WHITE_LEVEL {
 *    DISPLAYCONFIG_DEVICE_INFO_HEADER header;
 *    DWORD SDRWhiteLevel;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_sdr_white_level">DISPLAYCONFIG_SDR_WHITE_LEVEL (Microsoft)</a>
 */
public class DISPLAYCONFIG_SDR_WHITE_LEVEL {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        DISPLAYCONFIG_DEVICE_INFO_HEADER.layout().withName("header"),
        JAVA_INT.withName("SDRWhiteLevel")
    );

    /**
     * Gets the layout of the struct {@code DISPLAYCONFIG_SDR_WHITE_LEVEL}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DISPLAYCONFIG_SDR_WHITE_LEVEL} (in bytes).
     */
    public static long sizeof() {
        return 24L;
    }

    /**
     * Gets the offset of the field {@code header} (in bytes).
     */
    public static long header$offset() {
        return 0L;
    }

    /**
     * Gets the field {@code header} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment header(MemorySegment segment) {
        return segment.asSlice(0L, 20L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code header} in {@code segment}.
     */
    public static void header(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 0L, 20L);
    }

    /**
     * Gets the offset of the field {@code SDRWhiteLevel} (in bytes).
     */
    public static long SDRWhiteLevel$offset() {
        return 20L;
    }

    /**
     * Gets the value of field {@code SDRWhiteLevel} in {@code segment}.
     */
    public static int SDRWhiteLevel(MemorySegment segment) {
        return segment.get(JAVA_INT, 20L);
    }

    /**
     * Sets the field {@code SDRWhiteLevel} in {@code segment} to {@code value}.
     */
    public static void SDRWhiteLevel(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 20L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code DISPLAYCONFIG_SDR_WHITE_LEVEL}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(24L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DISPLAYCONFIG_SDR_WHITE_LEVEL} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(24L * index, 24L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(24L * elementCount, 4L);
    }

    private DISPLAYCONFIG_SDR_WHITE_LEVEL () {}
}
