// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

/**
 * {@code DISPLAYCONFIG_DEVICE_INFO_TYPE} enumeration
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/wingdi/ne-wingdi-displayconfig_device_info_type">DISPLAYCONFIG_DEVICE_INFO_TYPE (Microsoft)</a>
 */
public class DISPLAYCONFIG_DEVICE_INFO_TYPE {
    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME = 1;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME = 2;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_PREFERRED_MODE}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_PREFERRED_MODE = 3;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_GET_ADAPTER_NAME}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_GET_ADAPTER_NAME = 4;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_SET_TARGET_PERSISTENCE}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_SET_TARGET_PERSISTENCE = 5;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_BASE_TYPE}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_BASE_TYPE = 6;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_GET_SUPPORT_VIRTUAL_RESOLUTION}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_GET_SUPPORT_VIRTUAL_RESOLUTION = 7;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_SET_SUPPORT_VIRTUAL_RESOLUTION}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_SET_SUPPORT_VIRTUAL_RESOLUTION = 8;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_GET_ADVANCED_COLOR_INFO}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_GET_ADVANCED_COLOR_INFO = 9;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_SET_ADVANCED_COLOR_STATE}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_SET_ADVANCED_COLOR_STATE = 10;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_GET_SDR_WHITE_LEVEL}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_GET_SDR_WHITE_LEVEL = 11;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_GET_MONITOR_SPECIALIZATION}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_GET_MONITOR_SPECIALIZATION = 12;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_SET_MONITOR_SPECIALIZATION}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_SET_MONITOR_SPECIALIZATION = 13;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_SET_RESERVED1}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_SET_RESERVED1 = 14;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_GET_ADVANCED_COLOR_INFO_2}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_GET_ADVANCED_COLOR_INFO_2 = 15;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_SET_HDR_STATE}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_SET_HDR_STATE = 16;

    /**
     * Enumeration value {@code DISPLAYCONFIG_DEVICE_INFO_SET_WCG_STATE}
     */
    public static final int DISPLAYCONFIG_DEVICE_INFO_SET_WCG_STATE = 17;


    private DISPLAYCONFIG_DEVICE_INFO_TYPE() {}
}
