// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

import static java.lang.foreign.ValueLayout.JAVA_SHORT;

/**
 * {@code DISPLAYCONFIG_SOURCE_DEVICE_NAME} structure
 * <p>
 * {@snippet lang=c :
 * struct DISPLAYCONFIG_SOURCE_DEVICE_NAME {
 *    DISPLAYCONFIG_DEVICE_INFO_HEADER header;
 *    WCHAR[32] viewGdiDeviceName;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_source_device_name">DISPLAYCONFIG_SOURCE_DEVICE_NAME (Microsoft)</a>
 */
public class DISPLAYCONFIG_SOURCE_DEVICE_NAME {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        DISPLAYCONFIG_DEVICE_INFO_HEADER.layout().withName("header"),
        MemoryLayout.sequenceLayout(32L, JAVA_SHORT).withName("viewGdiDeviceName")
    );

    /**
     * Gets the layout of the struct {@code DISPLAYCONFIG_SOURCE_DEVICE_NAME}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DISPLAYCONFIG_SOURCE_DEVICE_NAME} (in bytes).
     */
    public static long sizeof() {
        return 84L;
    }

    /**
     * Gets the offset of the field {@code header} (in bytes).
     */
    public static long header$offset() {
        return 0L;
    }

    /**
     * Gets the field {@code header} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment header(MemorySegment segment) {
        return segment.asSlice(0L, 20L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code header} in {@code segment}.
     */
    public static void header(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 0L, 20L);
    }

    /**
     * Gets the offset of the field {@code viewGdiDeviceName} (in bytes).
     */
    public static long viewGdiDeviceName$offset() {
        return 20L;
    }

    /**
     * Gets the field {@code viewGdiDeviceName} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment viewGdiDeviceName(MemorySegment segment) {
        return segment.asSlice(20L, 64L, 2L);
    }

    /**
     * Copies {@code value} into the field {@code viewGdiDeviceName} in {@code segment}.
     */
    public static void viewGdiDeviceName(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 20L, 64L);
    }

    /**
     * Allocates a new memory segment for the struct {@code DISPLAYCONFIG_SOURCE_DEVICE_NAME}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(84L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DISPLAYCONFIG_SOURCE_DEVICE_NAME} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(84L * index, 84L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(84L * elementCount, 4L);
    }

    private DISPLAYCONFIG_SOURCE_DEVICE_NAME () {}
}
