// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

import static java.lang.foreign.ValueLayout.JAVA_INT;

/**
 * {@code DISPLAYCONFIG_DEVICE_INFO_HEADER} structure
 * <p>
 * {@snippet lang=c :
 * struct DISPLAYCONFIG_DEVICE_INFO_HEADER {
 *    DISPLAYCONFIG_DEVICE_INFO_TYPE type;
 *    DWORD size;
 *    LUID adapterId;
 *    DWORD id;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_device_info_header">DISPLAYCONFIG_DEVICE_INFO_HEADER (Microsoft)</a>
 */
public class DISPLAYCONFIG_DEVICE_INFO_HEADER {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("size"),
        windows.win32.foundation.LUID.layout().withName("adapterId"),
        JAVA_INT.withName("id")
    );

    /**
     * Gets the layout of the struct {@code DISPLAYCONFIG_DEVICE_INFO_HEADER}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DISPLAYCONFIG_DEVICE_INFO_HEADER} (in bytes).
     */
    public static long sizeof() {
        return 20L;
    }

    /**
     * Gets the offset of the field {@code type} (in bytes).
     */
    public static long type$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code type} in {@code segment}.
     */
    public static int type(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code type} in {@code segment} to {@code value}.
     */
    public static void type(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code size} (in bytes).
     */
    public static long size$offset() {
        return 4L;
    }

    /**
     * Gets the value of field {@code size} in {@code segment}.
     */
    public static int size(MemorySegment segment) {
        return segment.get(JAVA_INT, 4L);
    }

    /**
     * Sets the field {@code size} in {@code segment} to {@code value}.
     */
    public static void size(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 4L, value);
    }

    /**
     * Gets the offset of the field {@code adapterId} (in bytes).
     */
    public static long adapterId$offset() {
        return 8L;
    }

    /**
     * Gets the field {@code adapterId} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment adapterId(MemorySegment segment) {
        return segment.asSlice(8L, 8L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code adapterId} in {@code segment}.
     */
    public static void adapterId(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 8L, 8L);
    }

    /**
     * Gets the offset of the field {@code id} (in bytes).
     */
    public static long id$offset() {
        return 16L;
    }

    /**
     * Gets the value of field {@code id} in {@code segment}.
     */
    public static int id(MemorySegment segment) {
        return segment.get(JAVA_INT, 16L);
    }

    /**
     * Sets the field {@code id} in {@code segment} to {@code value}.
     */
    public static void id(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 16L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code DISPLAYCONFIG_DEVICE_INFO_HEADER}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(20L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DISPLAYCONFIG_DEVICE_INFO_HEADER} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(20L * index, 20L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(20L * elementCount, 4L);
    }

    private DISPLAYCONFIG_DEVICE_INFO_HEADER () {}
}
