// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

import static java.lang.foreign.ValueLayout.JAVA_INT;

/**
 * {@code DISPLAYCONFIG_PATH_TARGET_INFO} structure
 * <p>
 * {@snippet lang=c :
 * struct DISPLAYCONFIG_PATH_TARGET_INFO {
 *    LUID adapterId;
 *    DWORD id;
 *    union {
 *        DWORD modeInfoIdx;
 *        struct {
 *            DWORD _bitfield;
 *        } Anonymous;
 *    } Anonymous;
 *    DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY outputTechnology;
 *    DISPLAYCONFIG_ROTATION rotation;
 *    DISPLAYCONFIG_SCALING scaling;
 *    DISPLAYCONFIG_RATIONAL refreshRate;
 *    DISPLAYCONFIG_SCANLINE_ORDERING scanLineOrdering;
 *    BOOL targetAvailable;
 *    DWORD statusFlags;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-displayconfig_path_target_info">DISPLAYCONFIG_PATH_TARGET_INFO (Microsoft)</a>
 */
public class DISPLAYCONFIG_PATH_TARGET_INFO {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        windows.win32.foundation.LUID.layout().withName("adapterId"),
        JAVA_INT.withName("id"),
        MemoryLayout.unionLayout(
            JAVA_INT.withName("modeInfoIdx"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("_bitfield")
            )
        ),
        JAVA_INT.withName("outputTechnology"),
        JAVA_INT.withName("rotation"),
        JAVA_INT.withName("scaling"),
        DISPLAYCONFIG_RATIONAL.layout().withName("refreshRate"),
        JAVA_INT.withName("scanLineOrdering"),
        JAVA_INT.withName("targetAvailable"),
        JAVA_INT.withName("statusFlags")
    );

    /**
     * Gets the layout of the struct {@code DISPLAYCONFIG_PATH_TARGET_INFO}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DISPLAYCONFIG_PATH_TARGET_INFO} (in bytes).
     */
    public static long sizeof() {
        return 48L;
    }

    /**
     * Gets the offset of the field {@code adapterId} (in bytes).
     */
    public static long adapterId$offset() {
        return 0L;
    }

    /**
     * Gets the field {@code adapterId} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment adapterId(MemorySegment segment) {
        return segment.asSlice(0L, 8L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code adapterId} in {@code segment}.
     */
    public static void adapterId(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 0L, 8L);
    }

    /**
     * Gets the offset of the field {@code id} (in bytes).
     */
    public static long id$offset() {
        return 8L;
    }

    /**
     * Gets the value of field {@code id} in {@code segment}.
     */
    public static int id(MemorySegment segment) {
        return segment.get(JAVA_INT, 8L);
    }

    /**
     * Sets the field {@code id} in {@code segment} to {@code value}.
     */
    public static void id(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 8L, value);
    }

    /**
     * Gets the offset of the field {@code modeInfoIdx} (in bytes).
     */
    public static long modeInfoIdx$offset() {
        return 12L;
    }

    /**
     * Gets the value of field {@code modeInfoIdx} in {@code segment}.
     */
    public static int modeInfoIdx(MemorySegment segment) {
        return segment.get(JAVA_INT, 12L);
    }

    /**
     * Sets the field {@code modeInfoIdx} in {@code segment} to {@code value}.
     */
    public static void modeInfoIdx(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 12L, value);
    }

    /**
     * Gets the offset of the field {@code _bitfield} (in bytes).
     */
    public static long _bitfield1$offset() {
        return 12L;
    }

    /**
     * Gets the value of field {@code _bitfield} in {@code segment}.
     */
    public static int _bitfield1(MemorySegment segment) {
        return segment.get(JAVA_INT, 12L);
    }

    /**
     * Sets the field {@code _bitfield} in {@code segment} to {@code value}.
     */
    public static void _bitfield1(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 12L, value);
    }

    /**
     * Gets the offset of the field {@code outputTechnology} (in bytes).
     */
    public static long outputTechnology$offset() {
        return 16L;
    }

    /**
     * Gets the value of field {@code outputTechnology} in {@code segment}.
     */
    public static int outputTechnology(MemorySegment segment) {
        return segment.get(JAVA_INT, 16L);
    }

    /**
     * Sets the field {@code outputTechnology} in {@code segment} to {@code value}.
     */
    public static void outputTechnology(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 16L, value);
    }

    /**
     * Gets the offset of the field {@code rotation} (in bytes).
     */
    public static long rotation$offset() {
        return 20L;
    }

    /**
     * Gets the value of field {@code rotation} in {@code segment}.
     */
    public static int rotation(MemorySegment segment) {
        return segment.get(JAVA_INT, 20L);
    }

    /**
     * Sets the field {@code rotation} in {@code segment} to {@code value}.
     */
    public static void rotation(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 20L, value);
    }

    /**
     * Gets the offset of the field {@code scaling} (in bytes).
     */
    public static long scaling$offset() {
        return 24L;
    }

    /**
     * Gets the value of field {@code scaling} in {@code segment}.
     */
    public static int scaling(MemorySegment segment) {
        return segment.get(JAVA_INT, 24L);
    }

    /**
     * Sets the field {@code scaling} in {@code segment} to {@code value}.
     */
    public static void scaling(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 24L, value);
    }

    /**
     * Gets the offset of the field {@code refreshRate} (in bytes).
     */
    public static long refreshRate$offset() {
        return 28L;
    }

    /**
     * Gets the field {@code refreshRate} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment refreshRate(MemorySegment segment) {
        return segment.asSlice(28L, 8L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code refreshRate} in {@code segment}.
     */
    public static void refreshRate(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 28L, 8L);
    }

    /**
     * Gets the offset of the field {@code scanLineOrdering} (in bytes).
     */
    public static long scanLineOrdering$offset() {
        return 36L;
    }

    /**
     * Gets the value of field {@code scanLineOrdering} in {@code segment}.
     */
    public static int scanLineOrdering(MemorySegment segment) {
        return segment.get(JAVA_INT, 36L);
    }

    /**
     * Sets the field {@code scanLineOrdering} in {@code segment} to {@code value}.
     */
    public static void scanLineOrdering(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 36L, value);
    }

    /**
     * Gets the offset of the field {@code targetAvailable} (in bytes).
     */
    public static long targetAvailable$offset() {
        return 40L;
    }

    /**
     * Gets the value of field {@code targetAvailable} in {@code segment}.
     */
    public static int targetAvailable(MemorySegment segment) {
        return segment.get(JAVA_INT, 40L);
    }

    /**
     * Sets the field {@code targetAvailable} in {@code segment} to {@code value}.
     */
    public static void targetAvailable(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 40L, value);
    }

    /**
     * Gets the offset of the field {@code statusFlags} (in bytes).
     */
    public static long statusFlags$offset() {
        return 44L;
    }

    /**
     * Gets the value of field {@code statusFlags} in {@code segment}.
     */
    public static int statusFlags(MemorySegment segment) {
        return segment.get(JAVA_INT, 44L);
    }

    /**
     * Sets the field {@code statusFlags} in {@code segment} to {@code value}.
     */
    public static void statusFlags(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 44L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code DISPLAYCONFIG_PATH_TARGET_INFO}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(48L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DISPLAYCONFIG_PATH_TARGET_INFO} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(48L * index, 48L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(48L * elementCount, 4L);
    }

    private DISPLAYCONFIG_PATH_TARGET_INFO () {}
}
