// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

/**
 * {@code DISPLAYCONFIG_TOPOLOGY_ID} enumeration
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/wingdi/ne-wingdi-displayconfig_topology_id">DISPLAYCONFIG_TOPOLOGY_ID (Microsoft)</a>
 */
public class DISPLAYCONFIG_TOPOLOGY_ID {
    /**
     * Enumeration value {@code DISPLAYCONFIG_TOPOLOGY_INTERNAL}
     */
    public static final int DISPLAYCONFIG_TOPOLOGY_INTERNAL = 1;

    /**
     * Enumeration value {@code DISPLAYCONFIG_TOPOLOGY_CLONE}
     */
    public static final int DISPLAYCONFIG_TOPOLOGY_CLONE = 2;

    /**
     * Enumeration value {@code DISPLAYCONFIG_TOPOLOGY_EXTEND}
     */
    public static final int DISPLAYCONFIG_TOPOLOGY_EXTEND = 4;

    /**
     * Enumeration value {@code DISPLAYCONFIG_TOPOLOGY_EXTERNAL}
     */
    public static final int DISPLAYCONFIG_TOPOLOGY_EXTERNAL = 8;


    private DISPLAYCONFIG_TOPOLOGY_ID() {}
}
