// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.devices.display;

/**
 * {@code QUERY_DISPLAY_CONFIG_FLAGS} enumeration flags
 */
public class QUERY_DISPLAY_CONFIG_FLAGS {
    /**
     * Enumeration value {@code QDC_ALL_PATHS}
     */
    public static final int QDC_ALL_PATHS = 1;

    /**
     * Enumeration value {@code QDC_ONLY_ACTIVE_PATHS}
     */
    public static final int QDC_ONLY_ACTIVE_PATHS = 2;

    /**
     * Enumeration value {@code QDC_DATABASE_CURRENT}
     */
    public static final int QDC_DATABASE_CURRENT = 4;

    /**
     * Enumeration value {@code QDC_VIRTUAL_MODE_AWARE}
     */
    public static final int QDC_VIRTUAL_MODE_AWARE = 16;

    /**
     * Enumeration value {@code QDC_INCLUDE_HMD}
     */
    public static final int QDC_INCLUDE_HMD = 32;

    /**
     * Enumeration value {@code QDC_VIRTUAL_REFRESH_RATE_AWARE}
     */
    public static final int QDC_VIRTUAL_REFRESH_RATE_AWARE = 64;


    private QUERY_DISPLAY_CONFIG_FLAGS() {}
}
