// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.system.diagnostics.debug;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.*;

/**
 * Functions of namespace {@code Windows.Win32.System.Diagnostics.Debug}
 */
public class Apis {

    

    private static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup("KERNEL32.dll", Arena.global());
    private static final Linker LINKER = Linker.nativeLinker();
    private static final Linker.Option LAST_ERROR_STATE = Linker.Option.captureCallState("GetLastError");
    private static final AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    private static final AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));

    private static class FormatMessageW$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT, ADDRESS$UNKNOWN_SIZE, JAVA_INT, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = LINKER.downcallHandle(SYMBOL_LOOKUP.findOrThrow("FormatMessageW"), DESC, LAST_ERROR_STATE);
    }

    /**
     * Gets the function descriptor for {@code FormatMessageW}
     * <p>
     * The additional first parameter takes a memory segment to capture the call state (replacement for {@code GetLastError()}).
     * </p>
     */
    public static FunctionDescriptor FormatMessageW$descriptor() {
        return FormatMessageW$IMPL.DESC;
    }

    /**
     * Gets the method handle for {@code FormatMessageW}
     */
    public static MethodHandle FormatMessageW$handle() {
        return FormatMessageW$IMPL.HANDLE;
    }

    /**
     * {@code FormatMessageW} function
     * <p>
     * {@snippet lang=c :
     * DWORD FormatMessageW(
     *     FORMAT_MESSAGE_OPTIONS dwFlags,
     *     void* lpSource,
     *     DWORD dwMessageId,
     *     DWORD dwLanguageId,
     *     PWSTR lpBuffer,
     *     DWORD nSize,
     *     INT8** Arguments
     * );
     * }
     * </p>
     * <p>
     * The additional first parameter takes a memory segment to capture the call state (replacement for {@code GetLastError()}).
     * </p>
     *
     * @see <a href="https://learn.microsoft.com/windows/win32/api/winbase/nf-winbase-formatmessagew">FormatMessageW (Microsoft)</a>
     */
    public static int FormatMessageW(MemorySegment lastErrorState, int dwFlags, MemorySegment lpSource, int dwMessageId, int dwLanguageId, MemorySegment lpBuffer, int nSize, MemorySegment Arguments) {
        try {
            return (int) FormatMessageW$IMPL.HANDLE.invokeExact(lastErrorState, dwFlags, lpSource, dwMessageId, dwLanguageId, lpBuffer, nSize, Arguments);
        } catch (Throwable ex) {
            throw new RuntimeException(ex);
        }
    }

}
