// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.system.diagnostics.debug;

/**
 * {@code FORMAT_MESSAGE_OPTIONS} enumeration flags
 */
public class FORMAT_MESSAGE_OPTIONS {
    /**
     * Enumeration value {@code FORMAT_MESSAGE_ALLOCATE_BUFFER}
     */
    public static final int FORMAT_MESSAGE_ALLOCATE_BUFFER = 256;

    /**
     * Enumeration value {@code FORMAT_MESSAGE_ARGUMENT_ARRAY}
     */
    public static final int FORMAT_MESSAGE_ARGUMENT_ARRAY = 8192;

    /**
     * Enumeration value {@code FORMAT_MESSAGE_FROM_HMODULE}
     */
    public static final int FORMAT_MESSAGE_FROM_HMODULE = 2048;

    /**
     * Enumeration value {@code FORMAT_MESSAGE_FROM_STRING}
     */
    public static final int FORMAT_MESSAGE_FROM_STRING = 1024;

    /**
     * Enumeration value {@code FORMAT_MESSAGE_FROM_SYSTEM}
     */
    public static final int FORMAT_MESSAGE_FROM_SYSTEM = 4096;

    /**
     * Enumeration value {@code FORMAT_MESSAGE_IGNORE_INSERTS}
     */
    public static final int FORMAT_MESSAGE_IGNORE_INSERTS = 512;


    private FORMAT_MESSAGE_OPTIONS() {}
}
