// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code DXGI_MAPPED_RECT} structure
 * <p>
 * {@snippet lang=c :
 * struct DXGI_MAPPED_RECT {
 *    LONG Pitch;
 *    BYTE* pBits;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi/ns-dxgi-dxgi_mapped_rect">DXGI_MAPPED_RECT (Microsoft)</a>
 */
public class DXGI_MAPPED_RECT {
    private static final AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("Pitch"),
        MemoryLayout.paddingLayout(4),
        ADDRESS$UNKNOWN_SIZE.withName("pBits")
    );

    /**
     * Gets the layout of the struct {@code DXGI_MAPPED_RECT}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DXGI_MAPPED_RECT} (in bytes).
     */
    public static long sizeof() {
        return 16L;
    }

    /**
     * Gets the offset of the field {@code Pitch} (in bytes).
     */
    public static long Pitch$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code Pitch} in {@code segment}.
     */
    public static int Pitch(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code Pitch} in {@code segment} to {@code value}.
     */
    public static void Pitch(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code pBits} (in bytes).
     */
    public static long pBits$offset() {
        return 8L;
    }

    /**
     * Gets the value of field {@code pBits} in {@code segment}.
     */
    public static MemorySegment pBits(MemorySegment segment) {
        return segment.get(ADDRESS$UNKNOWN_SIZE, 8L);
    }

    /**
     * Sets the field {@code pBits} in {@code segment} to {@code value}.
     */
    public static void pBits(MemorySegment segment, MemorySegment value) {
        segment.set(ADDRESS$UNKNOWN_SIZE, 8L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code DXGI_MAPPED_RECT}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(16L, 8L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DXGI_MAPPED_RECT} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(16L * index, 16L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(16L * elementCount, 8L);
    }

    private DXGI_MAPPED_RECT () {}
}
