// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

/**
 * {@code DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAGS} enumeration flags
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi1_6/ne-dxgi1_6-dxgi_hardware_composition_support_flags">DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAGS (Microsoft)</a>
 */
public class DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAGS {
    /**
     * Enumeration value {@code DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAG_FULLSCREEN}
     */
    public static final int DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAG_FULLSCREEN = 1;

    /**
     * Enumeration value {@code DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAG_WINDOWED}
     */
    public static final int DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAG_WINDOWED = 2;

    /**
     * Enumeration value {@code DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAG_CURSOR_STRETCHED}
     */
    public static final int DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAG_CURSOR_STRETCHED = 4;


    private DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAGS() {}
}
