// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

/**
 * {@code DXGI_PRESENT} enumeration flags
 * <p>
 * The enumeration member names do not include the prefix {@code DXGI_PRESENT} as it is the same as the enumeration name.
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/direct3ddxgi/dxgi-present">DXGI_PRESENT (Microsoft)</a>
 */
public class DXGI_PRESENT {
    /**
     * Enumeration value {@code DXGI_PRESENT_TEST}
     */
    public static final int TEST = 1;

    /**
     * Enumeration value {@code DXGI_PRESENT_DO_NOT_SEQUENCE}
     */
    public static final int DO_NOT_SEQUENCE = 2;

    /**
     * Enumeration value {@code DXGI_PRESENT_RESTART}
     */
    public static final int RESTART = 4;

    /**
     * Enumeration value {@code DXGI_PRESENT_DO_NOT_WAIT}
     */
    public static final int DO_NOT_WAIT = 8;

    /**
     * Enumeration value {@code DXGI_PRESENT_STEREO_PREFER_RIGHT}
     */
    public static final int STEREO_PREFER_RIGHT = 16;

    /**
     * Enumeration value {@code DXGI_PRESENT_STEREO_TEMPORARY_MONO}
     */
    public static final int STEREO_TEMPORARY_MONO = 32;

    /**
     * Enumeration value {@code DXGI_PRESENT_RESTRICT_TO_OUTPUT}
     */
    public static final int RESTRICT_TO_OUTPUT = 64;

    /**
     * Enumeration value {@code DXGI_PRESENT_USE_DURATION}
     */
    public static final int USE_DURATION = 256;

    /**
     * Enumeration value {@code DXGI_PRESENT_ALLOW_TEARING}
     */
    public static final int ALLOW_TEARING = 512;


    private DXGI_PRESENT() {}
}
