// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

import static java.lang.foreign.ValueLayout.JAVA_INT;

/**
 * {@code DXGI_OUTDUPL_POINTER_POSITION} structure
 * <p>
 * {@snippet lang=c :
 * struct DXGI_OUTDUPL_POINTER_POSITION {
 *    POINT Position;
 *    BOOL Visible;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi1_2/ns-dxgi1_2-dxgi_outdupl_pointer_position">DXGI_OUTDUPL_POINTER_POSITION (Microsoft)</a>
 */
public class DXGI_OUTDUPL_POINTER_POSITION {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        windows.win32.foundation.POINT.layout().withName("Position"),
        JAVA_INT.withName("Visible")
    );

    /**
     * Gets the layout of the struct {@code DXGI_OUTDUPL_POINTER_POSITION}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DXGI_OUTDUPL_POINTER_POSITION} (in bytes).
     */
    public static long sizeof() {
        return 12L;
    }

    /**
     * Gets the offset of the field {@code Position} (in bytes).
     */
    public static long Position$offset() {
        return 0L;
    }

    /**
     * Gets the field {@code Position} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment Position(MemorySegment segment) {
        return segment.asSlice(0L, 8L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code Position} in {@code segment}.
     */
    public static void Position(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 0L, 8L);
    }

    /**
     * Gets the offset of the field {@code Visible} (in bytes).
     */
    public static long Visible$offset() {
        return 8L;
    }

    /**
     * Gets the value of field {@code Visible} in {@code segment}.
     */
    public static int Visible(MemorySegment segment) {
        return segment.get(JAVA_INT, 8L);
    }

    /**
     * Sets the field {@code Visible} in {@code segment} to {@code value}.
     */
    public static void Visible(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 8L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code DXGI_OUTDUPL_POINTER_POSITION}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(12L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DXGI_OUTDUPL_POINTER_POSITION} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(12L * index, 12L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(12L * elementCount, 4L);
    }

    private DXGI_OUTDUPL_POINTER_POSITION () {}
}
