// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code DXGI_SWAP_CHAIN_FULLSCREEN_DESC} structure
 * <p>
 * {@snippet lang=c :
 * struct DXGI_SWAP_CHAIN_FULLSCREEN_DESC {
 *    DXGI_RATIONAL RefreshRate;
 *    DXGI_MODE_SCANLINE_ORDER ScanlineOrdering;
 *    DXGI_MODE_SCALING Scaling;
 *    BOOL Windowed;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi1_2/ns-dxgi1_2-dxgi_swap_chain_fullscreen_desc">DXGI_SWAP_CHAIN_FULLSCREEN_DESC (Microsoft)</a>
 */
public class DXGI_SWAP_CHAIN_FULLSCREEN_DESC {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        windows.win32.graphics.dxgi.common.DXGI_RATIONAL.layout().withName("RefreshRate"),
        JAVA_INT.withName("ScanlineOrdering"),
        JAVA_INT.withName("Scaling"),
        JAVA_INT.withName("Windowed")
    );

    /**
     * Gets the layout of the struct {@code DXGI_SWAP_CHAIN_FULLSCREEN_DESC}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DXGI_SWAP_CHAIN_FULLSCREEN_DESC} (in bytes).
     */
    public static long sizeof() {
        return 20L;
    }

    /**
     * Gets the offset of the field {@code RefreshRate} (in bytes).
     */
    public static long RefreshRate$offset() {
        return 0L;
    }

    /**
     * Gets the field {@code RefreshRate} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment RefreshRate(MemorySegment segment) {
        return segment.asSlice(0L, 8L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code RefreshRate} in {@code segment}.
     */
    public static void RefreshRate(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 0L, 8L);
    }

    /**
     * Gets the offset of the field {@code ScanlineOrdering} (in bytes).
     */
    public static long ScanlineOrdering$offset() {
        return 8L;
    }

    /**
     * Gets the value of field {@code ScanlineOrdering} in {@code segment}.
     */
    public static int ScanlineOrdering(MemorySegment segment) {
        return segment.get(JAVA_INT, 8L);
    }

    /**
     * Sets the field {@code ScanlineOrdering} in {@code segment} to {@code value}.
     */
    public static void ScanlineOrdering(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 8L, value);
    }

    /**
     * Gets the offset of the field {@code Scaling} (in bytes).
     */
    public static long Scaling$offset() {
        return 12L;
    }

    /**
     * Gets the value of field {@code Scaling} in {@code segment}.
     */
    public static int Scaling(MemorySegment segment) {
        return segment.get(JAVA_INT, 12L);
    }

    /**
     * Sets the field {@code Scaling} in {@code segment} to {@code value}.
     */
    public static void Scaling(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 12L, value);
    }

    /**
     * Gets the offset of the field {@code Windowed} (in bytes).
     */
    public static long Windowed$offset() {
        return 16L;
    }

    /**
     * Gets the value of field {@code Windowed} in {@code segment}.
     */
    public static int Windowed(MemorySegment segment) {
        return segment.get(JAVA_INT, 16L);
    }

    /**
     * Sets the field {@code Windowed} in {@code segment} to {@code value}.
     */
    public static void Windowed(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 16L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code DXGI_SWAP_CHAIN_FULLSCREEN_DESC}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(20L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DXGI_SWAP_CHAIN_FULLSCREEN_DESC} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(20L * index, 20L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(20L * elementCount, 4L);
    }

    private DXGI_SWAP_CHAIN_FULLSCREEN_DESC () {}
}
