// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

/**
 * {@code DXGI_SWAP_EFFECT} enumeration
 * <p>
 * The enumeration member names do not include the prefix {@code DXGI_SWAP_EFFECT} as it is the same as the enumeration name.
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi/ne-dxgi-dxgi_swap_effect">DXGI_SWAP_EFFECT (Microsoft)</a>
 */
public class DXGI_SWAP_EFFECT {
    /**
     * Enumeration value {@code DXGI_SWAP_EFFECT_DISCARD}
     */
    public static final int DISCARD = 0;

    /**
     * Enumeration value {@code DXGI_SWAP_EFFECT_SEQUENTIAL}
     */
    public static final int SEQUENTIAL = 1;

    /**
     * Enumeration value {@code DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL}
     */
    public static final int FLIP_SEQUENTIAL = 3;

    /**
     * Enumeration value {@code DXGI_SWAP_EFFECT_FLIP_DISCARD}
     */
    public static final int FLIP_DISCARD = 4;


    private DXGI_SWAP_EFFECT() {}
}
