// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

import java.lang.foreign.GroupLayout;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * {@code DXGI_FRAME_STATISTICS} structure
 * <p>
 * {@snippet lang=c :
 * struct DXGI_FRAME_STATISTICS {
 *    DWORD PresentCount;
 *    DWORD PresentRefreshCount;
 *    DWORD SyncRefreshCount;
 *    LONGLONG SyncQPCTime;
 *    LONGLONG SyncGPUTime;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi/ns-dxgi-dxgi_frame_statistics">DXGI_FRAME_STATISTICS (Microsoft)</a>
 */
public class DXGI_FRAME_STATISTICS {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("PresentCount"),
        JAVA_INT.withName("PresentRefreshCount"),
        JAVA_INT.withName("SyncRefreshCount"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("SyncQPCTime"),
        JAVA_LONG.withName("SyncGPUTime")
    );

    /**
     * Gets the layout of the struct {@code DXGI_FRAME_STATISTICS}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DXGI_FRAME_STATISTICS} (in bytes).
     */
    public static long sizeof() {
        return 32L;
    }

    /**
     * Gets the offset of the field {@code PresentCount} (in bytes).
     */
    public static long PresentCount$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code PresentCount} in {@code segment}.
     */
    public static int PresentCount(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code PresentCount} in {@code segment} to {@code value}.
     */
    public static void PresentCount(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code PresentRefreshCount} (in bytes).
     */
    public static long PresentRefreshCount$offset() {
        return 4L;
    }

    /**
     * Gets the value of field {@code PresentRefreshCount} in {@code segment}.
     */
    public static int PresentRefreshCount(MemorySegment segment) {
        return segment.get(JAVA_INT, 4L);
    }

    /**
     * Sets the field {@code PresentRefreshCount} in {@code segment} to {@code value}.
     */
    public static void PresentRefreshCount(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 4L, value);
    }

    /**
     * Gets the offset of the field {@code SyncRefreshCount} (in bytes).
     */
    public static long SyncRefreshCount$offset() {
        return 8L;
    }

    /**
     * Gets the value of field {@code SyncRefreshCount} in {@code segment}.
     */
    public static int SyncRefreshCount(MemorySegment segment) {
        return segment.get(JAVA_INT, 8L);
    }

    /**
     * Sets the field {@code SyncRefreshCount} in {@code segment} to {@code value}.
     */
    public static void SyncRefreshCount(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 8L, value);
    }

    /**
     * Gets the offset of the field {@code SyncQPCTime} (in bytes).
     */
    public static long SyncQPCTime$offset() {
        return 16L;
    }

    /**
     * Gets the value of field {@code SyncQPCTime} in {@code segment}.
     */
    public static long SyncQPCTime(MemorySegment segment) {
        return segment.get(JAVA_LONG, 16L);
    }

    /**
     * Sets the field {@code SyncQPCTime} in {@code segment} to {@code value}.
     */
    public static void SyncQPCTime(MemorySegment segment, long value) {
        segment.set(JAVA_LONG, 16L, value);
    }

    /**
     * Gets the offset of the field {@code SyncGPUTime} (in bytes).
     */
    public static long SyncGPUTime$offset() {
        return 24L;
    }

    /**
     * Gets the value of field {@code SyncGPUTime} in {@code segment}.
     */
    public static long SyncGPUTime(MemorySegment segment) {
        return segment.get(JAVA_LONG, 24L);
    }

    /**
     * Sets the field {@code SyncGPUTime} in {@code segment} to {@code value}.
     */
    public static void SyncGPUTime(MemorySegment segment, long value) {
        segment.set(JAVA_LONG, 24L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code DXGI_FRAME_STATISTICS}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(32L, 8L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DXGI_FRAME_STATISTICS} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(32L * index, 32L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(32L * elementCount, 8L);
    }

    private DXGI_FRAME_STATISTICS () {}
}
