// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

/**
 * {@code DXGI_OVERLAY_SUPPORT_FLAG} enumeration flags
 * <p>
 * The enumeration member names do not include the prefix {@code DXGI_OVERLAY_SUPPORT_FLAG} as it is the same as the enumeration name.
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi1_3/ne-dxgi1_3-dxgi_overlay_support_flag">DXGI_OVERLAY_SUPPORT_FLAG (Microsoft)</a>
 */
public class DXGI_OVERLAY_SUPPORT_FLAG {
    /**
     * Enumeration value {@code DXGI_OVERLAY_SUPPORT_FLAG_DIRECT}
     */
    public static final int DIRECT = 1;

    /**
     * Enumeration value {@code DXGI_OVERLAY_SUPPORT_FLAG_SCALING}
     */
    public static final int SCALING = 2;


    private DXGI_OVERLAY_SUPPORT_FLAG() {}
}
