// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code DXGI_SWAP_CHAIN_DESC} structure
 * <p>
 * {@snippet lang=c :
 * struct DXGI_SWAP_CHAIN_DESC {
 *    DXGI_MODE_DESC BufferDesc;
 *    DXGI_SAMPLE_DESC SampleDesc;
 *    DXGI_USAGE BufferUsage;
 *    DWORD BufferCount;
 *    HWND OutputWindow;
 *    BOOL Windowed;
 *    DXGI_SWAP_EFFECT SwapEffect;
 *    DWORD Flags;
 * }
 * }
 * </p>
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi/ns-dxgi-dxgi_swap_chain_desc">DXGI_SWAP_CHAIN_DESC (Microsoft)</a>
 */
public class DXGI_SWAP_CHAIN_DESC {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        windows.win32.graphics.dxgi.common.DXGI_MODE_DESC.layout().withName("BufferDesc"),
        windows.win32.graphics.dxgi.common.DXGI_SAMPLE_DESC.layout().withName("SampleDesc"),
        JAVA_INT.withName("BufferUsage"),
        JAVA_INT.withName("BufferCount"),
        MemoryLayout.paddingLayout(4),
        ADDRESS.withName("OutputWindow"),
        JAVA_INT.withName("Windowed"),
        JAVA_INT.withName("SwapEffect"),
        JAVA_INT.withName("Flags"),
        MemoryLayout.paddingLayout(4)
    );

    /**
     * Gets the layout of the struct {@code DXGI_SWAP_CHAIN_DESC}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code DXGI_SWAP_CHAIN_DESC} (in bytes).
     */
    public static long sizeof() {
        return 72L;
    }

    /**
     * Gets the offset of the field {@code BufferDesc} (in bytes).
     */
    public static long BufferDesc$offset() {
        return 0L;
    }

    /**
     * Gets the field {@code BufferDesc} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment BufferDesc(MemorySegment segment) {
        return segment.asSlice(0L, 28L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code BufferDesc} in {@code segment}.
     */
    public static void BufferDesc(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 0L, 28L);
    }

    /**
     * Gets the offset of the field {@code SampleDesc} (in bytes).
     */
    public static long SampleDesc$offset() {
        return 28L;
    }

    /**
     * Gets the field {@code SampleDesc} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment SampleDesc(MemorySegment segment) {
        return segment.asSlice(28L, 8L, 4L);
    }

    /**
     * Copies {@code value} into the field {@code SampleDesc} in {@code segment}.
     */
    public static void SampleDesc(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 28L, 8L);
    }

    /**
     * Gets the offset of the field {@code BufferUsage} (in bytes).
     */
    public static long BufferUsage$offset() {
        return 36L;
    }

    /**
     * Gets the value of field {@code BufferUsage} in {@code segment}.
     */
    public static int BufferUsage(MemorySegment segment) {
        return segment.get(JAVA_INT, 36L);
    }

    /**
     * Sets the field {@code BufferUsage} in {@code segment} to {@code value}.
     */
    public static void BufferUsage(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 36L, value);
    }

    /**
     * Gets the offset of the field {@code BufferCount} (in bytes).
     */
    public static long BufferCount$offset() {
        return 40L;
    }

    /**
     * Gets the value of field {@code BufferCount} in {@code segment}.
     */
    public static int BufferCount(MemorySegment segment) {
        return segment.get(JAVA_INT, 40L);
    }

    /**
     * Sets the field {@code BufferCount} in {@code segment} to {@code value}.
     */
    public static void BufferCount(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 40L, value);
    }

    /**
     * Gets the offset of the field {@code OutputWindow} (in bytes).
     */
    public static long OutputWindow$offset() {
        return 48L;
    }

    /**
     * Gets the value of field {@code OutputWindow} in {@code segment}.
     */
    public static MemorySegment OutputWindow(MemorySegment segment) {
        return segment.get(ADDRESS, 48L);
    }

    /**
     * Sets the field {@code OutputWindow} in {@code segment} to {@code value}.
     */
    public static void OutputWindow(MemorySegment segment, MemorySegment value) {
        segment.set(ADDRESS, 48L, value);
    }

    /**
     * Gets the offset of the field {@code Windowed} (in bytes).
     */
    public static long Windowed$offset() {
        return 56L;
    }

    /**
     * Gets the value of field {@code Windowed} in {@code segment}.
     */
    public static int Windowed(MemorySegment segment) {
        return segment.get(JAVA_INT, 56L);
    }

    /**
     * Sets the field {@code Windowed} in {@code segment} to {@code value}.
     */
    public static void Windowed(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 56L, value);
    }

    /**
     * Gets the offset of the field {@code SwapEffect} (in bytes).
     */
    public static long SwapEffect$offset() {
        return 60L;
    }

    /**
     * Gets the value of field {@code SwapEffect} in {@code segment}.
     */
    public static int SwapEffect(MemorySegment segment) {
        return segment.get(JAVA_INT, 60L);
    }

    /**
     * Sets the field {@code SwapEffect} in {@code segment} to {@code value}.
     */
    public static void SwapEffect(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 60L, value);
    }

    /**
     * Gets the offset of the field {@code Flags} (in bytes).
     */
    public static long Flags$offset() {
        return 64L;
    }

    /**
     * Gets the value of field {@code Flags} in {@code segment}.
     */
    public static int Flags(MemorySegment segment) {
        return segment.get(JAVA_INT, 64L);
    }

    /**
     * Sets the field {@code Flags} in {@code segment} to {@code value}.
     */
    public static void Flags(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 64L, value);
    }

    /**
     * Allocates a new memory segment for the struct {@code DXGI_SWAP_CHAIN_DESC}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(72L, 8L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code DXGI_SWAP_CHAIN_DESC} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(72L * index, 72L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(72L * elementCount, 8L);
    }

    private DXGI_SWAP_CHAIN_DESC () {}
}
