// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

import java.lang.foreign.*;
import java.lang.invoke.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code IDXGIFactory2} COM interface
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi1_2/nn-dxgi1_2-idxgifactory2">IDXGIFactory2 (Microsoft)</a>
 */
public interface IDXGIFactory2 extends IDXGIFactory1 {
    /**
     * {@code IsWindowedStereoEnabled} COM interface method
     * <p>
     * {@snippet lang=c :
     * BOOL IsWindowedStereoEnabled(
     * );
     * }
     * </p>
     */
    int IsWindowedStereoEnabled();

    /**
     * {@code CreateSwapChainForHwnd} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateSwapChainForHwnd(
     *     IUnknown pDevice,
     *     HWND hWnd,
     *     DXGI_SWAP_CHAIN_DESC1* pDesc,
     *     DXGI_SWAP_CHAIN_FULLSCREEN_DESC* pFullscreenDesc,
     *     IDXGIOutput pRestrictToOutput,
     *     IDXGISwapChain1* ppSwapChain
     * );
     * }
     * </p>
     */
    int CreateSwapChainForHwnd(MemorySegment pDevice, MemorySegment hWnd, MemorySegment pDesc, MemorySegment pFullscreenDesc, MemorySegment pRestrictToOutput, MemorySegment ppSwapChain);

    /**
     * {@code CreateSwapChainForCoreWindow} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateSwapChainForCoreWindow(
     *     IUnknown pDevice,
     *     IUnknown pWindow,
     *     DXGI_SWAP_CHAIN_DESC1* pDesc,
     *     IDXGIOutput pRestrictToOutput,
     *     IDXGISwapChain1* ppSwapChain
     * );
     * }
     * </p>
     */
    int CreateSwapChainForCoreWindow(MemorySegment pDevice, MemorySegment pWindow, MemorySegment pDesc, MemorySegment pRestrictToOutput, MemorySegment ppSwapChain);

    /**
     * {@code GetSharedResourceAdapterLuid} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetSharedResourceAdapterLuid(
     *     HANDLE hResource,
     *     LUID* pLuid
     * );
     * }
     * </p>
     */
    int GetSharedResourceAdapterLuid(MemorySegment hResource, MemorySegment pLuid);

    /**
     * {@code RegisterStereoStatusWindow} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT RegisterStereoStatusWindow(
     *     HWND WindowHandle,
     *     DWORD wMsg,
     *     DWORD* pdwCookie
     * );
     * }
     * </p>
     */
    int RegisterStereoStatusWindow(MemorySegment WindowHandle, int wMsg, MemorySegment pdwCookie);

    /**
     * {@code RegisterStereoStatusEvent} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT RegisterStereoStatusEvent(
     *     HANDLE hEvent,
     *     DWORD* pdwCookie
     * );
     * }
     * </p>
     */
    int RegisterStereoStatusEvent(MemorySegment hEvent, MemorySegment pdwCookie);

    /**
     * {@code UnregisterStereoStatus} COM interface method
     * <p>
     * {@snippet lang=c :
     * void UnregisterStereoStatus(
     *     DWORD dwCookie
     * );
     * }
     * </p>
     */
    void UnregisterStereoStatus(int dwCookie);

    /**
     * {@code RegisterOcclusionStatusWindow} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT RegisterOcclusionStatusWindow(
     *     HWND WindowHandle,
     *     DWORD wMsg,
     *     DWORD* pdwCookie
     * );
     * }
     * </p>
     */
    int RegisterOcclusionStatusWindow(MemorySegment WindowHandle, int wMsg, MemorySegment pdwCookie);

    /**
     * {@code RegisterOcclusionStatusEvent} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT RegisterOcclusionStatusEvent(
     *     HANDLE hEvent,
     *     DWORD* pdwCookie
     * );
     * }
     * </p>
     */
    int RegisterOcclusionStatusEvent(MemorySegment hEvent, MemorySegment pdwCookie);

    /**
     * {@code UnregisterOcclusionStatus} COM interface method
     * <p>
     * {@snippet lang=c :
     * void UnregisterOcclusionStatus(
     *     DWORD dwCookie
     * );
     * }
     * </p>
     */
    void UnregisterOcclusionStatus(int dwCookie);

    /**
     * {@code CreateSwapChainForComposition} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CreateSwapChainForComposition(
     *     IUnknown pDevice,
     *     DXGI_SWAP_CHAIN_DESC1* pDesc,
     *     IDXGIOutput pRestrictToOutput,
     *     IDXGISwapChain1* ppSwapChain
     * );
     * }
     * </p>
     */
    int CreateSwapChainForComposition(MemorySegment pDevice, MemorySegment pDesc, MemorySegment pRestrictToOutput, MemorySegment ppSwapChain);

    /**
     * Wraps the given COM object in a Java object with methods to call the COM interface functions.
     */
    static IDXGIFactory2 wrap(MemorySegment comObject) {
        return new $DOWNCALL(comObject.reinterpret(8L));
    }

    /**
     * Gets the address layout for pointers to {@code IDXGIFactory2} COM interfaces.
     */
    static AddressLayout addressLayout() {
        return IDXGIFactory2$ADDRESS_LAYOUT;
    }

    /**
     * Interface identifier (IID) for {@code IDXGIFactory2} ({@code {50c83a1c-e072-4c48-87b0-3630fa36a6d0}}).
     */
    static MemorySegment iid() {
        return $IID$IDXGIFactory2.IID$SEG;
    }

    /**
     * Creates a COM object instance for the given Java object implementing {@code IDXGIFactory2}.
     */
    static MemorySegment create(IDXGIFactory2 obj, Arena arena) {
        var unwrapper = new $UPCALL(obj);
        var vtable = arena.allocate(ADDRESS, 25);
        var linker = Linker.nativeLinker();
        for (int i = 0; i < 25; i++)
            vtable.set(ADDRESS, 8 * i, linker.upcallStub($UPCALL_IMPL.HANDLES[i].bindTo(unwrapper), $UPCALL_IMPL.DESCRIPTORS[i], arena));
        var objSegment = arena.allocate(ADDRESS);
        objSegment.set(ADDRESS, 0, vtable);
        return objSegment;
    }

    StructLayout IDXGIFactory2$COM_OBJECT_LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(25, ADDRESS)).withName("vtable")
    );

    AddressLayout IDXGIFactory2$ADDRESS_LAYOUT = ADDRESS.withTargetLayout(IDXGIFactory2$COM_OBJECT_LAYOUT);

    AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));
    AddressLayout ADDRESS$STRUCT_8_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(8, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_16_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_20_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(20, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_48_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(48, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_72_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(72, JAVA_BYTE).withByteAlignment(8));

    class $IID$IDXGIFactory2 {
        private static final Arena ARENA = Arena.ofAuto();

        private static MemorySegment createGuid(long v1, long v2) {
            var seg = ARENA.allocate(16, 8);
            seg.set(ValueLayout.JAVA_LONG, 0, v1);
            seg.set(ValueLayout.JAVA_LONG, 8, v2);
            return seg;
        }

        private static final MemorySegment IID$SEG = createGuid(5496890126791883292L, -3411979219507957625L);

    }

    class $DOWNCALL extends IDXGIFactory1.$DOWNCALL implements IDXGIFactory2 {
        private static final VarHandle VTABLE_FUNC_VARHANDLE = IDXGIFactory2$COM_OBJECT_LAYOUT.varHandle(
                PathElement.groupElement("vtable"),
                PathElement.dereferenceElement(),
                PathElement.sequenceElement()
        );

        private static MemorySegment vtableFunc(MemorySegment comObject, long index) {
            return (MemorySegment) VTABLE_FUNC_VARHANDLE.get(comObject, 0L, index);
        }

        protected $DOWNCALL(MemorySegment comObject) {
            super(comObject);
        }

        public int IsWindowedStereoEnabled() {
            try {
                return (int) VFUNC14$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 14), comObject);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateSwapChainForHwnd(MemorySegment pDevice, MemorySegment hWnd, MemorySegment pDesc, MemorySegment pFullscreenDesc, MemorySegment pRestrictToOutput, MemorySegment ppSwapChain) {
            try {
                return (int) VFUNC15$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 15), comObject, pDevice, hWnd, pDesc, pFullscreenDesc, pRestrictToOutput, ppSwapChain);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateSwapChainForCoreWindow(MemorySegment pDevice, MemorySegment pWindow, MemorySegment pDesc, MemorySegment pRestrictToOutput, MemorySegment ppSwapChain) {
            try {
                return (int) VFUNC16$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 16), comObject, pDevice, pWindow, pDesc, pRestrictToOutput, ppSwapChain);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetSharedResourceAdapterLuid(MemorySegment hResource, MemorySegment pLuid) {
            try {
                return (int) VFUNC17$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 17), comObject, hResource, pLuid);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int RegisterStereoStatusWindow(MemorySegment WindowHandle, int wMsg, MemorySegment pdwCookie) {
            try {
                return (int) VFUNC18$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 18), comObject, WindowHandle, wMsg, pdwCookie);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int RegisterStereoStatusEvent(MemorySegment hEvent, MemorySegment pdwCookie) {
            try {
                return (int) VFUNC19$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 19), comObject, hEvent, pdwCookie);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public void UnregisterStereoStatus(int dwCookie) {
            try {
                VFUNC20$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 20), comObject, dwCookie);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int RegisterOcclusionStatusWindow(MemorySegment WindowHandle, int wMsg, MemorySegment pdwCookie) {
            try {
                return (int) VFUNC21$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 21), comObject, WindowHandle, wMsg, pdwCookie);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int RegisterOcclusionStatusEvent(MemorySegment hEvent, MemorySegment pdwCookie) {
            try {
                return (int) VFUNC22$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 22), comObject, hEvent, pdwCookie);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public void UnregisterOcclusionStatus(int dwCookie) {
            try {
                VFUNC23$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 23), comObject, dwCookie);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CreateSwapChainForComposition(MemorySegment pDevice, MemorySegment pDesc, MemorySegment pRestrictToOutput, MemorySegment ppSwapChain) {
            try {
                return (int) VFUNC24$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 24), comObject, pDevice, pDesc, pRestrictToOutput, ppSwapChain);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

    }

    class VFUNC14$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIFactory2$ADDRESS_LAYOUT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC15$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIFactory2$ADDRESS_LAYOUT, ADDRESS$ADDRESS, ADDRESS, ADDRESS$STRUCT_48_4, ADDRESS$STRUCT_20_4, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC16$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIFactory2$ADDRESS_LAYOUT, ADDRESS$ADDRESS, ADDRESS$ADDRESS, ADDRESS$STRUCT_48_4, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC17$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIFactory2$ADDRESS_LAYOUT, ADDRESS, ADDRESS$STRUCT_8_4);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC18$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIFactory2$ADDRESS_LAYOUT, ADDRESS, JAVA_INT, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC19$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIFactory2$ADDRESS_LAYOUT, ADDRESS, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC20$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(IDXGIFactory2$ADDRESS_LAYOUT, JAVA_INT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC21$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIFactory2$ADDRESS_LAYOUT, ADDRESS, JAVA_INT, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC22$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIFactory2$ADDRESS_LAYOUT, ADDRESS, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC23$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(IDXGIFactory2$ADDRESS_LAYOUT, JAVA_INT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC24$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIFactory2$ADDRESS_LAYOUT, ADDRESS$ADDRESS, ADDRESS$STRUCT_48_4, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class $UPCALL {
        private final IDXGIFactory2 javaObject;

        private $UPCALL(IDXGIFactory2 javaObject) {
            this.javaObject = javaObject;
        }

        int QueryInterface(MemorySegment thisObject, MemorySegment riid, MemorySegment ppvObject) {
            return javaObject.QueryInterface(riid, ppvObject);
        }
        int AddRef(MemorySegment thisObject) {
            return javaObject.AddRef();
        }
        int Release(MemorySegment thisObject) {
            return javaObject.Release();
        }
        int SetPrivateData(MemorySegment thisObject, MemorySegment Name, int DataSize, MemorySegment pData) {
            return javaObject.SetPrivateData(Name, DataSize, pData);
        }
        int SetPrivateDataInterface(MemorySegment thisObject, MemorySegment Name, MemorySegment pUnknown) {
            return javaObject.SetPrivateDataInterface(Name, pUnknown);
        }
        int GetPrivateData(MemorySegment thisObject, MemorySegment Name, MemorySegment pDataSize, MemorySegment pData) {
            return javaObject.GetPrivateData(Name, pDataSize, pData);
        }
        int GetParent(MemorySegment thisObject, MemorySegment riid, MemorySegment ppParent) {
            return javaObject.GetParent(riid, ppParent);
        }
        int EnumAdapters(MemorySegment thisObject, int Adapter, MemorySegment ppAdapter) {
            return javaObject.EnumAdapters(Adapter, ppAdapter);
        }
        int MakeWindowAssociation(MemorySegment thisObject, MemorySegment WindowHandle, int Flags) {
            return javaObject.MakeWindowAssociation(WindowHandle, Flags);
        }
        int GetWindowAssociation(MemorySegment thisObject, MemorySegment pWindowHandle) {
            return javaObject.GetWindowAssociation(pWindowHandle);
        }
        int CreateSwapChain(MemorySegment thisObject, MemorySegment pDevice, MemorySegment pDesc, MemorySegment ppSwapChain) {
            return javaObject.CreateSwapChain(pDevice, pDesc, ppSwapChain);
        }
        int CreateSoftwareAdapter(MemorySegment thisObject, MemorySegment Module, MemorySegment ppAdapter) {
            return javaObject.CreateSoftwareAdapter(Module, ppAdapter);
        }
        int EnumAdapters1(MemorySegment thisObject, int Adapter, MemorySegment ppAdapter) {
            return javaObject.EnumAdapters1(Adapter, ppAdapter);
        }
        int IsCurrent(MemorySegment thisObject) {
            return javaObject.IsCurrent();
        }
        int IsWindowedStereoEnabled(MemorySegment thisObject) {
            return javaObject.IsWindowedStereoEnabled();
        }
        int CreateSwapChainForHwnd(MemorySegment thisObject, MemorySegment pDevice, MemorySegment hWnd, MemorySegment pDesc, MemorySegment pFullscreenDesc, MemorySegment pRestrictToOutput, MemorySegment ppSwapChain) {
            return javaObject.CreateSwapChainForHwnd(pDevice, hWnd, pDesc, pFullscreenDesc, pRestrictToOutput, ppSwapChain);
        }
        int CreateSwapChainForCoreWindow(MemorySegment thisObject, MemorySegment pDevice, MemorySegment pWindow, MemorySegment pDesc, MemorySegment pRestrictToOutput, MemorySegment ppSwapChain) {
            return javaObject.CreateSwapChainForCoreWindow(pDevice, pWindow, pDesc, pRestrictToOutput, ppSwapChain);
        }
        int GetSharedResourceAdapterLuid(MemorySegment thisObject, MemorySegment hResource, MemorySegment pLuid) {
            return javaObject.GetSharedResourceAdapterLuid(hResource, pLuid);
        }
        int RegisterStereoStatusWindow(MemorySegment thisObject, MemorySegment WindowHandle, int wMsg, MemorySegment pdwCookie) {
            return javaObject.RegisterStereoStatusWindow(WindowHandle, wMsg, pdwCookie);
        }
        int RegisterStereoStatusEvent(MemorySegment thisObject, MemorySegment hEvent, MemorySegment pdwCookie) {
            return javaObject.RegisterStereoStatusEvent(hEvent, pdwCookie);
        }
        void UnregisterStereoStatus(MemorySegment thisObject, int dwCookie) {
            javaObject.UnregisterStereoStatus(dwCookie);
        }
        int RegisterOcclusionStatusWindow(MemorySegment thisObject, MemorySegment WindowHandle, int wMsg, MemorySegment pdwCookie) {
            return javaObject.RegisterOcclusionStatusWindow(WindowHandle, wMsg, pdwCookie);
        }
        int RegisterOcclusionStatusEvent(MemorySegment thisObject, MemorySegment hEvent, MemorySegment pdwCookie) {
            return javaObject.RegisterOcclusionStatusEvent(hEvent, pdwCookie);
        }
        void UnregisterOcclusionStatus(MemorySegment thisObject, int dwCookie) {
            javaObject.UnregisterOcclusionStatus(dwCookie);
        }
        int CreateSwapChainForComposition(MemorySegment thisObject, MemorySegment pDevice, MemorySegment pDesc, MemorySegment pRestrictToOutput, MemorySegment ppSwapChain) {
            return javaObject.CreateSwapChainForComposition(pDevice, pDesc, pRestrictToOutput, ppSwapChain);
        }
    }

    class $UPCALL_IMPL {
        private static final FunctionDescriptor[] DESCRIPTORS = createDescriptors();
        private static final MethodHandle[] HANDLES = createHandles();

        private static FunctionDescriptor[] createDescriptors() {
            var descriptors = new FunctionDescriptor[25];
            descriptors[0] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[1] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[2] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[3] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
            descriptors[4] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[5] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
            descriptors[6] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[7] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$ADDRESS);
            descriptors[8] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT);
            descriptors[9] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS);
            descriptors[10] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS, ADDRESS$STRUCT_72_8, ADDRESS$ADDRESS);
            descriptors[11] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, ADDRESS$ADDRESS);
            descriptors[12] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$ADDRESS);
            descriptors[13] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[14] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[15] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS, ADDRESS, ADDRESS$STRUCT_48_4, ADDRESS$STRUCT_20_4, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
            descriptors[16] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS, ADDRESS$ADDRESS, ADDRESS$STRUCT_48_4, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
            descriptors[17] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, ADDRESS$STRUCT_8_4);
            descriptors[18] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, ADDRESS$UNKNOWN_SIZE);
            descriptors[19] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, ADDRESS$UNKNOWN_SIZE);
            descriptors[20] = FunctionDescriptor.ofVoid(ADDRESS, JAVA_INT);
            descriptors[21] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, ADDRESS$UNKNOWN_SIZE);
            descriptors[22] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, ADDRESS$UNKNOWN_SIZE);
            descriptors[23] = FunctionDescriptor.ofVoid(ADDRESS, JAVA_INT);
            descriptors[24] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS, ADDRESS$STRUCT_48_4, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
            return descriptors;
        }

        private static MethodHandle[] createHandles() {
            try {
                var lookup = MethodHandles.lookup();
                var handles = new MethodHandle[25];
                handles[0] = lookup.findVirtual($UPCALL.class, "QueryInterface", DESCRIPTORS[0].toMethodType());
                handles[1] = lookup.findVirtual($UPCALL.class, "AddRef", DESCRIPTORS[1].toMethodType());
                handles[2] = lookup.findVirtual($UPCALL.class, "Release", DESCRIPTORS[2].toMethodType());
                handles[3] = lookup.findVirtual($UPCALL.class, "SetPrivateData", DESCRIPTORS[3].toMethodType());
                handles[4] = lookup.findVirtual($UPCALL.class, "SetPrivateDataInterface", DESCRIPTORS[4].toMethodType());
                handles[5] = lookup.findVirtual($UPCALL.class, "GetPrivateData", DESCRIPTORS[5].toMethodType());
                handles[6] = lookup.findVirtual($UPCALL.class, "GetParent", DESCRIPTORS[6].toMethodType());
                handles[7] = lookup.findVirtual($UPCALL.class, "EnumAdapters", DESCRIPTORS[7].toMethodType());
                handles[8] = lookup.findVirtual($UPCALL.class, "MakeWindowAssociation", DESCRIPTORS[8].toMethodType());
                handles[9] = lookup.findVirtual($UPCALL.class, "GetWindowAssociation", DESCRIPTORS[9].toMethodType());
                handles[10] = lookup.findVirtual($UPCALL.class, "CreateSwapChain", DESCRIPTORS[10].toMethodType());
                handles[11] = lookup.findVirtual($UPCALL.class, "CreateSoftwareAdapter", DESCRIPTORS[11].toMethodType());
                handles[12] = lookup.findVirtual($UPCALL.class, "EnumAdapters1", DESCRIPTORS[12].toMethodType());
                handles[13] = lookup.findVirtual($UPCALL.class, "IsCurrent", DESCRIPTORS[13].toMethodType());
                handles[14] = lookup.findVirtual($UPCALL.class, "IsWindowedStereoEnabled", DESCRIPTORS[14].toMethodType());
                handles[15] = lookup.findVirtual($UPCALL.class, "CreateSwapChainForHwnd", DESCRIPTORS[15].toMethodType());
                handles[16] = lookup.findVirtual($UPCALL.class, "CreateSwapChainForCoreWindow", DESCRIPTORS[16].toMethodType());
                handles[17] = lookup.findVirtual($UPCALL.class, "GetSharedResourceAdapterLuid", DESCRIPTORS[17].toMethodType());
                handles[18] = lookup.findVirtual($UPCALL.class, "RegisterStereoStatusWindow", DESCRIPTORS[18].toMethodType());
                handles[19] = lookup.findVirtual($UPCALL.class, "RegisterStereoStatusEvent", DESCRIPTORS[19].toMethodType());
                handles[20] = lookup.findVirtual($UPCALL.class, "UnregisterStereoStatus", DESCRIPTORS[20].toMethodType());
                handles[21] = lookup.findVirtual($UPCALL.class, "RegisterOcclusionStatusWindow", DESCRIPTORS[21].toMethodType());
                handles[22] = lookup.findVirtual($UPCALL.class, "RegisterOcclusionStatusEvent", DESCRIPTORS[22].toMethodType());
                handles[23] = lookup.findVirtual($UPCALL.class, "UnregisterOcclusionStatus", DESCRIPTORS[23].toMethodType());
                handles[24] = lookup.findVirtual($UPCALL.class, "CreateSwapChainForComposition", DESCRIPTORS[24].toMethodType());
               return handles;
           } catch (ReflectiveOperationException e) {
               throw new RuntimeException(e);
           }
       }
   }
}
