// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

import java.lang.foreign.*;
import java.lang.invoke.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code IDXGISwapChain3} COM interface
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi1_4/nn-dxgi1_4-idxgiswapchain3">IDXGISwapChain3 (Microsoft)</a>
 */
public interface IDXGISwapChain3 extends IDXGISwapChain2 {
    /**
     * {@code GetCurrentBackBufferIndex} COM interface method
     * <p>
     * {@snippet lang=c :
     * DWORD GetCurrentBackBufferIndex(
     * );
     * }
     * </p>
     */
    int GetCurrentBackBufferIndex();

    /**
     * {@code CheckColorSpaceSupport} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CheckColorSpaceSupport(
     *     DXGI_COLOR_SPACE_TYPE ColorSpace,
     *     DWORD* pColorSpaceSupport
     * );
     * }
     * </p>
     */
    int CheckColorSpaceSupport(int ColorSpace, MemorySegment pColorSpaceSupport);

    /**
     * {@code SetColorSpace1} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT SetColorSpace1(
     *     DXGI_COLOR_SPACE_TYPE ColorSpace
     * );
     * }
     * </p>
     */
    int SetColorSpace1(int ColorSpace);

    /**
     * {@code ResizeBuffers1} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT ResizeBuffers1(
     *     DWORD BufferCount,
     *     DWORD Width,
     *     DWORD Height,
     *     DXGI_FORMAT Format,
     *     DWORD SwapChainFlags,
     *     DWORD* pCreationNodeMask,
     *     IUnknown* ppPresentQueue
     * );
     * }
     * </p>
     */
    int ResizeBuffers1(int BufferCount, int Width, int Height, int Format, int SwapChainFlags, MemorySegment pCreationNodeMask, MemorySegment ppPresentQueue);

    /**
     * Wraps the given COM object in a Java object with methods to call the COM interface functions.
     */
    static IDXGISwapChain3 wrap(MemorySegment comObject) {
        return new $DOWNCALL(comObject.reinterpret(8L));
    }

    /**
     * Gets the address layout for pointers to {@code IDXGISwapChain3} COM interfaces.
     */
    static AddressLayout addressLayout() {
        return IDXGISwapChain3$ADDRESS_LAYOUT;
    }

    /**
     * Interface identifier (IID) for {@code IDXGISwapChain3} ({@code {94d99bdb-f1f8-4ab0-b236-7da0170edab1}}).
     */
    static MemorySegment iid() {
        return $IID$IDXGISwapChain3.IID$SEG;
    }

    /**
     * Creates a COM object instance for the given Java object implementing {@code IDXGISwapChain3}.
     */
    static MemorySegment create(IDXGISwapChain3 obj, Arena arena) {
        var unwrapper = new $UPCALL(obj);
        var vtable = arena.allocate(ADDRESS, 40);
        var linker = Linker.nativeLinker();
        for (int i = 0; i < 40; i++)
            vtable.set(ADDRESS, 8 * i, linker.upcallStub($UPCALL_IMPL.HANDLES[i].bindTo(unwrapper), $UPCALL_IMPL.DESCRIPTORS[i], arena));
        var objSegment = arena.allocate(ADDRESS);
        objSegment.set(ADDRESS, 0, vtable);
        return objSegment;
    }

    StructLayout IDXGISwapChain3$COM_OBJECT_LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(40, ADDRESS)).withName("vtable")
    );

    AddressLayout IDXGISwapChain3$ADDRESS_LAYOUT = ADDRESS.withTargetLayout(IDXGISwapChain3$COM_OBJECT_LAYOUT);

    AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));
    AddressLayout ADDRESS$STRUCT_16_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_20_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(20, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_24_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(24, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_28_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(28, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_32_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(32, JAVA_BYTE).withByteAlignment(8));
    AddressLayout ADDRESS$STRUCT_48_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(48, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_72_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(72, JAVA_BYTE).withByteAlignment(8));

    class $IID$IDXGISwapChain3 {
        private static final Arena ARENA = Arena.ofAuto();

        private static MemorySegment createGuid(long v1, long v2) {
            var seg = ARENA.allocate(16, 8);
            seg.set(ValueLayout.JAVA_LONG, 0, v1);
            seg.set(ValueLayout.JAVA_LONG, 8, v2);
            return seg;
        }

        private static final MemorySegment IID$SEG = createGuid(5382067604659215323L, -5631172889433786702L);

    }

    class $DOWNCALL extends IDXGISwapChain2.$DOWNCALL implements IDXGISwapChain3 {
        private static final VarHandle VTABLE_FUNC_VARHANDLE = IDXGISwapChain3$COM_OBJECT_LAYOUT.varHandle(
                PathElement.groupElement("vtable"),
                PathElement.dereferenceElement(),
                PathElement.sequenceElement()
        );

        private static MemorySegment vtableFunc(MemorySegment comObject, long index) {
            return (MemorySegment) VTABLE_FUNC_VARHANDLE.get(comObject, 0L, index);
        }

        protected $DOWNCALL(MemorySegment comObject) {
            super(comObject);
        }

        public int GetCurrentBackBufferIndex() {
            try {
                return (int) VFUNC36$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 36), comObject);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int CheckColorSpaceSupport(int ColorSpace, MemorySegment pColorSpaceSupport) {
            try {
                return (int) VFUNC37$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 37), comObject, ColorSpace, pColorSpaceSupport);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int SetColorSpace1(int ColorSpace) {
            try {
                return (int) VFUNC38$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 38), comObject, ColorSpace);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int ResizeBuffers1(int BufferCount, int Width, int Height, int Format, int SwapChainFlags, MemorySegment pCreationNodeMask, MemorySegment ppPresentQueue) {
            try {
                return (int) VFUNC39$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 39), comObject, BufferCount, Width, Height, Format, SwapChainFlags, pCreationNodeMask, ppPresentQueue);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

    }

    class VFUNC36$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain3$ADDRESS_LAYOUT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC37$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain3$ADDRESS_LAYOUT, JAVA_INT, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC38$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain3$ADDRESS_LAYOUT, JAVA_INT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC39$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain3$ADDRESS_LAYOUT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, ADDRESS$UNKNOWN_SIZE, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class $UPCALL {
        private final IDXGISwapChain3 javaObject;

        private $UPCALL(IDXGISwapChain3 javaObject) {
            this.javaObject = javaObject;
        }

        int QueryInterface(MemorySegment thisObject, MemorySegment riid, MemorySegment ppvObject) {
            return javaObject.QueryInterface(riid, ppvObject);
        }
        int AddRef(MemorySegment thisObject) {
            return javaObject.AddRef();
        }
        int Release(MemorySegment thisObject) {
            return javaObject.Release();
        }
        int SetPrivateData(MemorySegment thisObject, MemorySegment Name, int DataSize, MemorySegment pData) {
            return javaObject.SetPrivateData(Name, DataSize, pData);
        }
        int SetPrivateDataInterface(MemorySegment thisObject, MemorySegment Name, MemorySegment pUnknown) {
            return javaObject.SetPrivateDataInterface(Name, pUnknown);
        }
        int GetPrivateData(MemorySegment thisObject, MemorySegment Name, MemorySegment pDataSize, MemorySegment pData) {
            return javaObject.GetPrivateData(Name, pDataSize, pData);
        }
        int GetParent(MemorySegment thisObject, MemorySegment riid, MemorySegment ppParent) {
            return javaObject.GetParent(riid, ppParent);
        }
        int GetDevice(MemorySegment thisObject, MemorySegment riid, MemorySegment ppDevice) {
            return javaObject.GetDevice(riid, ppDevice);
        }
        int Present(MemorySegment thisObject, int SyncInterval, int Flags) {
            return javaObject.Present(SyncInterval, Flags);
        }
        int GetBuffer(MemorySegment thisObject, int Buffer, MemorySegment riid, MemorySegment ppSurface) {
            return javaObject.GetBuffer(Buffer, riid, ppSurface);
        }
        int SetFullscreenState(MemorySegment thisObject, int Fullscreen, MemorySegment pTarget) {
            return javaObject.SetFullscreenState(Fullscreen, pTarget);
        }
        int GetFullscreenState(MemorySegment thisObject, MemorySegment pFullscreen, MemorySegment ppTarget) {
            return javaObject.GetFullscreenState(pFullscreen, ppTarget);
        }
        int GetDesc(MemorySegment thisObject, MemorySegment pDesc) {
            return javaObject.GetDesc(pDesc);
        }
        int ResizeBuffers(MemorySegment thisObject, int BufferCount, int Width, int Height, int NewFormat, int SwapChainFlags) {
            return javaObject.ResizeBuffers(BufferCount, Width, Height, NewFormat, SwapChainFlags);
        }
        int ResizeTarget(MemorySegment thisObject, MemorySegment pNewTargetParameters) {
            return javaObject.ResizeTarget(pNewTargetParameters);
        }
        int GetContainingOutput(MemorySegment thisObject, MemorySegment ppOutput) {
            return javaObject.GetContainingOutput(ppOutput);
        }
        int GetFrameStatistics(MemorySegment thisObject, MemorySegment pStats) {
            return javaObject.GetFrameStatistics(pStats);
        }
        int GetLastPresentCount(MemorySegment thisObject, MemorySegment pLastPresentCount) {
            return javaObject.GetLastPresentCount(pLastPresentCount);
        }
        int GetDesc1(MemorySegment thisObject, MemorySegment pDesc) {
            return javaObject.GetDesc1(pDesc);
        }
        int GetFullscreenDesc(MemorySegment thisObject, MemorySegment pDesc) {
            return javaObject.GetFullscreenDesc(pDesc);
        }
        int GetHwnd(MemorySegment thisObject, MemorySegment pHwnd) {
            return javaObject.GetHwnd(pHwnd);
        }
        int GetCoreWindow(MemorySegment thisObject, MemorySegment refiid, MemorySegment ppUnk) {
            return javaObject.GetCoreWindow(refiid, ppUnk);
        }
        int Present1(MemorySegment thisObject, int SyncInterval, int PresentFlags, MemorySegment pPresentParameters) {
            return javaObject.Present1(SyncInterval, PresentFlags, pPresentParameters);
        }
        int IsTemporaryMonoSupported(MemorySegment thisObject) {
            return javaObject.IsTemporaryMonoSupported();
        }
        int GetRestrictToOutput(MemorySegment thisObject, MemorySegment ppRestrictToOutput) {
            return javaObject.GetRestrictToOutput(ppRestrictToOutput);
        }
        int SetBackgroundColor(MemorySegment thisObject, MemorySegment pColor) {
            return javaObject.SetBackgroundColor(pColor);
        }
        int GetBackgroundColor(MemorySegment thisObject, MemorySegment pColor) {
            return javaObject.GetBackgroundColor(pColor);
        }
        int SetRotation(MemorySegment thisObject, int Rotation) {
            return javaObject.SetRotation(Rotation);
        }
        int GetRotation(MemorySegment thisObject, MemorySegment pRotation) {
            return javaObject.GetRotation(pRotation);
        }
        int SetSourceSize(MemorySegment thisObject, int Width, int Height) {
            return javaObject.SetSourceSize(Width, Height);
        }
        int GetSourceSize(MemorySegment thisObject, MemorySegment pWidth, MemorySegment pHeight) {
            return javaObject.GetSourceSize(pWidth, pHeight);
        }
        int SetMaximumFrameLatency(MemorySegment thisObject, int MaxLatency) {
            return javaObject.SetMaximumFrameLatency(MaxLatency);
        }
        int GetMaximumFrameLatency(MemorySegment thisObject, MemorySegment pMaxLatency) {
            return javaObject.GetMaximumFrameLatency(pMaxLatency);
        }
        MemorySegment GetFrameLatencyWaitableObject(MemorySegment thisObject) {
            return javaObject.GetFrameLatencyWaitableObject();
        }
        int SetMatrixTransform(MemorySegment thisObject, MemorySegment pMatrix) {
            return javaObject.SetMatrixTransform(pMatrix);
        }
        int GetMatrixTransform(MemorySegment thisObject, MemorySegment pMatrix) {
            return javaObject.GetMatrixTransform(pMatrix);
        }
        int GetCurrentBackBufferIndex(MemorySegment thisObject) {
            return javaObject.GetCurrentBackBufferIndex();
        }
        int CheckColorSpaceSupport(MemorySegment thisObject, int ColorSpace, MemorySegment pColorSpaceSupport) {
            return javaObject.CheckColorSpaceSupport(ColorSpace, pColorSpaceSupport);
        }
        int SetColorSpace1(MemorySegment thisObject, int ColorSpace) {
            return javaObject.SetColorSpace1(ColorSpace);
        }
        int ResizeBuffers1(MemorySegment thisObject, int BufferCount, int Width, int Height, int Format, int SwapChainFlags, MemorySegment pCreationNodeMask, MemorySegment ppPresentQueue) {
            return javaObject.ResizeBuffers1(BufferCount, Width, Height, Format, SwapChainFlags, pCreationNodeMask, ppPresentQueue);
        }
    }

    class $UPCALL_IMPL {
        private static final FunctionDescriptor[] DESCRIPTORS = createDescriptors();
        private static final MethodHandle[] HANDLES = createHandles();

        private static FunctionDescriptor[] createDescriptors() {
            var descriptors = new FunctionDescriptor[40];
            descriptors[0] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[1] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[2] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[3] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
            descriptors[4] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[5] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
            descriptors[6] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[7] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[8] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT);
            descriptors[9] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[10] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$ADDRESS);
            descriptors[11] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$UNKNOWN_SIZE, ADDRESS$ADDRESS);
            descriptors[12] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_72_8);
            descriptors[13] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT);
            descriptors[14] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_28_4);
            descriptors[15] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS);
            descriptors[16] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_32_8);
            descriptors[17] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$UNKNOWN_SIZE);
            descriptors[18] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_48_4);
            descriptors[19] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_20_4);
            descriptors[20] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS);
            descriptors[21] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[22] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT, ADDRESS$STRUCT_32_8);
            descriptors[23] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[24] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS);
            descriptors[25] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4);
            descriptors[26] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4);
            descriptors[27] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT);
            descriptors[28] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$UNKNOWN_SIZE);
            descriptors[29] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT);
            descriptors[30] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$UNKNOWN_SIZE, ADDRESS$UNKNOWN_SIZE);
            descriptors[31] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT);
            descriptors[32] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$UNKNOWN_SIZE);
            descriptors[33] = FunctionDescriptor.of(ADDRESS, ADDRESS);
            descriptors[34] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_24_4);
            descriptors[35] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_24_4);
            descriptors[36] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[37] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$UNKNOWN_SIZE);
            descriptors[38] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT);
            descriptors[39] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, ADDRESS$UNKNOWN_SIZE, ADDRESS$ADDRESS);
            return descriptors;
        }

        private static MethodHandle[] createHandles() {
            try {
                var lookup = MethodHandles.lookup();
                var handles = new MethodHandle[40];
                handles[0] = lookup.findVirtual($UPCALL.class, "QueryInterface", DESCRIPTORS[0].toMethodType());
                handles[1] = lookup.findVirtual($UPCALL.class, "AddRef", DESCRIPTORS[1].toMethodType());
                handles[2] = lookup.findVirtual($UPCALL.class, "Release", DESCRIPTORS[2].toMethodType());
                handles[3] = lookup.findVirtual($UPCALL.class, "SetPrivateData", DESCRIPTORS[3].toMethodType());
                handles[4] = lookup.findVirtual($UPCALL.class, "SetPrivateDataInterface", DESCRIPTORS[4].toMethodType());
                handles[5] = lookup.findVirtual($UPCALL.class, "GetPrivateData", DESCRIPTORS[5].toMethodType());
                handles[6] = lookup.findVirtual($UPCALL.class, "GetParent", DESCRIPTORS[6].toMethodType());
                handles[7] = lookup.findVirtual($UPCALL.class, "GetDevice", DESCRIPTORS[7].toMethodType());
                handles[8] = lookup.findVirtual($UPCALL.class, "Present", DESCRIPTORS[8].toMethodType());
                handles[9] = lookup.findVirtual($UPCALL.class, "GetBuffer", DESCRIPTORS[9].toMethodType());
                handles[10] = lookup.findVirtual($UPCALL.class, "SetFullscreenState", DESCRIPTORS[10].toMethodType());
                handles[11] = lookup.findVirtual($UPCALL.class, "GetFullscreenState", DESCRIPTORS[11].toMethodType());
                handles[12] = lookup.findVirtual($UPCALL.class, "GetDesc", DESCRIPTORS[12].toMethodType());
                handles[13] = lookup.findVirtual($UPCALL.class, "ResizeBuffers", DESCRIPTORS[13].toMethodType());
                handles[14] = lookup.findVirtual($UPCALL.class, "ResizeTarget", DESCRIPTORS[14].toMethodType());
                handles[15] = lookup.findVirtual($UPCALL.class, "GetContainingOutput", DESCRIPTORS[15].toMethodType());
                handles[16] = lookup.findVirtual($UPCALL.class, "GetFrameStatistics", DESCRIPTORS[16].toMethodType());
                handles[17] = lookup.findVirtual($UPCALL.class, "GetLastPresentCount", DESCRIPTORS[17].toMethodType());
                handles[18] = lookup.findVirtual($UPCALL.class, "GetDesc1", DESCRIPTORS[18].toMethodType());
                handles[19] = lookup.findVirtual($UPCALL.class, "GetFullscreenDesc", DESCRIPTORS[19].toMethodType());
                handles[20] = lookup.findVirtual($UPCALL.class, "GetHwnd", DESCRIPTORS[20].toMethodType());
                handles[21] = lookup.findVirtual($UPCALL.class, "GetCoreWindow", DESCRIPTORS[21].toMethodType());
                handles[22] = lookup.findVirtual($UPCALL.class, "Present1", DESCRIPTORS[22].toMethodType());
                handles[23] = lookup.findVirtual($UPCALL.class, "IsTemporaryMonoSupported", DESCRIPTORS[23].toMethodType());
                handles[24] = lookup.findVirtual($UPCALL.class, "GetRestrictToOutput", DESCRIPTORS[24].toMethodType());
                handles[25] = lookup.findVirtual($UPCALL.class, "SetBackgroundColor", DESCRIPTORS[25].toMethodType());
                handles[26] = lookup.findVirtual($UPCALL.class, "GetBackgroundColor", DESCRIPTORS[26].toMethodType());
                handles[27] = lookup.findVirtual($UPCALL.class, "SetRotation", DESCRIPTORS[27].toMethodType());
                handles[28] = lookup.findVirtual($UPCALL.class, "GetRotation", DESCRIPTORS[28].toMethodType());
                handles[29] = lookup.findVirtual($UPCALL.class, "SetSourceSize", DESCRIPTORS[29].toMethodType());
                handles[30] = lookup.findVirtual($UPCALL.class, "GetSourceSize", DESCRIPTORS[30].toMethodType());
                handles[31] = lookup.findVirtual($UPCALL.class, "SetMaximumFrameLatency", DESCRIPTORS[31].toMethodType());
                handles[32] = lookup.findVirtual($UPCALL.class, "GetMaximumFrameLatency", DESCRIPTORS[32].toMethodType());
                handles[33] = lookup.findVirtual($UPCALL.class, "GetFrameLatencyWaitableObject", DESCRIPTORS[33].toMethodType());
                handles[34] = lookup.findVirtual($UPCALL.class, "SetMatrixTransform", DESCRIPTORS[34].toMethodType());
                handles[35] = lookup.findVirtual($UPCALL.class, "GetMatrixTransform", DESCRIPTORS[35].toMethodType());
                handles[36] = lookup.findVirtual($UPCALL.class, "GetCurrentBackBufferIndex", DESCRIPTORS[36].toMethodType());
                handles[37] = lookup.findVirtual($UPCALL.class, "CheckColorSpaceSupport", DESCRIPTORS[37].toMethodType());
                handles[38] = lookup.findVirtual($UPCALL.class, "SetColorSpace1", DESCRIPTORS[38].toMethodType());
                handles[39] = lookup.findVirtual($UPCALL.class, "ResizeBuffers1", DESCRIPTORS[39].toMethodType());
               return handles;
           } catch (ReflectiveOperationException e) {
               throw new RuntimeException(e);
           }
       }
   }
}
