// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

import java.lang.foreign.*;
import java.lang.invoke.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code IDXGIAdapter1} COM interface
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi/nn-dxgi-idxgiadapter1">IDXGIAdapter1 (Microsoft)</a>
 */
public interface IDXGIAdapter1 extends IDXGIAdapter {
    /**
     * {@code GetDesc1} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetDesc1(
     *     DXGI_ADAPTER_DESC1* pDesc
     * );
     * }
     * </p>
     */
    int GetDesc1(MemorySegment pDesc);

    /**
     * Wraps the given COM object in a Java object with methods to call the COM interface functions.
     */
    static IDXGIAdapter1 wrap(MemorySegment comObject) {
        return new $DOWNCALL(comObject.reinterpret(8L));
    }

    /**
     * Gets the address layout for pointers to {@code IDXGIAdapter1} COM interfaces.
     */
    static AddressLayout addressLayout() {
        return IDXGIAdapter1$ADDRESS_LAYOUT;
    }

    /**
     * Interface identifier (IID) for {@code IDXGIAdapter1} ({@code {29038f61-3839-4626-91fd-086879011a05}}).
     */
    static MemorySegment iid() {
        return $IID$IDXGIAdapter1.IID$SEG;
    }

    /**
     * Creates a COM object instance for the given Java object implementing {@code IDXGIAdapter1}.
     */
    static MemorySegment create(IDXGIAdapter1 obj, Arena arena) {
        var unwrapper = new $UPCALL(obj);
        var vtable = arena.allocate(ADDRESS, 11);
        var linker = Linker.nativeLinker();
        for (int i = 0; i < 11; i++)
            vtable.set(ADDRESS, 8 * i, linker.upcallStub($UPCALL_IMPL.HANDLES[i].bindTo(unwrapper), $UPCALL_IMPL.DESCRIPTORS[i], arena));
        var objSegment = arena.allocate(ADDRESS);
        objSegment.set(ADDRESS, 0, vtable);
        return objSegment;
    }

    StructLayout IDXGIAdapter1$COM_OBJECT_LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(11, ADDRESS)).withName("vtable")
    );

    AddressLayout IDXGIAdapter1$ADDRESS_LAYOUT = ADDRESS.withTargetLayout(IDXGIAdapter1$COM_OBJECT_LAYOUT);

    AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));
    AddressLayout ADDRESS$STRUCT_16_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_304_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(304, JAVA_BYTE).withByteAlignment(8));
    AddressLayout ADDRESS$STRUCT_312_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(312, JAVA_BYTE).withByteAlignment(8));

    class $IID$IDXGIAdapter1 {
        private static final Arena ARENA = Arena.ofAuto();

        private static MemorySegment createGuid(long v1, long v2) {
            var seg = ARENA.allocate(16, 8);
            seg.set(ValueLayout.JAVA_LONG, 0, v1);
            seg.set(ValueLayout.JAVA_LONG, 8, v2);
            return seg;
        }

        private static final MemorySegment IID$SEG = createGuid(5054789449922350945L, 367607940532206993L);

    }

    class $DOWNCALL extends IDXGIAdapter.$DOWNCALL implements IDXGIAdapter1 {
        private static final VarHandle VTABLE_FUNC_VARHANDLE = IDXGIAdapter1$COM_OBJECT_LAYOUT.varHandle(
                PathElement.groupElement("vtable"),
                PathElement.dereferenceElement(),
                PathElement.sequenceElement()
        );

        private static MemorySegment vtableFunc(MemorySegment comObject, long index) {
            return (MemorySegment) VTABLE_FUNC_VARHANDLE.get(comObject, 0L, index);
        }

        protected $DOWNCALL(MemorySegment comObject) {
            super(comObject);
        }

        public int GetDesc1(MemorySegment pDesc) {
            try {
                return (int) VFUNC10$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 10), comObject, pDesc);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

    }

    class VFUNC10$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIAdapter1$ADDRESS_LAYOUT, ADDRESS$STRUCT_312_8);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class $UPCALL {
        private final IDXGIAdapter1 javaObject;

        private $UPCALL(IDXGIAdapter1 javaObject) {
            this.javaObject = javaObject;
        }

        int QueryInterface(MemorySegment thisObject, MemorySegment riid, MemorySegment ppvObject) {
            return javaObject.QueryInterface(riid, ppvObject);
        }
        int AddRef(MemorySegment thisObject) {
            return javaObject.AddRef();
        }
        int Release(MemorySegment thisObject) {
            return javaObject.Release();
        }
        int SetPrivateData(MemorySegment thisObject, MemorySegment Name, int DataSize, MemorySegment pData) {
            return javaObject.SetPrivateData(Name, DataSize, pData);
        }
        int SetPrivateDataInterface(MemorySegment thisObject, MemorySegment Name, MemorySegment pUnknown) {
            return javaObject.SetPrivateDataInterface(Name, pUnknown);
        }
        int GetPrivateData(MemorySegment thisObject, MemorySegment Name, MemorySegment pDataSize, MemorySegment pData) {
            return javaObject.GetPrivateData(Name, pDataSize, pData);
        }
        int GetParent(MemorySegment thisObject, MemorySegment riid, MemorySegment ppParent) {
            return javaObject.GetParent(riid, ppParent);
        }
        int EnumOutputs(MemorySegment thisObject, int Output, MemorySegment ppOutput) {
            return javaObject.EnumOutputs(Output, ppOutput);
        }
        int GetDesc(MemorySegment thisObject, MemorySegment pDesc) {
            return javaObject.GetDesc(pDesc);
        }
        int CheckInterfaceSupport(MemorySegment thisObject, MemorySegment InterfaceName, MemorySegment pUMDVersion) {
            return javaObject.CheckInterfaceSupport(InterfaceName, pUMDVersion);
        }
        int GetDesc1(MemorySegment thisObject, MemorySegment pDesc) {
            return javaObject.GetDesc1(pDesc);
        }
    }

    class $UPCALL_IMPL {
        private static final FunctionDescriptor[] DESCRIPTORS = createDescriptors();
        private static final MethodHandle[] HANDLES = createHandles();

        private static FunctionDescriptor[] createDescriptors() {
            var descriptors = new FunctionDescriptor[11];
            descriptors[0] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[1] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[2] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[3] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
            descriptors[4] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[5] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
            descriptors[6] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[7] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$ADDRESS);
            descriptors[8] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_304_8);
            descriptors[9] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE);
            descriptors[10] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_312_8);
            return descriptors;
        }

        private static MethodHandle[] createHandles() {
            try {
                var lookup = MethodHandles.lookup();
                var handles = new MethodHandle[11];
                handles[0] = lookup.findVirtual($UPCALL.class, "QueryInterface", DESCRIPTORS[0].toMethodType());
                handles[1] = lookup.findVirtual($UPCALL.class, "AddRef", DESCRIPTORS[1].toMethodType());
                handles[2] = lookup.findVirtual($UPCALL.class, "Release", DESCRIPTORS[2].toMethodType());
                handles[3] = lookup.findVirtual($UPCALL.class, "SetPrivateData", DESCRIPTORS[3].toMethodType());
                handles[4] = lookup.findVirtual($UPCALL.class, "SetPrivateDataInterface", DESCRIPTORS[4].toMethodType());
                handles[5] = lookup.findVirtual($UPCALL.class, "GetPrivateData", DESCRIPTORS[5].toMethodType());
                handles[6] = lookup.findVirtual($UPCALL.class, "GetParent", DESCRIPTORS[6].toMethodType());
                handles[7] = lookup.findVirtual($UPCALL.class, "EnumOutputs", DESCRIPTORS[7].toMethodType());
                handles[8] = lookup.findVirtual($UPCALL.class, "GetDesc", DESCRIPTORS[8].toMethodType());
                handles[9] = lookup.findVirtual($UPCALL.class, "CheckInterfaceSupport", DESCRIPTORS[9].toMethodType());
                handles[10] = lookup.findVirtual($UPCALL.class, "GetDesc1", DESCRIPTORS[10].toMethodType());
               return handles;
           } catch (ReflectiveOperationException e) {
               throw new RuntimeException(e);
           }
       }
   }
}
