// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

import java.lang.foreign.*;
import java.lang.invoke.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code IDXGIFactory1} COM interface
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi/nn-dxgi-idxgifactory1">IDXGIFactory1 (Microsoft)</a>
 */
public interface IDXGIFactory1 extends IDXGIFactory {
    /**
     * {@code EnumAdapters1} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT EnumAdapters1(
     *     DWORD Adapter,
     *     IDXGIAdapter1* ppAdapter
     * );
     * }
     * </p>
     */
    int EnumAdapters1(int Adapter, MemorySegment ppAdapter);

    /**
     * {@code IsCurrent} COM interface method
     * <p>
     * {@snippet lang=c :
     * BOOL IsCurrent(
     * );
     * }
     * </p>
     */
    int IsCurrent();

    /**
     * Wraps the given COM object in a Java object with methods to call the COM interface functions.
     */
    static IDXGIFactory1 wrap(MemorySegment comObject) {
        return new $DOWNCALL(comObject.reinterpret(8L));
    }

    /**
     * Gets the address layout for pointers to {@code IDXGIFactory1} COM interfaces.
     */
    static AddressLayout addressLayout() {
        return IDXGIFactory1$ADDRESS_LAYOUT;
    }

    /**
     * Interface identifier (IID) for {@code IDXGIFactory1} ({@code {770aae78-f26f-4dba-a829-253c83d1b387}}).
     */
    static MemorySegment iid() {
        return $IID$IDXGIFactory1.IID$SEG;
    }

    /**
     * Creates a COM object instance for the given Java object implementing {@code IDXGIFactory1}.
     */
    static MemorySegment create(IDXGIFactory1 obj, Arena arena) {
        var unwrapper = new $UPCALL(obj);
        var vtable = arena.allocate(ADDRESS, 14);
        var linker = Linker.nativeLinker();
        for (int i = 0; i < 14; i++)
            vtable.set(ADDRESS, 8 * i, linker.upcallStub($UPCALL_IMPL.HANDLES[i].bindTo(unwrapper), $UPCALL_IMPL.DESCRIPTORS[i], arena));
        var objSegment = arena.allocate(ADDRESS);
        objSegment.set(ADDRESS, 0, vtable);
        return objSegment;
    }

    StructLayout IDXGIFactory1$COM_OBJECT_LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(14, ADDRESS)).withName("vtable")
    );

    AddressLayout IDXGIFactory1$ADDRESS_LAYOUT = ADDRESS.withTargetLayout(IDXGIFactory1$COM_OBJECT_LAYOUT);

    AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));
    AddressLayout ADDRESS$STRUCT_16_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_72_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(72, JAVA_BYTE).withByteAlignment(8));

    class $IID$IDXGIFactory1 {
        private static final Arena ARENA = Arena.ofAuto();

        private static MemorySegment createGuid(long v1, long v2) {
            var seg = ARENA.allocate(16, 8);
            seg.set(ValueLayout.JAVA_LONG, 0, v1);
            seg.set(ValueLayout.JAVA_LONG, 8, v2);
            return seg;
        }

        private static final MemorySegment IID$SEG = createGuid(5601055647141113464L, -8668354496178083416L);

    }

    class $DOWNCALL extends IDXGIFactory.$DOWNCALL implements IDXGIFactory1 {
        private static final VarHandle VTABLE_FUNC_VARHANDLE = IDXGIFactory1$COM_OBJECT_LAYOUT.varHandle(
                PathElement.groupElement("vtable"),
                PathElement.dereferenceElement(),
                PathElement.sequenceElement()
        );

        private static MemorySegment vtableFunc(MemorySegment comObject, long index) {
            return (MemorySegment) VTABLE_FUNC_VARHANDLE.get(comObject, 0L, index);
        }

        protected $DOWNCALL(MemorySegment comObject) {
            super(comObject);
        }

        public int EnumAdapters1(int Adapter, MemorySegment ppAdapter) {
            try {
                return (int) VFUNC12$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 12), comObject, Adapter, ppAdapter);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int IsCurrent() {
            try {
                return (int) VFUNC13$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 13), comObject);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

    }

    class VFUNC12$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIFactory1$ADDRESS_LAYOUT, JAVA_INT, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC13$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIFactory1$ADDRESS_LAYOUT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class $UPCALL {
        private final IDXGIFactory1 javaObject;

        private $UPCALL(IDXGIFactory1 javaObject) {
            this.javaObject = javaObject;
        }

        int QueryInterface(MemorySegment thisObject, MemorySegment riid, MemorySegment ppvObject) {
            return javaObject.QueryInterface(riid, ppvObject);
        }
        int AddRef(MemorySegment thisObject) {
            return javaObject.AddRef();
        }
        int Release(MemorySegment thisObject) {
            return javaObject.Release();
        }
        int SetPrivateData(MemorySegment thisObject, MemorySegment Name, int DataSize, MemorySegment pData) {
            return javaObject.SetPrivateData(Name, DataSize, pData);
        }
        int SetPrivateDataInterface(MemorySegment thisObject, MemorySegment Name, MemorySegment pUnknown) {
            return javaObject.SetPrivateDataInterface(Name, pUnknown);
        }
        int GetPrivateData(MemorySegment thisObject, MemorySegment Name, MemorySegment pDataSize, MemorySegment pData) {
            return javaObject.GetPrivateData(Name, pDataSize, pData);
        }
        int GetParent(MemorySegment thisObject, MemorySegment riid, MemorySegment ppParent) {
            return javaObject.GetParent(riid, ppParent);
        }
        int EnumAdapters(MemorySegment thisObject, int Adapter, MemorySegment ppAdapter) {
            return javaObject.EnumAdapters(Adapter, ppAdapter);
        }
        int MakeWindowAssociation(MemorySegment thisObject, MemorySegment WindowHandle, int Flags) {
            return javaObject.MakeWindowAssociation(WindowHandle, Flags);
        }
        int GetWindowAssociation(MemorySegment thisObject, MemorySegment pWindowHandle) {
            return javaObject.GetWindowAssociation(pWindowHandle);
        }
        int CreateSwapChain(MemorySegment thisObject, MemorySegment pDevice, MemorySegment pDesc, MemorySegment ppSwapChain) {
            return javaObject.CreateSwapChain(pDevice, pDesc, ppSwapChain);
        }
        int CreateSoftwareAdapter(MemorySegment thisObject, MemorySegment Module, MemorySegment ppAdapter) {
            return javaObject.CreateSoftwareAdapter(Module, ppAdapter);
        }
        int EnumAdapters1(MemorySegment thisObject, int Adapter, MemorySegment ppAdapter) {
            return javaObject.EnumAdapters1(Adapter, ppAdapter);
        }
        int IsCurrent(MemorySegment thisObject) {
            return javaObject.IsCurrent();
        }
    }

    class $UPCALL_IMPL {
        private static final FunctionDescriptor[] DESCRIPTORS = createDescriptors();
        private static final MethodHandle[] HANDLES = createHandles();

        private static FunctionDescriptor[] createDescriptors() {
            var descriptors = new FunctionDescriptor[14];
            descriptors[0] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[1] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[2] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[3] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
            descriptors[4] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[5] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
            descriptors[6] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[7] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$ADDRESS);
            descriptors[8] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT);
            descriptors[9] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS);
            descriptors[10] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS, ADDRESS$STRUCT_72_8, ADDRESS$ADDRESS);
            descriptors[11] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, ADDRESS$ADDRESS);
            descriptors[12] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$ADDRESS);
            descriptors[13] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            return descriptors;
        }

        private static MethodHandle[] createHandles() {
            try {
                var lookup = MethodHandles.lookup();
                var handles = new MethodHandle[14];
                handles[0] = lookup.findVirtual($UPCALL.class, "QueryInterface", DESCRIPTORS[0].toMethodType());
                handles[1] = lookup.findVirtual($UPCALL.class, "AddRef", DESCRIPTORS[1].toMethodType());
                handles[2] = lookup.findVirtual($UPCALL.class, "Release", DESCRIPTORS[2].toMethodType());
                handles[3] = lookup.findVirtual($UPCALL.class, "SetPrivateData", DESCRIPTORS[3].toMethodType());
                handles[4] = lookup.findVirtual($UPCALL.class, "SetPrivateDataInterface", DESCRIPTORS[4].toMethodType());
                handles[5] = lookup.findVirtual($UPCALL.class, "GetPrivateData", DESCRIPTORS[5].toMethodType());
                handles[6] = lookup.findVirtual($UPCALL.class, "GetParent", DESCRIPTORS[6].toMethodType());
                handles[7] = lookup.findVirtual($UPCALL.class, "EnumAdapters", DESCRIPTORS[7].toMethodType());
                handles[8] = lookup.findVirtual($UPCALL.class, "MakeWindowAssociation", DESCRIPTORS[8].toMethodType());
                handles[9] = lookup.findVirtual($UPCALL.class, "GetWindowAssociation", DESCRIPTORS[9].toMethodType());
                handles[10] = lookup.findVirtual($UPCALL.class, "CreateSwapChain", DESCRIPTORS[10].toMethodType());
                handles[11] = lookup.findVirtual($UPCALL.class, "CreateSoftwareAdapter", DESCRIPTORS[11].toMethodType());
                handles[12] = lookup.findVirtual($UPCALL.class, "EnumAdapters1", DESCRIPTORS[12].toMethodType());
                handles[13] = lookup.findVirtual($UPCALL.class, "IsCurrent", DESCRIPTORS[13].toMethodType());
               return handles;
           } catch (ReflectiveOperationException e) {
               throw new RuntimeException(e);
           }
       }
   }
}
