// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;

/**
 * {@code IDXGISwapChain1} COM interface
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi1_2/nn-dxgi1_2-idxgiswapchain1">IDXGISwapChain1 (Microsoft)</a>
 */
public interface IDXGISwapChain1 extends IDXGISwapChain {
    /**
     * {@code GetDesc1} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetDesc1(
     *     DXGI_SWAP_CHAIN_DESC1* pDesc
     * );
     * }
     * </p>
     */
    int GetDesc1(MemorySegment pDesc);

    /**
     * {@code GetFullscreenDesc} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetFullscreenDesc(
     *     DXGI_SWAP_CHAIN_FULLSCREEN_DESC* pDesc
     * );
     * }
     * </p>
     */
    int GetFullscreenDesc(MemorySegment pDesc);

    /**
     * {@code GetHwnd} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetHwnd(
     *     HWND* pHwnd
     * );
     * }
     * </p>
     */
    int GetHwnd(MemorySegment pHwnd);

    /**
     * {@code GetCoreWindow} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetCoreWindow(
     *     GUID* refiid,
     *     void** ppUnk
     * );
     * }
     * </p>
     */
    int GetCoreWindow(MemorySegment refiid, MemorySegment ppUnk);

    /**
     * {@code Present1} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT Present1(
     *     DWORD SyncInterval,
     *     DXGI_PRESENT PresentFlags,
     *     DXGI_PRESENT_PARAMETERS* pPresentParameters
     * );
     * }
     * </p>
     */
    int Present1(int SyncInterval, int PresentFlags, MemorySegment pPresentParameters);

    /**
     * {@code IsTemporaryMonoSupported} COM interface method
     * <p>
     * {@snippet lang=c :
     * BOOL IsTemporaryMonoSupported(
     * );
     * }
     * </p>
     */
    int IsTemporaryMonoSupported();

    /**
     * {@code GetRestrictToOutput} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetRestrictToOutput(
     *     IDXGIOutput* ppRestrictToOutput
     * );
     * }
     * </p>
     */
    int GetRestrictToOutput(MemorySegment ppRestrictToOutput);

    /**
     * {@code SetBackgroundColor} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT SetBackgroundColor(
     *     DXGI_RGBA* pColor
     * );
     * }
     * </p>
     */
    int SetBackgroundColor(MemorySegment pColor);

    /**
     * {@code GetBackgroundColor} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetBackgroundColor(
     *     DXGI_RGBA* pColor
     * );
     * }
     * </p>
     */
    int GetBackgroundColor(MemorySegment pColor);

    /**
     * {@code SetRotation} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT SetRotation(
     *     DXGI_MODE_ROTATION Rotation
     * );
     * }
     * </p>
     */
    int SetRotation(int Rotation);

    /**
     * {@code GetRotation} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetRotation(
     *     DXGI_MODE_ROTATION* pRotation
     * );
     * }
     * </p>
     */
    int GetRotation(MemorySegment pRotation);

    /**
     * Wraps the given COM object in a Java object with methods to call the COM interface functions.
     */
    static IDXGISwapChain1 wrap(MemorySegment comObject) {
        return new $DOWNCALL(comObject.reinterpret(8L));
    }

    /**
     * Gets the address layout for pointers to {@code IDXGISwapChain1} COM interfaces.
     */
    static AddressLayout addressLayout() {
        return IDXGISwapChain1$ADDRESS_LAYOUT;
    }

    /**
     * Interface identifier (IID) for {@code IDXGISwapChain1} ({@code {790a45f7-0d42-4876-983a-0a55cfe6f4aa}}).
     */
    static MemorySegment iid() {
        return $IID$IDXGISwapChain1.IID$SEG;
    }

    /**
     * Creates a COM object instance for the given Java object implementing {@code IDXGISwapChain1}.
     */
    static MemorySegment create(IDXGISwapChain1 obj, Arena arena) {
        var unwrapper = new $UPCALL(obj);
        var vtable = arena.allocate(ADDRESS, 29);
        var linker = Linker.nativeLinker();
        for (int i = 0; i < 29; i++)
            vtable.set(ADDRESS, 8 * i, linker.upcallStub($UPCALL_IMPL.HANDLES[i].bindTo(unwrapper), $UPCALL_IMPL.DESCRIPTORS[i], arena));
        var objSegment = arena.allocate(ADDRESS);
        objSegment.set(ADDRESS, 0, vtable);
        return objSegment;
    }

    StructLayout IDXGISwapChain1$COM_OBJECT_LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(29, ADDRESS)).withName("vtable")
    );

    AddressLayout IDXGISwapChain1$ADDRESS_LAYOUT = ADDRESS.withTargetLayout(IDXGISwapChain1$COM_OBJECT_LAYOUT);

    AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));
    AddressLayout ADDRESS$STRUCT_16_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_20_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(20, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_28_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(28, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_32_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(32, JAVA_BYTE).withByteAlignment(8));
    AddressLayout ADDRESS$STRUCT_48_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(48, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_72_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(72, JAVA_BYTE).withByteAlignment(8));

    class $IID$IDXGISwapChain1 {
        private static final Arena ARENA = Arena.ofAuto();

        private static MemorySegment createGuid(long v1, long v2) {
            var seg = ARENA.allocate(16, 8);
            seg.set(ValueLayout.JAVA_LONG, 0, v1);
            seg.set(ValueLayout.JAVA_LONG, 8, v2);
            return seg;
        }

        private static final MemorySegment IID$SEG = createGuid(5221375397132387831L, -6128019414785049960L);

    }

    class $DOWNCALL extends IDXGISwapChain.$DOWNCALL implements IDXGISwapChain1 {
        private static final VarHandle VTABLE_FUNC_VARHANDLE = IDXGISwapChain1$COM_OBJECT_LAYOUT.varHandle(
                PathElement.groupElement("vtable"),
                PathElement.dereferenceElement(),
                PathElement.sequenceElement()
        );

        private static MemorySegment vtableFunc(MemorySegment comObject, long index) {
            return (MemorySegment) VTABLE_FUNC_VARHANDLE.get(comObject, 0L, index);
        }

        protected $DOWNCALL(MemorySegment comObject) {
            super(comObject);
        }

        public int GetDesc1(MemorySegment pDesc) {
            try {
                return (int) VFUNC18$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 18), comObject, pDesc);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetFullscreenDesc(MemorySegment pDesc) {
            try {
                return (int) VFUNC19$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 19), comObject, pDesc);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetHwnd(MemorySegment pHwnd) {
            try {
                return (int) VFUNC20$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 20), comObject, pHwnd);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetCoreWindow(MemorySegment refiid, MemorySegment ppUnk) {
            try {
                return (int) VFUNC21$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 21), comObject, refiid, ppUnk);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int Present1(int SyncInterval, int PresentFlags, MemorySegment pPresentParameters) {
            try {
                return (int) VFUNC22$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 22), comObject, SyncInterval, PresentFlags, pPresentParameters);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int IsTemporaryMonoSupported() {
            try {
                return (int) VFUNC23$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 23), comObject);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetRestrictToOutput(MemorySegment ppRestrictToOutput) {
            try {
                return (int) VFUNC24$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 24), comObject, ppRestrictToOutput);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int SetBackgroundColor(MemorySegment pColor) {
            try {
                return (int) VFUNC25$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 25), comObject, pColor);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetBackgroundColor(MemorySegment pColor) {
            try {
                return (int) VFUNC26$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 26), comObject, pColor);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int SetRotation(int Rotation) {
            try {
                return (int) VFUNC27$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 27), comObject, Rotation);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

        public int GetRotation(MemorySegment pRotation) {
            try {
                return (int) VFUNC28$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 28), comObject, pRotation);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

    }

    class VFUNC18$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain1$ADDRESS_LAYOUT, ADDRESS$STRUCT_48_4);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC19$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain1$ADDRESS_LAYOUT, ADDRESS$STRUCT_20_4);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC20$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain1$ADDRESS_LAYOUT, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC21$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain1$ADDRESS_LAYOUT, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC22$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain1$ADDRESS_LAYOUT, JAVA_INT, JAVA_INT, ADDRESS$STRUCT_32_8);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC23$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain1$ADDRESS_LAYOUT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC24$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain1$ADDRESS_LAYOUT, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC25$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain1$ADDRESS_LAYOUT, ADDRESS$STRUCT_16_4);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC26$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain1$ADDRESS_LAYOUT, ADDRESS$STRUCT_16_4);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC27$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain1$ADDRESS_LAYOUT, JAVA_INT);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class VFUNC28$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGISwapChain1$ADDRESS_LAYOUT, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class $UPCALL {
        private final IDXGISwapChain1 javaObject;

        private $UPCALL(IDXGISwapChain1 javaObject) {
            this.javaObject = javaObject;
        }

        int QueryInterface(MemorySegment thisObject, MemorySegment riid, MemorySegment ppvObject) {
            return javaObject.QueryInterface(riid, ppvObject);
        }
        int AddRef(MemorySegment thisObject) {
            return javaObject.AddRef();
        }
        int Release(MemorySegment thisObject) {
            return javaObject.Release();
        }
        int SetPrivateData(MemorySegment thisObject, MemorySegment Name, int DataSize, MemorySegment pData) {
            return javaObject.SetPrivateData(Name, DataSize, pData);
        }
        int SetPrivateDataInterface(MemorySegment thisObject, MemorySegment Name, MemorySegment pUnknown) {
            return javaObject.SetPrivateDataInterface(Name, pUnknown);
        }
        int GetPrivateData(MemorySegment thisObject, MemorySegment Name, MemorySegment pDataSize, MemorySegment pData) {
            return javaObject.GetPrivateData(Name, pDataSize, pData);
        }
        int GetParent(MemorySegment thisObject, MemorySegment riid, MemorySegment ppParent) {
            return javaObject.GetParent(riid, ppParent);
        }
        int GetDevice(MemorySegment thisObject, MemorySegment riid, MemorySegment ppDevice) {
            return javaObject.GetDevice(riid, ppDevice);
        }
        int Present(MemorySegment thisObject, int SyncInterval, int Flags) {
            return javaObject.Present(SyncInterval, Flags);
        }
        int GetBuffer(MemorySegment thisObject, int Buffer, MemorySegment riid, MemorySegment ppSurface) {
            return javaObject.GetBuffer(Buffer, riid, ppSurface);
        }
        int SetFullscreenState(MemorySegment thisObject, int Fullscreen, MemorySegment pTarget) {
            return javaObject.SetFullscreenState(Fullscreen, pTarget);
        }
        int GetFullscreenState(MemorySegment thisObject, MemorySegment pFullscreen, MemorySegment ppTarget) {
            return javaObject.GetFullscreenState(pFullscreen, ppTarget);
        }
        int GetDesc(MemorySegment thisObject, MemorySegment pDesc) {
            return javaObject.GetDesc(pDesc);
        }
        int ResizeBuffers(MemorySegment thisObject, int BufferCount, int Width, int Height, int NewFormat, int SwapChainFlags) {
            return javaObject.ResizeBuffers(BufferCount, Width, Height, NewFormat, SwapChainFlags);
        }
        int ResizeTarget(MemorySegment thisObject, MemorySegment pNewTargetParameters) {
            return javaObject.ResizeTarget(pNewTargetParameters);
        }
        int GetContainingOutput(MemorySegment thisObject, MemorySegment ppOutput) {
            return javaObject.GetContainingOutput(ppOutput);
        }
        int GetFrameStatistics(MemorySegment thisObject, MemorySegment pStats) {
            return javaObject.GetFrameStatistics(pStats);
        }
        int GetLastPresentCount(MemorySegment thisObject, MemorySegment pLastPresentCount) {
            return javaObject.GetLastPresentCount(pLastPresentCount);
        }
        int GetDesc1(MemorySegment thisObject, MemorySegment pDesc) {
            return javaObject.GetDesc1(pDesc);
        }
        int GetFullscreenDesc(MemorySegment thisObject, MemorySegment pDesc) {
            return javaObject.GetFullscreenDesc(pDesc);
        }
        int GetHwnd(MemorySegment thisObject, MemorySegment pHwnd) {
            return javaObject.GetHwnd(pHwnd);
        }
        int GetCoreWindow(MemorySegment thisObject, MemorySegment refiid, MemorySegment ppUnk) {
            return javaObject.GetCoreWindow(refiid, ppUnk);
        }
        int Present1(MemorySegment thisObject, int SyncInterval, int PresentFlags, MemorySegment pPresentParameters) {
            return javaObject.Present1(SyncInterval, PresentFlags, pPresentParameters);
        }
        int IsTemporaryMonoSupported(MemorySegment thisObject) {
            return javaObject.IsTemporaryMonoSupported();
        }
        int GetRestrictToOutput(MemorySegment thisObject, MemorySegment ppRestrictToOutput) {
            return javaObject.GetRestrictToOutput(ppRestrictToOutput);
        }
        int SetBackgroundColor(MemorySegment thisObject, MemorySegment pColor) {
            return javaObject.SetBackgroundColor(pColor);
        }
        int GetBackgroundColor(MemorySegment thisObject, MemorySegment pColor) {
            return javaObject.GetBackgroundColor(pColor);
        }
        int SetRotation(MemorySegment thisObject, int Rotation) {
            return javaObject.SetRotation(Rotation);
        }
        int GetRotation(MemorySegment thisObject, MemorySegment pRotation) {
            return javaObject.GetRotation(pRotation);
        }
    }

    class $UPCALL_IMPL {
        private static final FunctionDescriptor[] DESCRIPTORS = createDescriptors();
        private static final MethodHandle[] HANDLES = createHandles();

        private static FunctionDescriptor[] createDescriptors() {
            var descriptors = new FunctionDescriptor[29];
            descriptors[0] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[1] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[2] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[3] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
            descriptors[4] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[5] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
            descriptors[6] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[7] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[8] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT);
            descriptors[9] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[10] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$ADDRESS);
            descriptors[11] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$UNKNOWN_SIZE, ADDRESS$ADDRESS);
            descriptors[12] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_72_8);
            descriptors[13] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT);
            descriptors[14] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_28_4);
            descriptors[15] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS);
            descriptors[16] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_32_8);
            descriptors[17] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$UNKNOWN_SIZE);
            descriptors[18] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_48_4);
            descriptors[19] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_20_4);
            descriptors[20] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS);
            descriptors[21] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[22] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT, ADDRESS$STRUCT_32_8);
            descriptors[23] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[24] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS);
            descriptors[25] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4);
            descriptors[26] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4);
            descriptors[27] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT);
            descriptors[28] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$UNKNOWN_SIZE);
            return descriptors;
        }

        private static MethodHandle[] createHandles() {
            try {
                var lookup = MethodHandles.lookup();
                var handles = new MethodHandle[29];
                handles[0] = lookup.findVirtual($UPCALL.class, "QueryInterface", DESCRIPTORS[0].toMethodType());
                handles[1] = lookup.findVirtual($UPCALL.class, "AddRef", DESCRIPTORS[1].toMethodType());
                handles[2] = lookup.findVirtual($UPCALL.class, "Release", DESCRIPTORS[2].toMethodType());
                handles[3] = lookup.findVirtual($UPCALL.class, "SetPrivateData", DESCRIPTORS[3].toMethodType());
                handles[4] = lookup.findVirtual($UPCALL.class, "SetPrivateDataInterface", DESCRIPTORS[4].toMethodType());
                handles[5] = lookup.findVirtual($UPCALL.class, "GetPrivateData", DESCRIPTORS[5].toMethodType());
                handles[6] = lookup.findVirtual($UPCALL.class, "GetParent", DESCRIPTORS[6].toMethodType());
                handles[7] = lookup.findVirtual($UPCALL.class, "GetDevice", DESCRIPTORS[7].toMethodType());
                handles[8] = lookup.findVirtual($UPCALL.class, "Present", DESCRIPTORS[8].toMethodType());
                handles[9] = lookup.findVirtual($UPCALL.class, "GetBuffer", DESCRIPTORS[9].toMethodType());
                handles[10] = lookup.findVirtual($UPCALL.class, "SetFullscreenState", DESCRIPTORS[10].toMethodType());
                handles[11] = lookup.findVirtual($UPCALL.class, "GetFullscreenState", DESCRIPTORS[11].toMethodType());
                handles[12] = lookup.findVirtual($UPCALL.class, "GetDesc", DESCRIPTORS[12].toMethodType());
                handles[13] = lookup.findVirtual($UPCALL.class, "ResizeBuffers", DESCRIPTORS[13].toMethodType());
                handles[14] = lookup.findVirtual($UPCALL.class, "ResizeTarget", DESCRIPTORS[14].toMethodType());
                handles[15] = lookup.findVirtual($UPCALL.class, "GetContainingOutput", DESCRIPTORS[15].toMethodType());
                handles[16] = lookup.findVirtual($UPCALL.class, "GetFrameStatistics", DESCRIPTORS[16].toMethodType());
                handles[17] = lookup.findVirtual($UPCALL.class, "GetLastPresentCount", DESCRIPTORS[17].toMethodType());
                handles[18] = lookup.findVirtual($UPCALL.class, "GetDesc1", DESCRIPTORS[18].toMethodType());
                handles[19] = lookup.findVirtual($UPCALL.class, "GetFullscreenDesc", DESCRIPTORS[19].toMethodType());
                handles[20] = lookup.findVirtual($UPCALL.class, "GetHwnd", DESCRIPTORS[20].toMethodType());
                handles[21] = lookup.findVirtual($UPCALL.class, "GetCoreWindow", DESCRIPTORS[21].toMethodType());
                handles[22] = lookup.findVirtual($UPCALL.class, "Present1", DESCRIPTORS[22].toMethodType());
                handles[23] = lookup.findVirtual($UPCALL.class, "IsTemporaryMonoSupported", DESCRIPTORS[23].toMethodType());
                handles[24] = lookup.findVirtual($UPCALL.class, "GetRestrictToOutput", DESCRIPTORS[24].toMethodType());
                handles[25] = lookup.findVirtual($UPCALL.class, "SetBackgroundColor", DESCRIPTORS[25].toMethodType());
                handles[26] = lookup.findVirtual($UPCALL.class, "GetBackgroundColor", DESCRIPTORS[26].toMethodType());
                handles[27] = lookup.findVirtual($UPCALL.class, "SetRotation", DESCRIPTORS[27].toMethodType());
                handles[28] = lookup.findVirtual($UPCALL.class, "GetRotation", DESCRIPTORS[28].toMethodType());
               return handles;
           } catch (ReflectiveOperationException e) {
               throw new RuntimeException(e);
           }
       }
   }
}
