// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;

/**
 * {@code IDXGIDeviceSubObject} COM interface
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi/nn-dxgi-idxgidevicesubobject">IDXGIDeviceSubObject (Microsoft)</a>
 */
public interface IDXGIDeviceSubObject extends IDXGIObject {
    /**
     * {@code GetDevice} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT GetDevice(
     *     GUID* riid,
     *     void** ppDevice
     * );
     * }
     * </p>
     */
    int GetDevice(MemorySegment riid, MemorySegment ppDevice);

    /**
     * Wraps the given COM object in a Java object with methods to call the COM interface functions.
     */
    static IDXGIDeviceSubObject wrap(MemorySegment comObject) {
        return new $DOWNCALL(comObject.reinterpret(8L));
    }

    /**
     * Gets the address layout for pointers to {@code IDXGIDeviceSubObject} COM interfaces.
     */
    static AddressLayout addressLayout() {
        return IDXGIDeviceSubObject$ADDRESS_LAYOUT;
    }

    /**
     * Interface identifier (IID) for {@code IDXGIDeviceSubObject} ({@code {3d3e0379-f9de-4d58-bb6c-18d62992f1a6}}).
     */
    static MemorySegment iid() {
        return $IID$IDXGIDeviceSubObject.IID$SEG;
    }

    /**
     * Creates a COM object instance for the given Java object implementing {@code IDXGIDeviceSubObject}.
     */
    static MemorySegment create(IDXGIDeviceSubObject obj, Arena arena) {
        var unwrapper = new $UPCALL(obj);
        var vtable = arena.allocate(ADDRESS, 8);
        var linker = Linker.nativeLinker();
        for (int i = 0; i < 8; i++)
            vtable.set(ADDRESS, 8 * i, linker.upcallStub($UPCALL_IMPL.HANDLES[i].bindTo(unwrapper), $UPCALL_IMPL.DESCRIPTORS[i], arena));
        var objSegment = arena.allocate(ADDRESS);
        objSegment.set(ADDRESS, 0, vtable);
        return objSegment;
    }

    StructLayout IDXGIDeviceSubObject$COM_OBJECT_LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(8, ADDRESS)).withName("vtable")
    );

    AddressLayout IDXGIDeviceSubObject$ADDRESS_LAYOUT = ADDRESS.withTargetLayout(IDXGIDeviceSubObject$COM_OBJECT_LAYOUT);

    AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));
    AddressLayout ADDRESS$STRUCT_16_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(4));

    class $IID$IDXGIDeviceSubObject {
        private static final Arena ARENA = Arena.ofAuto();

        private static MemorySegment createGuid(long v1, long v2) {
            var seg = ARENA.allocate(16, 8);
            seg.set(ValueLayout.JAVA_LONG, 0, v1);
            seg.set(ValueLayout.JAVA_LONG, 8, v2);
            return seg;
        }

        private static final MemorySegment IID$SEG = createGuid(5573479271776519033L, -6417187285643006789L);

    }

    class $DOWNCALL extends IDXGIObject.$DOWNCALL implements IDXGIDeviceSubObject {
        private static final VarHandle VTABLE_FUNC_VARHANDLE = IDXGIDeviceSubObject$COM_OBJECT_LAYOUT.varHandle(
                PathElement.groupElement("vtable"),
                PathElement.dereferenceElement(),
                PathElement.sequenceElement()
        );

        private static MemorySegment vtableFunc(MemorySegment comObject, long index) {
            return (MemorySegment) VTABLE_FUNC_VARHANDLE.get(comObject, 0L, index);
        }

        protected $DOWNCALL(MemorySegment comObject) {
            super(comObject);
        }

        public int GetDevice(MemorySegment riid, MemorySegment ppDevice) {
            try {
                return (int) VFUNC7$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 7), comObject, riid, ppDevice);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

    }

    class VFUNC7$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIDeviceSubObject$ADDRESS_LAYOUT, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class $UPCALL {
        private final IDXGIDeviceSubObject javaObject;

        private $UPCALL(IDXGIDeviceSubObject javaObject) {
            this.javaObject = javaObject;
        }

        int QueryInterface(MemorySegment thisObject, MemorySegment riid, MemorySegment ppvObject) {
            return javaObject.QueryInterface(riid, ppvObject);
        }
        int AddRef(MemorySegment thisObject) {
            return javaObject.AddRef();
        }
        int Release(MemorySegment thisObject) {
            return javaObject.Release();
        }
        int SetPrivateData(MemorySegment thisObject, MemorySegment Name, int DataSize, MemorySegment pData) {
            return javaObject.SetPrivateData(Name, DataSize, pData);
        }
        int SetPrivateDataInterface(MemorySegment thisObject, MemorySegment Name, MemorySegment pUnknown) {
            return javaObject.SetPrivateDataInterface(Name, pUnknown);
        }
        int GetPrivateData(MemorySegment thisObject, MemorySegment Name, MemorySegment pDataSize, MemorySegment pData) {
            return javaObject.GetPrivateData(Name, pDataSize, pData);
        }
        int GetParent(MemorySegment thisObject, MemorySegment riid, MemorySegment ppParent) {
            return javaObject.GetParent(riid, ppParent);
        }
        int GetDevice(MemorySegment thisObject, MemorySegment riid, MemorySegment ppDevice) {
            return javaObject.GetDevice(riid, ppDevice);
        }
    }

    class $UPCALL_IMPL {
        private static final FunctionDescriptor[] DESCRIPTORS = createDescriptors();
        private static final MethodHandle[] HANDLES = createHandles();

        private static FunctionDescriptor[] createDescriptors() {
            var descriptors = new FunctionDescriptor[8];
            descriptors[0] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[1] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[2] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[3] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
            descriptors[4] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[5] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
            descriptors[6] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[7] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            return descriptors;
        }

        private static MethodHandle[] createHandles() {
            try {
                var lookup = MethodHandles.lookup();
                var handles = new MethodHandle[8];
                handles[0] = lookup.findVirtual($UPCALL.class, "QueryInterface", DESCRIPTORS[0].toMethodType());
                handles[1] = lookup.findVirtual($UPCALL.class, "AddRef", DESCRIPTORS[1].toMethodType());
                handles[2] = lookup.findVirtual($UPCALL.class, "Release", DESCRIPTORS[2].toMethodType());
                handles[3] = lookup.findVirtual($UPCALL.class, "SetPrivateData", DESCRIPTORS[3].toMethodType());
                handles[4] = lookup.findVirtual($UPCALL.class, "SetPrivateDataInterface", DESCRIPTORS[4].toMethodType());
                handles[5] = lookup.findVirtual($UPCALL.class, "GetPrivateData", DESCRIPTORS[5].toMethodType());
                handles[6] = lookup.findVirtual($UPCALL.class, "GetParent", DESCRIPTORS[6].toMethodType());
                handles[7] = lookup.findVirtual($UPCALL.class, "GetDevice", DESCRIPTORS[7].toMethodType());
               return handles;
           } catch (ReflectiveOperationException e) {
               throw new RuntimeException(e);
           }
       }
   }
}
