// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.graphics.dxgi;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.*;

/**
 * {@code IDXGIOutput3} COM interface
 *
 * @see <a href="https://learn.microsoft.com/windows/win32/api/dxgi1_3/nn-dxgi1_3-idxgioutput3">IDXGIOutput3 (Microsoft)</a>
 */
public interface IDXGIOutput3 extends IDXGIOutput2 {
    /**
     * {@code CheckOverlaySupport} COM interface method
     * <p>
     * {@snippet lang=c :
     * HRESULT CheckOverlaySupport(
     *     DXGI_FORMAT EnumFormat,
     *     IUnknown pConcernedDevice,
     *     DWORD* pFlags
     * );
     * }
     * </p>
     */
    int CheckOverlaySupport(int EnumFormat, MemorySegment pConcernedDevice, MemorySegment pFlags);

    /**
     * Wraps the given COM object in a Java object with methods to call the COM interface functions.
     */
    static IDXGIOutput3 wrap(MemorySegment comObject) {
        return new $DOWNCALL(comObject.reinterpret(8L));
    }

    /**
     * Gets the address layout for pointers to {@code IDXGIOutput3} COM interfaces.
     */
    static AddressLayout addressLayout() {
        return IDXGIOutput3$ADDRESS_LAYOUT;
    }

    /**
     * Interface identifier (IID) for {@code IDXGIOutput3} ({@code {8a6bb301-7e7e-41f4-a8e0-5b32f7f99b18}}).
     */
    static MemorySegment iid() {
        return $IID$IDXGIOutput3.IID$SEG;
    }

    /**
     * Creates a COM object instance for the given Java object implementing {@code IDXGIOutput3}.
     */
    static MemorySegment create(IDXGIOutput3 obj, Arena arena) {
        var unwrapper = new $UPCALL(obj);
        var vtable = arena.allocate(ADDRESS, 25);
        var linker = Linker.nativeLinker();
        for (int i = 0; i < 25; i++)
            vtable.set(ADDRESS, 8 * i, linker.upcallStub($UPCALL_IMPL.HANDLES[i].bindTo(unwrapper), $UPCALL_IMPL.DESCRIPTORS[i], arena));
        var objSegment = arena.allocate(ADDRESS);
        objSegment.set(ADDRESS, 0, vtable);
        return objSegment;
    }

    StructLayout IDXGIOutput3$COM_OBJECT_LAYOUT = MemoryLayout.structLayout(
        ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(25, ADDRESS)).withName("vtable")
    );

    AddressLayout IDXGIOutput3$ADDRESS_LAYOUT = ADDRESS.withTargetLayout(IDXGIOutput3$COM_OBJECT_LAYOUT);

    AddressLayout ADDRESS$ADDRESS = ADDRESS.withTargetLayout(ADDRESS);
    AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));
    AddressLayout ADDRESS$STRUCT_16_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(16, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_28_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(28, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_32_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(32, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_32_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(32, JAVA_BYTE).withByteAlignment(8));
    AddressLayout ADDRESS$STRUCT_96_8 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(96, JAVA_BYTE).withByteAlignment(8));
    AddressLayout ADDRESS$STRUCT_4116_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(4116, JAVA_BYTE).withByteAlignment(4));
    AddressLayout ADDRESS$STRUCT_12324_4 = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(12324, JAVA_BYTE).withByteAlignment(4));

    class $IID$IDXGIOutput3 {
        private static final Arena ARENA = Arena.ofAuto();

        private static MemorySegment createGuid(long v1, long v2) {
            var seg = ARENA.allocate(16, 8);
            seg.set(ValueLayout.JAVA_LONG, 0, v1);
            seg.set(ValueLayout.JAVA_LONG, 8, v2);
            return seg;
        }

        private static final MemorySegment IID$SEG = createGuid(4752562588736008961L, 1773285718397542568L);

    }

    class $DOWNCALL extends IDXGIOutput2.$DOWNCALL implements IDXGIOutput3 {
        private static final VarHandle VTABLE_FUNC_VARHANDLE = IDXGIOutput3$COM_OBJECT_LAYOUT.varHandle(
                PathElement.groupElement("vtable"),
                PathElement.dereferenceElement(),
                PathElement.sequenceElement()
        );

        private static MemorySegment vtableFunc(MemorySegment comObject, long index) {
            return (MemorySegment) VTABLE_FUNC_VARHANDLE.get(comObject, 0L, index);
        }

        protected $DOWNCALL(MemorySegment comObject) {
            super(comObject);
        }

        public int CheckOverlaySupport(int EnumFormat, MemorySegment pConcernedDevice, MemorySegment pFlags) {
            try {
                return (int) VFUNC24$IMPL.HANDLE.invokeExact(vtableFunc(comObject, 24), comObject, EnumFormat, pConcernedDevice, pFlags);
            } catch (Throwable ex) {
                throw new RuntimeException(ex);
            }
        }

    }

    class VFUNC24$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, IDXGIOutput3$ADDRESS_LAYOUT, JAVA_INT, ADDRESS$ADDRESS, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(DESC);
    }

    class $UPCALL {
        private final IDXGIOutput3 javaObject;

        private $UPCALL(IDXGIOutput3 javaObject) {
            this.javaObject = javaObject;
        }

        int QueryInterface(MemorySegment thisObject, MemorySegment riid, MemorySegment ppvObject) {
            return javaObject.QueryInterface(riid, ppvObject);
        }
        int AddRef(MemorySegment thisObject) {
            return javaObject.AddRef();
        }
        int Release(MemorySegment thisObject) {
            return javaObject.Release();
        }
        int SetPrivateData(MemorySegment thisObject, MemorySegment Name, int DataSize, MemorySegment pData) {
            return javaObject.SetPrivateData(Name, DataSize, pData);
        }
        int SetPrivateDataInterface(MemorySegment thisObject, MemorySegment Name, MemorySegment pUnknown) {
            return javaObject.SetPrivateDataInterface(Name, pUnknown);
        }
        int GetPrivateData(MemorySegment thisObject, MemorySegment Name, MemorySegment pDataSize, MemorySegment pData) {
            return javaObject.GetPrivateData(Name, pDataSize, pData);
        }
        int GetParent(MemorySegment thisObject, MemorySegment riid, MemorySegment ppParent) {
            return javaObject.GetParent(riid, ppParent);
        }
        int GetDesc(MemorySegment thisObject, MemorySegment pDesc) {
            return javaObject.GetDesc(pDesc);
        }
        int GetDisplayModeList(MemorySegment thisObject, int EnumFormat, int Flags, MemorySegment pNumModes, MemorySegment pDesc) {
            return javaObject.GetDisplayModeList(EnumFormat, Flags, pNumModes, pDesc);
        }
        int FindClosestMatchingMode(MemorySegment thisObject, MemorySegment pModeToMatch, MemorySegment pClosestMatch, MemorySegment pConcernedDevice) {
            return javaObject.FindClosestMatchingMode(pModeToMatch, pClosestMatch, pConcernedDevice);
        }
        int WaitForVBlank(MemorySegment thisObject) {
            return javaObject.WaitForVBlank();
        }
        int TakeOwnership(MemorySegment thisObject, MemorySegment pDevice, int Exclusive) {
            return javaObject.TakeOwnership(pDevice, Exclusive);
        }
        void ReleaseOwnership(MemorySegment thisObject) {
            javaObject.ReleaseOwnership();
        }
        int GetGammaControlCapabilities(MemorySegment thisObject, MemorySegment pGammaCaps) {
            return javaObject.GetGammaControlCapabilities(pGammaCaps);
        }
        int SetGammaControl(MemorySegment thisObject, MemorySegment pArray) {
            return javaObject.SetGammaControl(pArray);
        }
        int GetGammaControl(MemorySegment thisObject, MemorySegment pArray) {
            return javaObject.GetGammaControl(pArray);
        }
        int SetDisplaySurface(MemorySegment thisObject, MemorySegment pScanoutSurface) {
            return javaObject.SetDisplaySurface(pScanoutSurface);
        }
        int GetDisplaySurfaceData(MemorySegment thisObject, MemorySegment pDestination) {
            return javaObject.GetDisplaySurfaceData(pDestination);
        }
        int GetFrameStatistics(MemorySegment thisObject, MemorySegment pStats) {
            return javaObject.GetFrameStatistics(pStats);
        }
        int GetDisplayModeList1(MemorySegment thisObject, int EnumFormat, int Flags, MemorySegment pNumModes, MemorySegment pDesc) {
            return javaObject.GetDisplayModeList1(EnumFormat, Flags, pNumModes, pDesc);
        }
        int FindClosestMatchingMode1(MemorySegment thisObject, MemorySegment pModeToMatch, MemorySegment pClosestMatch, MemorySegment pConcernedDevice) {
            return javaObject.FindClosestMatchingMode1(pModeToMatch, pClosestMatch, pConcernedDevice);
        }
        int GetDisplaySurfaceData1(MemorySegment thisObject, MemorySegment pDestination) {
            return javaObject.GetDisplaySurfaceData1(pDestination);
        }
        int DuplicateOutput(MemorySegment thisObject, MemorySegment pDevice, MemorySegment ppOutputDuplication) {
            return javaObject.DuplicateOutput(pDevice, ppOutputDuplication);
        }
        int SupportsOverlays(MemorySegment thisObject) {
            return javaObject.SupportsOverlays();
        }
        int CheckOverlaySupport(MemorySegment thisObject, int EnumFormat, MemorySegment pConcernedDevice, MemorySegment pFlags) {
            return javaObject.CheckOverlaySupport(EnumFormat, pConcernedDevice, pFlags);
        }
    }

    class $UPCALL_IMPL {
        private static final FunctionDescriptor[] DESCRIPTORS = createDescriptors();
        private static final MethodHandle[] HANDLES = createHandles();

        private static FunctionDescriptor[] createDescriptors() {
            var descriptors = new FunctionDescriptor[25];
            descriptors[0] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[1] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[2] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[3] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, JAVA_INT, ADDRESS);
            descriptors[4] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[5] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$UNKNOWN_SIZE, ADDRESS);
            descriptors[6] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_16_4, ADDRESS$ADDRESS);
            descriptors[7] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_96_8);
            descriptors[8] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT, ADDRESS$UNKNOWN_SIZE, ADDRESS$STRUCT_28_4);
            descriptors[9] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_28_4, ADDRESS$STRUCT_28_4, ADDRESS$ADDRESS);
            descriptors[10] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[11] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS, JAVA_INT);
            descriptors[12] = FunctionDescriptor.ofVoid(ADDRESS);
            descriptors[13] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_4116_4);
            descriptors[14] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_12324_4);
            descriptors[15] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_12324_4);
            descriptors[16] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS);
            descriptors[17] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS);
            descriptors[18] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_32_8);
            descriptors[19] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, JAVA_INT, ADDRESS$UNKNOWN_SIZE, ADDRESS$STRUCT_32_4);
            descriptors[20] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$STRUCT_32_4, ADDRESS$STRUCT_32_4, ADDRESS$ADDRESS);
            descriptors[21] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS);
            descriptors[22] = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS$ADDRESS, ADDRESS$ADDRESS);
            descriptors[23] = FunctionDescriptor.of(JAVA_INT, ADDRESS);
            descriptors[24] = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT, ADDRESS$ADDRESS, ADDRESS$UNKNOWN_SIZE);
            return descriptors;
        }

        private static MethodHandle[] createHandles() {
            try {
                var lookup = MethodHandles.lookup();
                var handles = new MethodHandle[25];
                handles[0] = lookup.findVirtual($UPCALL.class, "QueryInterface", DESCRIPTORS[0].toMethodType());
                handles[1] = lookup.findVirtual($UPCALL.class, "AddRef", DESCRIPTORS[1].toMethodType());
                handles[2] = lookup.findVirtual($UPCALL.class, "Release", DESCRIPTORS[2].toMethodType());
                handles[3] = lookup.findVirtual($UPCALL.class, "SetPrivateData", DESCRIPTORS[3].toMethodType());
                handles[4] = lookup.findVirtual($UPCALL.class, "SetPrivateDataInterface", DESCRIPTORS[4].toMethodType());
                handles[5] = lookup.findVirtual($UPCALL.class, "GetPrivateData", DESCRIPTORS[5].toMethodType());
                handles[6] = lookup.findVirtual($UPCALL.class, "GetParent", DESCRIPTORS[6].toMethodType());
                handles[7] = lookup.findVirtual($UPCALL.class, "GetDesc", DESCRIPTORS[7].toMethodType());
                handles[8] = lookup.findVirtual($UPCALL.class, "GetDisplayModeList", DESCRIPTORS[8].toMethodType());
                handles[9] = lookup.findVirtual($UPCALL.class, "FindClosestMatchingMode", DESCRIPTORS[9].toMethodType());
                handles[10] = lookup.findVirtual($UPCALL.class, "WaitForVBlank", DESCRIPTORS[10].toMethodType());
                handles[11] = lookup.findVirtual($UPCALL.class, "TakeOwnership", DESCRIPTORS[11].toMethodType());
                handles[12] = lookup.findVirtual($UPCALL.class, "ReleaseOwnership", DESCRIPTORS[12].toMethodType());
                handles[13] = lookup.findVirtual($UPCALL.class, "GetGammaControlCapabilities", DESCRIPTORS[13].toMethodType());
                handles[14] = lookup.findVirtual($UPCALL.class, "SetGammaControl", DESCRIPTORS[14].toMethodType());
                handles[15] = lookup.findVirtual($UPCALL.class, "GetGammaControl", DESCRIPTORS[15].toMethodType());
                handles[16] = lookup.findVirtual($UPCALL.class, "SetDisplaySurface", DESCRIPTORS[16].toMethodType());
                handles[17] = lookup.findVirtual($UPCALL.class, "GetDisplaySurfaceData", DESCRIPTORS[17].toMethodType());
                handles[18] = lookup.findVirtual($UPCALL.class, "GetFrameStatistics", DESCRIPTORS[18].toMethodType());
                handles[19] = lookup.findVirtual($UPCALL.class, "GetDisplayModeList1", DESCRIPTORS[19].toMethodType());
                handles[20] = lookup.findVirtual($UPCALL.class, "FindClosestMatchingMode1", DESCRIPTORS[20].toMethodType());
                handles[21] = lookup.findVirtual($UPCALL.class, "GetDisplaySurfaceData1", DESCRIPTORS[21].toMethodType());
                handles[22] = lookup.findVirtual($UPCALL.class, "DuplicateOutput", DESCRIPTORS[22].toMethodType());
                handles[23] = lookup.findVirtual($UPCALL.class, "SupportsOverlays", DESCRIPTORS[23].toMethodType());
                handles[24] = lookup.findVirtual($UPCALL.class, "CheckOverlaySupport", DESCRIPTORS[24].toMethodType());
               return handles;
           } catch (ReflectiveOperationException e) {
               throw new RuntimeException(e);
           }
       }
   }
}
