// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.system.libraryloader;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_BYTE;

/**
 * Functions of namespace {@code Windows.Win32.System.LibraryLoader}
 */
public class Apis {

    

    private static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup("KERNEL32.dll", Arena.global());
    private static final Linker LINKER = Linker.nativeLinker();
    private static final Linker.Option LAST_ERROR_STATE = Linker.Option.captureCallState("GetLastError");
    private static final AddressLayout ADDRESS$UNKNOWN_SIZE = ADDRESS.withTargetLayout(MemoryLayout.sequenceLayout(Long.MAX_VALUE, JAVA_BYTE));

    private static class GetModuleHandleW$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(ADDRESS, ADDRESS$UNKNOWN_SIZE);
        private static final MethodHandle HANDLE = LINKER.downcallHandle(SYMBOL_LOOKUP.findOrThrow("GetModuleHandleW"), DESC, LAST_ERROR_STATE);
    }

    /**
     * Gets the function descriptor for {@code GetModuleHandleW}
     * <p>
     * The additional first parameter takes a memory segment to capture the call state (replacement for {@code GetLastError()}).
     * </p>
     */
    public static FunctionDescriptor GetModuleHandleW$descriptor() {
        return GetModuleHandleW$IMPL.DESC;
    }

    /**
     * Gets the method handle for {@code GetModuleHandleW}
     */
    public static MethodHandle GetModuleHandleW$handle() {
        return GetModuleHandleW$IMPL.HANDLE;
    }

    /**
     * {@code GetModuleHandleW} function
     * <p>
     * {@snippet lang=c :
     * HMODULE GetModuleHandleW(
     *     PWSTR lpModuleName
     * );
     * }
     * </p>
     * <p>
     * The additional first parameter takes a memory segment to capture the call state (replacement for {@code GetLastError()}).
     * </p>
     *
     * @see <a href="https://learn.microsoft.com/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandlew">GetModuleHandleW (Microsoft)</a>
     */
    public static MemorySegment GetModuleHandleW(MemorySegment lastErrorState, MemorySegment lpModuleName) {
        try {
            return (MemorySegment) GetModuleHandleW$IMPL.HANDLE.invokeExact(lastErrorState, lpModuleName);
        } catch (Throwable ex) {
            throw new RuntimeException(ex);
        }
    }

}
