// Code generated by Windows API Generator.
// Do not modify manually.

package windows.win32.system.threading;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.*;

/**
 * Functions of namespace {@code Windows.Win32.System.Threading}
 */
public class Apis {

    

    private static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup("KERNEL32.dll", Arena.global());
    private static final Linker LINKER = Linker.nativeLinker();
    private static final Linker.Option LAST_ERROR_STATE = Linker.Option.captureCallState("GetLastError");

    private static class WaitForSingleObject$IMPL {
        private static final FunctionDescriptor DESC = FunctionDescriptor.of(JAVA_INT, ADDRESS, JAVA_INT);
        private static final MethodHandle HANDLE = LINKER.downcallHandle(SYMBOL_LOOKUP.findOrThrow("WaitForSingleObject"), DESC, LAST_ERROR_STATE);
    }

    /**
     * Gets the function descriptor for {@code WaitForSingleObject}
     * <p>
     * The additional first parameter takes a memory segment to capture the call state (replacement for {@code GetLastError()}).
     * </p>
     */
    public static FunctionDescriptor WaitForSingleObject$descriptor() {
        return WaitForSingleObject$IMPL.DESC;
    }

    /**
     * Gets the method handle for {@code WaitForSingleObject}
     */
    public static MethodHandle WaitForSingleObject$handle() {
        return WaitForSingleObject$IMPL.HANDLE;
    }

    /**
     * {@code WaitForSingleObject} function
     * <p>
     * {@snippet lang=c :
     * WAIT_EVENT WaitForSingleObject(
     *     HANDLE hHandle,
     *     DWORD dwMilliseconds
     * );
     * }
     * </p>
     * <p>
     * The additional first parameter takes a memory segment to capture the call state (replacement for {@code GetLastError()}).
     * </p>
     *
     * @see <a href="https://learn.microsoft.com/windows/win32/api/synchapi/nf-synchapi-waitforsingleobject">WaitForSingleObject (Microsoft)</a>
     */
    public static int WaitForSingleObject(MemorySegment lastErrorState, MemorySegment hHandle, int dwMilliseconds) {
        try {
            return (int) WaitForSingleObject$IMPL.HANDLE.invokeExact(lastErrorState, hHandle, dwMilliseconds);
        } catch (Throwable ex) {
            throw new RuntimeException(ex);
        }
    }

}
