// Code generated by Windows API Generator.
// Do not modify manually.

package system;

import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@code GUID} structure
 * <p>
 * {@snippet lang=c :
 * struct GUID {
 *    DWORD Data1;
 *    WORD Data2;
 *    WORD Data3;
 *    BYTE[8] Data4;
 * }
 * }
 * </p>
 */
public class Guid {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        JAVA_INT.withName("Data1"),
        JAVA_SHORT.withName("Data2"),
        JAVA_SHORT.withName("Data3"),
        MemoryLayout.sequenceLayout(8L, JAVA_BYTE).withName("Data4")
    );

    /**
     * Gets the layout of the struct {@code GUID}.
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Gets the size of the struct {@code GUID} (in bytes).
     */
    public static long sizeof() {
        return 16L;
    }

    /**
     * Gets the offset of the field {@code Data1} (in bytes).
     */
    public static long Data1$offset() {
        return 0L;
    }

    /**
     * Gets the value of field {@code Data1} in {@code segment}.
     */
    public static int Data1(MemorySegment segment) {
        return segment.get(JAVA_INT, 0L);
    }

    /**
     * Sets the field {@code Data1} in {@code segment} to {@code value}.
     */
    public static void Data1(MemorySegment segment, int value) {
        segment.set(JAVA_INT, 0L, value);
    }

    /**
     * Gets the offset of the field {@code Data2} (in bytes).
     */
    public static long Data2$offset() {
        return 4L;
    }

    /**
     * Gets the value of field {@code Data2} in {@code segment}.
     */
    public static short Data2(MemorySegment segment) {
        return segment.get(JAVA_SHORT, 4L);
    }

    /**
     * Sets the field {@code Data2} in {@code segment} to {@code value}.
     */
    public static void Data2(MemorySegment segment, short value) {
        segment.set(JAVA_SHORT, 4L, value);
    }

    /**
     * Gets the offset of the field {@code Data3} (in bytes).
     */
    public static long Data3$offset() {
        return 6L;
    }

    /**
     * Gets the value of field {@code Data3} in {@code segment}.
     */
    public static short Data3(MemorySegment segment) {
        return segment.get(JAVA_SHORT, 6L);
    }

    /**
     * Sets the field {@code Data3} in {@code segment} to {@code value}.
     */
    public static void Data3(MemorySegment segment, short value) {
        segment.set(JAVA_SHORT, 6L, value);
    }

    /**
     * Gets the offset of the field {@code Data4} (in bytes).
     */
    public static long Data4$offset() {
        return 8L;
    }

    /**
     * Gets the field {@code Data4} of {@code segment}.
     * <p>
     * The returned memory segment is a slice of {@code segment} and shares the backing memory.
     * </p>
     */
    public static MemorySegment Data4(MemorySegment segment) {
        return segment.asSlice(8L, 8L, 1L);
    }

    /**
     * Copies {@code value} into the field {@code Data4} in {@code segment}.
     */
    public static void Data4(MemorySegment segment, MemorySegment value) {
        MemorySegment.copy(value, 0L, segment, 8L, 8L);
    }

    /**
     * Allocates a new memory segment for the struct {@code GUID}.
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(16L, 4L);
    }

    /**
     * Gets the element with index {@code index} of the specified {@code GUID} array.
     * <p>
     * The returned memory segment is a slice of {@code array} and shares the backing memory.
     * </p>
     */
    public static MemorySegment elementAsSlice(MemorySegment array, long index) {
        return array.asSlice(16L * index, 16L);
    }

    /**
     * Allocates an array of {@code elementCount} elements of this struct.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(16L * elementCount, 4L);
    }

    private Guid () {}
}
